### ISSUE TITLE
Kernel Panic for iPhone 6s Plus iOS 10.2

### ISSUE THREAD

**Issue by EGYbkgo9449** [kpwn/yalu102#1]
Hey,
I've tried the jailbreak about 10 times but it resprings the device and nothing happen, here is the kernel panic log:

http://pastebin.com/BGkLuSMG

**Comment by Samohtemmitt** [comment]
Dude, give him a break!  He just posted this an hour ago, and it clearly says INCOMPLETE in the description.

**Comment by Lugimax** [comment]
Well, he posted the problem, it can help them. I think he did the right thing.

**Comment by EPiCxRIOTZZ** [comment]
i opened the project and all i keep getting is iokit/iokitlib.h isnt found, even when i have manually imported it and i imported it through terminal but no luck

**Comment by Lugimax** [comment]
EPiCxRIOTZZ, make another issue. Don't write it here

**Comment by nullpixel1** [comment]
@EPiCxRIOTZZ You need to include the headers. 
[headers.zip](https://github.com/kpwn/yalu102/files/730770/headers.zip)

**Comment by EGYbkgo9449** [comment]
I've just posted the issue so they'll know it's not working for the 6S Plus, I'm not forcing them to fix it #lol

And @EPiCxRIOTZZ, Just download IOKit from the internet #lol

**Comment by Lugimax** [comment]
nullpixel1, how do you think, when will they release working/somewhat stable jailbreak with cydia for 10.2?

**Comment by kpwn** [comment]
I do not currently have access to any device but iPad Pro 9.7". 

Can you tell me at which point it crashes?

**Comment by Alphawolf49** [comment]
@Lugimax where was the problem posted at?

**Comment by nullpixel1** [comment]
@kpwn Yeah, 

On the 6s 10.2, after running it, it hangs at go, then just reboots.

My syslog is almost identical to the one attached to the issue.

**Comment by EGYbkgo9449** [comment]
@kpwn
I've attached the kernel panic ^^^

**Comment by osxusr** [comment]
can i get a compiled version so i can try on my 6s on 10.2 ?

**Comment by albyvar** [comment]
Kernel panic also for me, and sometimes it says "failed. retry"

**Comment by drake90001** [comment]
`2017-01-25 14:32:24.766193 yalu102[238:5172] found corruption 37c03`

is where it crashed on my 6s

**Comment by EGYbkgo9449** [comment]
@albyvar
Yep, but it happened only 1 time for me

**Comment by rpalmieri99** [comment]
Osxusr you have to compile it. It isn't offered in compiled yet because it's prebeta.

**Comment by EGYbkgo9449** [comment]
@drake90001 
It fails here for me:

2017-01-25 23:35:25.606834 yalu102[284:15797] found corruption 39303

**Comment by osxusr** [comment]
i know its prebeta

**Comment by TheNoim** [comment]
For me it also crashes. I have a 5s gsm. Only the app is crashing at
´´´
found corruption 38103
´´´
I tried to change allproc_offset and set kernproc_offset but I don't know what procoff is.

**Comment by rpalmieri99** [comment]
Osxusr so compile it yourself.

**Comment by dani0l** [comment]
`2017-01-26 01:43:19.531065 yalu102[1050:277809] found corruption 38b03`

Says the same on 10.1.1 iPhone 6 Plus

**Comment by kpwn** [comment]
closing due to derailing. this is not a manual. 
anyway, issue is that you need to add the rootvnode offset and the allprocs offset to offset.c

rootvnode is a KPI, you can simply nm a decompressed kernel.
allprocs is a la mach portal

**Comment by Tmahendra** [comment]
http://imgur.com/a/wVYEB Help me with the IOKit Issue please.
