### ISSUE TITLE
Killed:9 error

### ISSUE THREAD

**Issue by CrypticGit** [kpwn/yalu102#101]
I get killed 9 error in terminal when running commands Luca made a post on this for pangu does it apply for Yalu?

https://www.reddit.com/r/jailbreak/comments/44ott8/question_is_there_a_fix_for_this_killed_9_error/?st=IYF5J2ZZ&sh=e209f4d0

**Comment by dado3212** [comment]
Did trying his proposed solution resolve it?

**Comment by CrypticGit** [comment]
@dado3212 Yes i tried ldid -s

**Comment by dado3212** [comment]
"To fix, just copy the file to some other place, remove the original and rename it back. Should do the trick, since you're creating a new vnode."

**Comment by CrypticGit** [comment]
@dado3212 i tried this in yalu beta 3 but didnt work will it work in 10.2?

**Comment by kpwn** [comment]
'when running commands' -> which command? try ldid -S (uppercase s)

**Comment by CrypticGit** [comment]
@kpwn I've tried that

**Comment by kpwn** [comment]
You have so many issues yet 0 logs or 0 explanations of what is going on. Please take 5 minutes to properly report issues as I mentioned in your other recently closed issue.
