### ISSUE TITLE
iPad Mini 2 (WiFi) not jailbreaking

### ISSUE THREAD

**Issue by TheModdersDen** [kpwn/yalu102#106]
I've ran the program using Xcode (on my device running iOS 10.1.1) and it gets past the offset code. The code I ran was directly from this repository (No modifications added, with the exception of importing the IOKit Framework). However, it crashes and reboots back to normal iOS. I've tried logging into the SSH server built into this app, but it says "connection refused."
I made a pastebin of the log for reference:  http://pastebin.com/cy1e56gn

Any ideas/solutions?

**Comment by liudayu** [comment]
YEAH THIS JAILBREAK DOES NOT SUPPORT IPAD MINI 2 (WIFI) YET, DO YOU UNDERSTAND NOW

WHY THE **** WON'T PEOPLE LIKE YOU DO SOME RESEARCH BEFORE YOU POST THOSE STUPID ISSUES

**Comment by TheModdersDen** [comment]
OK. Because I read through the code, and it would display the fact that it would have failed. It did not, however, and continued along. I'm just trying to submit a log for the developers of this jailbreak to reference so they can add support for this device fully...

**Comment by nicogibbons** [comment]
It is because 4k devices aren't supported. Please close this :/

**Comment by liudayu** [comment]
qwertyoruiop doesn't have the devices to test this jailbreak yet, so please wait patiently. He said he will be able to do some testing during the weekend. 
Please close this issue.

**Comment by TheModdersDen** [comment]
OK. Will do.

**Comment by TheModdersDen** [comment]
Ok. Will do...
