### ISSUE TITLE
Find the offsets

### ISSUE THREAD

**Issue by cawk** [kpwn/yalu102#11]
Could you make a write up on how to find the offsets for our device and iOS like p0 did it would save you time and since you don't have the devices anyway it could help for more support 

The allproc offset is the one from Mach portal right?
The other two we don't know how to get so maybe you could explain to us how like project zero did

Regards
Cawk

**Comment by nicogibbons** [comment]
:>

**Comment by kpwn** [comment]
not at this point in time.

**Comment by williamfs** [comment]
Here is a nice write up:
https://bugs.chromium.org/p/project-zero/issues/detail?id=965#c2

here is a command to do it:
https://gist.github.com/jndok/2a01a5885552571a69341a9700ac1bb0
