### ISSUE TITLE
To @qwertyuiopz

### ISSUE THREAD

**Issue by daniel63194** [kpwn/yalu102#110]
Marco Grassi: We uaglio bell stu jailbreak

**Comment by daniel63194** [comment]
(in italian) (ironic)

**Comment by BadLamb** [comment]
Boia dio non usare le issues in sta maniera

**Comment by BadLamb** [comment]
Madonna canaglia, quando capiranno...

**Comment by daniel63194** [comment]
perche??

**Comment by BadLamb** [comment]
Servono per i problemi in Yalu, non per fare i coglioni

**Comment by KILLCAMPER** [comment]
English would be amazing

**Comment by kpwn** [comment]
to english speakers: you're not losing out on anything

**Comment by KILLCAMPER** [comment]
Thank you it was keeping me up ☝️
