### ISSUE TITLE
No Crash Logs Produced in Jailbroken Mode

### ISSUE THREAD

**Issue by iAdam1n** [kpwn/yalu102#112]
So I just accidentally found a bug with Yalu on iOS 10.2 on my iPhone 6s. In jailbroken mode, you don't get crash logs for SpringBoard or apps. I found this first when Cydia and Messages app crashed then I had no logs. I've removed all tweaks I installed including Cydia Substrate so this has to be an issue with Yalu itself.

**Comment by nullpixel1** [comment]
Yeah, I'm also having this issue

**Comment by kpwn** [comment]
Weird. This only happens when in jailbroken mode?

**Comment by kpwn** [comment]
Anyway I bet this is a permission issue due to how I extract the bootstrap tar. :X

**Comment by iAdam1n** [comment]
@kpwn Yes. I tried the known NC bug that if you are mostly on widgets screen while holding the screen and tap the search bar, the device resprings (even on stock iOS). That showed me a SpringBoard log in non jb mode but not when booted into jb mode.

**Comment by andrewwiik** [comment]
@kpwn can we have a update on this issue?

**Comment by shinvou** [comment]
I also can't log from within tweaks.

**Comment by nicogibbons** [comment]
@kpwn latest commit fixes?
