### ISSUE TITLE
Stuck on while loop after "found kernel text"

### ISSUE THREAD

**Issue by Mistah-Sheep** [kpwn/yalu102#12]
Trying out the jailbreak on my iPhone 6 (7,2) and I get passed the crash that most are having at found corruption but then it freezes afterwards at "found kernel text at" I did some logging in the code and it seems to be stuck at the while loop around line 247 (`while (proc_) {`) any ideas?

This _is_ running while still attached to Xcode by the way.

**Comment by nicogibbons** [comment]
Not Supported you nugget

**Comment by DarknesGaming** [comment]
@nicogibbons is right. You can, however, figure out how to fix this.
Also, what iOS version are you using?

**Comment by Mistah-Sheep** [comment]
@nicogibbons Damn well it doesn't say that anywhere...

@DarknesGaming iOS 10.2

**Comment by Mistah-Sheep** [comment]
Appears the offset I got was incorrect, used a different kernel cache and it continued on down to another crash, the hunt continues!

**Comment by nicogibbons** [comment]
lol good luck

**Comment by Mistah-Sheep** [comment]
`0x5b8468` is the one I used to continue but I think I had `0x5a8438` before that
