### ISSUE TITLE
Nothing would install 

### ISSUE THREAD

**Issue by brasilejustin** [kpwn/yalu102#121]
Cydia Substrate and everything else wouldn't install it always crashed on iPhone 6s

**Comment by iOptimistic** [comment]
Post on /r/Jailbreak and close this issue. The Issues section is for ***Code Related Problems Only***.

**Comment by RypeDub420** [comment]
This issue is not fully documented, nor is this Support for Packages AFTER running the jailbreak.

This GitHub is ONLY for issues with the jailbreaking process its self.

Please close this issue.

**Comment by CrypticGit** [comment]
please send error messages on whatever place you are posting
