### ISSUE TITLE
Substrate does not restart when respringing out of Safe Mode.

### ISSUE THREAD

**Issue by Sticktron** [kpwn/yalu102#123]
Substrate safe mode is kinda broken: it resprings right away, and when SpringBoard starts again Substrate isn't reloaded.

This could be on @saurik to fix, just thought I'd add it here in case the reloading issue is due to the jailbreak in some way. Close this if it's not relevant.

**Comment by xnuos** [comment]
Fixed in latest commit I heard.
Check Closed Issues, think I saw one like this.
Might be able to reference it...

**Comment by Sticktron** [comment]
Tried as of 6:30PM, still the same.

**Comment by kpwn** [comment]
i don't think this is a problem with yalu

**Comment by sidpagariya** [comment]
So do we remove our tweaks?
