### ISSUE TITLE
How fix sub process /usr/libexec/cydia/cydo returned an error code (2)?

### ISSUE THREAD

**Issue by christo98** [kpwn/yalu102#124]
Please help me,i can't use pc to restore,there is something to do to fix it? I can't be able to install or disinstall tweaks,i have to wait for a new beta?

**Comment by xnuos** [comment]
This is a Cydia error, not yalu. This exact error soulution can be found on Google. This is not the place to post this, search before you post. 
Thank You.

**Comment by xnuos** [comment]
Solution*
And Please Close this Issue.

**Comment by CrypticGit** [comment]
@xnuos i had this error as well but im my case it was a yalu error. For some reason yalu didn't failed to grant me write access. and it didn't sometimes happen it happened all the time then i installed the latest yalu and it doesnt happen.

**Comment by CrypticGit** [comment]
https://www.reddit.com/r/jailbreak/comments/5qer1d/tutorial_how_to_fix_subprocess/

**Comment by christo98** [comment]
I don't have access to root,i think it's an error of yalu jailbreak

**Comment by CrypticGit** [comment]
Then you have to get the lasted uncompiled version of yalu and compile and install yourself

**Comment by christo98** [comment]
I don't have pc,i install ipa with appdb,somebody can compile me and send me the ipa? Please i'm desperate

**Comment by CrypticGit** [comment]
Pc?

**Comment by christo98** [comment]
I don't have computer and i don t have mac

**Comment by CrypticGit** [comment]
How are you installing it again? and heres link https://www.dropbox.com/s/fjcmq0c3oldzsr3/yalu102.ipa?dl=0

**Comment by meyer9** [comment]
It's recommended you don't download from random people off the internet.

**Comment by christo98** [comment]
I use appdb to sign the app without pc,now i try

**Comment by RypeDub420** [comment]
You need a VM, DualBoot Hackintosh or a Mac in order to compile using Xcode.

**Comment by CrypticGit** [comment]
@meyer9 your right you can check the hash to be sure i have not tampered with it i took it strate from debug folder of xcode

**Comment by CrypticGit** [comment]
@ryanb93 Are you following to conversation? he doesn't have a computer at all

**Comment by RypeDub420** [comment]
Also, you just need to use CydiaImpactor to install and ANYONES Apple ID log in information (that isn't blocked from the apple developer program for selling certs).

**Comment by RypeDub420** [comment]
Did not know the OP doesn't have a computer at all.

Good luck.

**Comment by CrypticGit** [comment]
Please close this if it works

**Comment by christo98** [comment]
I use appdb i can install ipa without pc

**Comment by CrypticGit** [comment]
I have a ipastore membership ill try it with that

**Comment by xnuos** [comment]
He shouldn't be even jailbreaking without a computer. Especially not in Alpha. There is ways to fix this but he isn't capable of doing them or at least maneuvering around a command-line (which seems to be required a lot in this state.) 

As stated above Good Luck.

**Comment by christo98** [comment]
You can link me to that? (Sorry foto bad english i'm italian)

**Comment by CrypticGit** [comment]
@xnuos when i had this issue the only way to fix was getting latest xcode project

**Comment by CrypticGit** [comment]
Link for what?

**Comment by christo98** [comment]
The ipa you send me is based in the latest Xcode project?

**Comment by CrypticGit** [comment]
https://www.dropbox.com/s/fjcmq0c3oldzsr3/yalu102.ipa?dl=0

**Comment by christo98** [comment]
I install it and re-jailbreak butti have the same error

**Comment by CrypticGit** [comment]
Then follow the reddit post. What device? what model? what ios?

**Comment by christo98** [comment]
iPhone 6s ios 10.2 64gb,i can't follow the reddit post because i don't have pc

**Comment by CrypticGit** [comment]
You dont need a pc wym?

**Comment by christo98** [comment]
I don't need? So i don't understand how fix it

**Comment by CrypticGit** [comment]
Follow what it says to do click the links

**Comment by christo98** [comment]
In the reddit link they Say to use a computer

**Comment by CrypticGit** [comment]
Hey look just click each link and import to ifile and install through ifile

**Comment by christo98** [comment]
Yes but i can't install iFile becouse i have this error in Cydia,i can't install tweaks

**Comment by CrypticGit** [comment]
Sideload it the same way you installed yalu

**Comment by christo98** [comment]
I can install only ipa Not .deb files

**Comment by CrypticGit** [comment]
https://www.dropbox.com/s/smq2zde7mjszahk/iFile.ipa?dl=0

**Comment by christo98** [comment]
Can i contact you somewhere to send you screenshot?

**Comment by CrypticGit** [comment]
twitter @cryptiiiic

**Comment by christo98** [comment]
I followed you,but how can i send you private messagge? I don't use Twitter so i'm a lutto e noob

**Comment by CrypticGit** [comment]
I had to follow you back now you can dm me
