### ISSUE TITLE
6s TSMC EXC_CRASH Thread 0 & ForkException

### ISSUE THREAD

**Issue by xnuos** [kpwn/yalu102#125]
I don't if this was fixed in last commit but I will post it just in case :/ (sorry if redundant, I searched closed issues but I didn't find this exact, maybe I missed it :( anyways if you find it reference explanation and close please). 

My model is supported, jailbreak works fine, however I did see someone post the issue of random resprings and it was fixed in the latest commit, however this continues to happen to me randomly.  

Specs: Test Device TSMC Chip - i6s - Literally Clean Install.

Crash Log: [Click Me](http://www.pastebin.com/HB9PXDZJ)

Also, upon respring, apps crash upon opening. 
Sometimes all apps crash, 
sometimes only apps installed with Jailbreak (Cydia, Crash Reporter, etc.) crash, 
sometimes some don't crash and others do (seems random), 
and then sometimes only terminal can open where it gives me a 

`"ForkException: Failed to fork child process (35: Resource is temporarily unavailable)."`

Odd thing is sometimes it just keeps giving this error in the terminal, and then sometimes it does it 1-4 times and then gives me access to the command line.

Restarting the phone fixes this, however it can happen several times in an hour.

**Comment by meyer9** [comment]
What apps? What tweaks? Looks like a kernel panic.

**Comment by xnuos** [comment]
Packages  under User are as follows:
Crash Reporter
Cydia Installer
Cydia Substrate
Cydia Translations
CyPush (Might Cause it idk, I'll uninstall now, however has been disabled in iCleaner, still receives crash)
Darwin CC Tools
Flex 3 (Nothing enabled, just sits there, removed before posting)
iFile (I know its outdated, still semoved, still received crash)
iCleaner
LD64
MusiLyric (Removed, still received crash)
Patcyh
Substrate Safe Mode
SwipeForMore

If you want the full list I will pull it, however everything installed installed automatically. And all comes from Cydia/Telesphoreo apt.saurik.com

**Comment by Skiddi3** [comment]
Does the `free` command work on iOS?

**Comment by kpwn** [comment]
this is an unrelated issue to yalu
