### ISSUE TITLE
[Can be a tester] possible on tvOS ?

### ISSUE THREAD

**Issue by onchehuh** [kpwn/yalu102#13]
Is it possible to adapt for tvOS 10.0.1 / 10.1 (equivalent to iOS10.2 I think) ?
I can test anything you post on my Apple TV.
Thanks !

**Comment by thebeastgamer25** [comment]
XDXDXDXD

**Comment by kpwn** [comment]
It may be, but not sure if it works right now.

**Comment by onchehuh** [comment]
@kpwn okay
Some functions are not allowed in tvOS sdk by default so I commented related __TVOS_PROHIBITED.
Trying to deal with IOKit now
