### ISSUE TITLE
tfp0 on yalu102

### ISSUE THREAD

**Issue by CrypticGit** [kpwn/yalu102#132]
Is tfp0 enabled on yalu102? Because when I try to use nonceEnabler it failed to get kernel base address. In the logs for yalu I remember seing something about tfp0.

**Comment by msamuel002** [comment]
nonceenabler is only supported for ios 9 i thought

**Comment by CrypticGit** [comment]
@msamuel002 it supports ios with jailbreak that enables tfp0

**Comment by msamuel002** [comment]
oh true dat but lol i dont know much about that stuff....sorry

**Comment by msamuel002** [comment]
apparently all jailbreaks from ios 5 till ios 9 have had tfp0 enabled, but since this jb is new, idk.

**Comment by minh6a** [comment]
On yalu mach-portal (old yalu that support iP7 on 10.1.1) qwertyoruiopz added tfp0 so I don't see why yalu102 don't support it.

Anw iOS 10 kernel is decrypted so patching tfp0 is easier and support for tfp0 should come in the future.

**Comment by CrypticGit** [comment]
@minh6a do you think downgrading to 10.1.1 is worth it for 6s?

**Comment by minh6a** [comment]
All 64 bit is supported in yalu102 so I don't see any benefit downgrading to 10.1.1, but i'm not saying you must stay on 10.2 either. But adding the possible touch ID break on downgrading to 10.1.1 I would say it is not worth it

**Comment by CrypticGit** [comment]
@minh6 touchid doesn't break anymore if you use the 10..2.1 sep

**Comment by minh6a** [comment]
Nope, 10.2.1 sep does NOT compatible with 10.1.1... Idk where you get your source saying 10.2.1 does not break touchid on 10.1.1

**Comment by CrypticGit** [comment]
@minh6 probly Reddit retards 😂

**Comment by minh6a** [comment]
/r/jb has a thread for SEP, search it

**Comment by nicogibbons** [comment]
Just to clear yes the 10.2.1 SEP is compatible with iOS 10.2 and yes Touch ID still works. 10.2.1 SEP is not compatible with 10.1.1 SEP so Touch ID will break.

**Comment by SuBLiNeR** [comment]
Pls close this, it is already stated on reddit.com/r/jailbreak that it is not affecting it if you using right SEP

**Comment by kpwn** [comment]
yalu102 does not yet support tfp0, although being opensource it's easy to add it yourself.

it will have it whenever i'm not lazy enough to not want to work on patchfinding.

**Comment by msamuel002** [comment]
@kpwn are you still working on adding support? just not bugs with the code?

**Comment by CrypticGit** [comment]
@msamuel002 if ur interested the trident jb has open source tfp0 called clover
