### ISSUE TITLE
Anyone know if this works on iPad Air 2 gsm and wifi? 

### ISSUE THREAD

**Issue by B0ngL0rd** [kpwn/yalu102#133]
???

**Comment by AppleBetas** [comment]
As it says right on the front page, in the readme. [No, it does not (for now).](https://github.com/kpwn/yalu102#supported-devices)

In addition, issues are for code issues, not asking for help or inquiring about features.

**Comment by B0ngL0rd** [comment]
Open source is it not?

**Comment by AppleBetas** [comment]
It is open source. That doesn't mean the section dedicated to code issues is meant for asking questions.

Close this, please.

**Comment by B0ngL0rd** [comment]
So it's the offsets that need replacing as per devices?

**Comment by nicogibbons** [comment]
Offsets are fine. The code doesn't support 4K devices yet.

**Comment by nicogibbons** [comment]
My turf @AppleBetas

**Comment by liudayu** [comment]
@B0ngL0rd I've seen you asking the same questions so many times, I don't know if you don't understand English or what's your problem. Maybe try translate.google.com and put "NO jailbreak for iPad Air 2, yet" and change the translated language to whatever language you speak. Hope that helps.
Close this issue please.
