### ISSUE TITLE
License

### ISSUE THREAD

**Issue by SableWalnut** [kpwn/yalu102#136]
As the source for this project is public, it should probably be licensed for it to truly be open source. The `README.md` file says 'Please respect copyright laws.', and this project having a license would certainly help that. https://choosealicense.com/ and https://opensource.org/licenses are worth looking at. :)

**Comment by turingsecurity** [comment]
It's already licensed.

**Comment by Dennisbonke** [comment]
Site states that the license is wtfpl (see: https://yalu.qwertyoruiop.com)

**Comment by nullpixel1** [comment]
hey @SableWalnut I added the copyright laws clause to the readme.

This is in referral to IOKit headers & redistribution.

**Comment by SableWalnut** [comment]
It tends to be common practice to put a `LICENSE` file at the root of the source?

**Comment by nullpixel1** [comment]
I've made a PR to do this. #137

**Comment by turingsecurity** [comment]
kpwn is going to reject any license modifications you make because the project is already licensed exactly how he wants, he doesn't want an open source license he prefers the "anyone but stefan esser" license that is already implemented and active.

**Comment by nullpixel1** [comment]
@turingsecurity It's the same license as on his site, but I added it to the repo because some people don't read the compiled site.

Note, https://yalu.qwertyoruiop.com states

> licensed under wtfpl

**Comment by nullpixel1** [comment]
#137 was just merged,

@kpwn you're good to close this 👍
