### ISSUE TITLE
ViewController.m requires refactoring?

### ISSUE THREAD

**Issue by eklipse2009** [kpwn/yalu102#138]
In file yalu102/ViewController.m there is a function 
- (IBAction)yolo:(UIButton*)sender
which starts on line 140 and follows till the end of the file and contains "goto" operators, which are considered a big "no-no" by vast majority of the community.
Please correct me if I'm wrong and this is just an optimization technique (maybe goto is faster than executing an extracted function/method).

**Comment by nullpixel1** [comment]
@kpwn Are you okay with me refactoring the view controller?

**Comment by kpwn** [comment]
> contains "goto" operators, which are considered a big "no-no" by vast majority of the community

lol what
