### ISSUE TITLE
How come my screen go's completely black ?

### ISSUE THREAD

**Issue by CrypticGit** [kpwn/yalu102#14]
In yalu1011 it has wierd screen distortion then it kernel panics. this time its instant to black and reboots.

sysname: Darwin
nodename: 0
release: 16.3.0
version: Darwin Kernel Version 16.3.0: Tue Nov 29 21:40:09 PST 2016; root:xnu-3789.32.1~4/RELEASE_ARM64_S8000
machine: iPhone8,1
2017-01-25 15:58:58.675005 yalu102[237:5001] found corruption 37c03

**Comment by nicogibbons** [comment]
Not Supported

**Comment by CrypticGit** [comment]
@nicogibbons to make it supported do you know what offsets have to be found

**Comment by ninjaprawn** [comment]
allproc and rootvnode

**Comment by CrypticGit** [comment]
@ninjaprawn ive almost found allproc but where do i replace vnode in?
