### ISSUE TITLE
Reboot iPhone SE TSMC when I'm trying to jailbreak Respring loop

### ISSUE THREAD

**Issue by kdc11** [kpwn/yalu102#143]
Hi, Yalu102 Jaibreak works only on first attempt on iPhone SE TSMC when I fresh restore it via iTunes, when I reboot iDevice and jailbreak again I get respring loop. I have partially fixed the problem by replacing def.plist for TSMC fix from previous jailbreak "mach_portal+yalu-b3.app", I renamed it to 0.reload.plist. Then I replaced 0.reload.plist (ex-def.plist) in the new yalu102_alpha.app or in the Xcode Yalu102 folder.

**Comment by kdc11** [comment]
nvm it's a problem with zypen tweak

**Comment by SparksCatcher** [comment]
Yep. It's broken. Fortunately I had AFC2, and was able to remove the dylibs.

**Comment by nerdtron123** [comment]
Please close this issue.
