### ISSUE TITLE
failed retry

### ISSUE THREAD

**Issue by mrpg99** [kpwn/yalu102#145]
Hi,
I just updated my iphone 6s to 10.2

and used cydia impactor to upload the yalu102 jb

when i press GO , to start the jauilbreak, i only get "failed, retry"

what am i doing wrong?

Best Regards
Patric

**Comment by JoeGodz** [comment]
How many times have you tried?

**Comment by mrpg99** [comment]
bugger, answering myself....

i apparently got 10.2.1 installed :(

**Comment by JoeGodz** [comment]
Yeah, good thing Apple is still signing ios 10.2, that could've been bad haha

**Comment by bobbysn0w** [comment]
#612

**Comment by Dennisbonke** [comment]
#162 he means

**Comment by bobbysn0w** [comment]
@Dennisbonke thanks again
