### ISSUE TITLE
NSLogging not working?

### ISSUE THREAD

**Issue by Sticktron** [kpwn/yalu102#150]

**Comment by tangalbert919** [comment]
Are you getting zero output from the console?

**Comment by nullpixel1** [comment]
working for me

**Comment by Sticktron** [comment]
Lots of output, just not my NSLog statements. Tested with tweaks and an app.

**Comment by Sticktron** [comment]
@nullpixel1 After jailbreaking? Using which software to read them?

**Comment by Sticktron** [comment]
To clarify: I can see NSLog statements from yalu102 itself, but not my apps/tweaks after being jailbroken.

**Comment by Sticktron** [comment]
Not related to Yalu. Closing.

**Comment by AppleBetas** [comment]
May I ask what it was if it wasn't related to Yalu? @Sticktron

**Comment by Sticktron** [comment]
Not sure, Theos's HBLog macros and/or iOS 10's new logging system?
