### ISSUE TITLE
iPhone 7 Plus, iOS 10.1.1 Failed, Retry

### ISSUE THREAD

**Issue by LmaoCrim** [kpwn/yalu102#152]
Hi everyone, a while ago, I jailbroke my iPhone 7 with Yalu Beta 3. I saw Yalu102 was released, and I wanted to use that one. I uninstalled Cydia Installer, and then used iFile to delete cydia.app, and other jailbreak .app files. Then I went to Settings > General > Reset > Reset all content and settings. When that successfully completed, I installed yalu102 using Cydia Impactor, but as soon as i press go, a few seconds later, I get failed, retry. When I press retry, the iPhone usually crashes. Did I do something wrong?

**Comment by LmaoCrim** [comment]
I decided to try and install beta 3 again, and it works, however it isn't installing cydia. Is there any way I can get cydia back?

**Comment by big538** [comment]
terminal

$ apt-get remove Cydia ( if necessary,  autoremove)
$ apt-get install Cydia
$ apt-get install (-f)

$ uicache
$ su
 alpine ()
 reboot

**Comment by LmaoCrim** [comment]
Thank you, do you know where I can get to a terminal? I don't know if I can SSH into this phone, since I don't think I ever had OpenSSH installed

**Comment by rudd23** [comment]
Dropbear is built-in!

**Comment by LmaoCrim** [comment]
Ahh thank you, I used PuTTY for windows to ssh into the iphone using root as the username and alpine as the password. I typed apt-get install Cydia but it said "-sh: apt-get: command not found" Is there a different way I'm supposed to be doing this?

**Comment by tangalbert919** [comment]
Can you SSH into the iPhone using Dropbear?

**Comment by tangalbert919** [comment]
Scratch the question. Actually, that was in Cydia itself (I think, but I haven't analyzed the bootstrap.tar file in a long time), so chances are you need to re-jailbreak using the Yalu thing again.

**Comment by LmaoCrim** [comment]
When I rejailbreak it doesn't install Cydia, but it gives me root access, and I can SSH into the phone and see the root files using PuTTY for Windows

**Comment by tangalbert919** [comment]
Also, it is best to stick with the Yalu 10.1.1 app and not use this version because this is for devices before the iPhone 7 on 10.2.

**Comment by LmaoCrim** [comment]
I tried reinstalling the yalu 10.1.1 beta 3 app but it won't install cydia :( I do have root access though.

**Comment by Cydios** [comment]
Using browser (App Store, Documentspro etc) 
http://apt.saurik.com/beta/cydia-arm64/cydia_1.1.28~b5_iphoneos-arm.deb 
Download the deb file from this link and open it with iFile Please. Then reboot.

**Comment by Cydios** [comment]
Are you in a jailbreak state?

**Comment by LmaoCrim** [comment]
When I try to install with iFile it says unable to access dpkg status area: no such file or directory. I seem to be in a jailbroken state, but with no cydia

**Comment by Mila432** [comment]
https://github.com/kpwn/yalu102/issues/64

**Comment by LmaoCrim** [comment]
Sorry Mila432, I was just asking if someone could be nice and help me out here. :/

**Comment by tangalbert919** [comment]
I would say you should reset your phone, but then it will update itself and then actually do the reset thing.
That was a bad move, deleting Cydia from your phone, and resetting it. If you're still on iOS 10.1.1, try jailbreaking again. Use both the old and new IPAs that Luca has for download. If you're on iOS 10.2, you're f***ed, but Luca does recommend that you stay there.
By the way, those commands used for installing and packaging like "dpkg" and apt-get", require "sudo" to work, regardless if you have root access (is the kind of thing you want to say if you think a UNIX-like system like iOS would use commands found in Linux, which is based off of UNIX).
Also, try this:
sudo dpkg -i <replace this and the brackets with the package name>.deb

**Comment by tangalbert919** [comment]
*sigh* GitHub blocked those arrow brackets, so let's try this:
sudo dpkg -i cydia_1.1.28~b5_iphoneos-arm.deb
Saurik should update the internals of Cydia soon, because iPhoneOS 2.0 isn't supported by anything recent or deprecated anymore. iOS 4, that is still around.

**Comment by DaveX510** [comment]
In iFile change settings to show hidden files. Go to root and delete ".installed_yaluX". Reboot and run Yalu b3 should reinstall Cydia.

**Comment by bobbysn0w** [comment]
#612

**Comment by Dennisbonke** [comment]
I think he means #162

**Comment by bobbysn0w** [comment]
Yeah 😅  @Dennisbonke
