### ISSUE TITLE
To @kpwn

### ISSUE THREAD

**Issue by msamuel002** [kpwn/yalu102#154]
Hey Luca,
I know if I commented this on Twitter, you wouldn't see it, but that you would most likely see it on here. I am not making a new issue to say "add support" or anything like that, but I just wanted to say thank you for all that you and Marco have done to make this jailbreak possible. Everyone is saying that it is pretty much as stable or a little less stable then the 9.3.3 jb from pangu, which is very good news. Thanks again for all you've done, and keep up the good work!

**Comment by bobbysn0w** [comment]
^

Not necessary. Keep the issues for ***issues*** please.

**Comment by msamuel002** [comment]
Chill out I was trying to be nice @0x0luke
