### ISSUE TITLE
Can't install IPA

### ISSUE THREAD

**Issue by daniel63194** [kpwn/yalu102#155]
![cattura](https://cloud.githubusercontent.com/assets/25371965/22398904/6e896c82-e591-11e6-8b69-2a77f36f74f5.PNG)

It's saying that in Cydia Impactor
How can i solve this?

**Comment by AppleBetas** [comment]
[Apple Developer Centre is currently down](https://developer.apple.com/system-status/). You won't be able to install apps during this period of time. 

In addition, this issues page is for **CODE ISSUES**. You should ask in a more appropriate place, such as [/r/jailbreak](https://www.reddit.com/r/jailbreak).

**Comment by daniel63194** [comment]
Ok thanks
