### ISSUE TITLE
iPhone 6S reboots after jailbreak, but Cydia doesn't appear.

### ISSUE THREAD

**Issue by tootyta** [kpwn/yalu102#160]
So my iPhone 6S reboots after I click the go button in the jailbreak app, but Cydia doesn't appear. I've tried more than thirty times and I get the same issue.

**Comment by joshmedia2016** [comment]
mine working   fine and cydia working fine to dude

**Comment by joshmedia2016** [comment]
ive got substrate  installed and working great     try  jailbreak again  mate  then wait for   storage almost full warning that means jailbreak  succeeded

**Comment by bobbysn0w** [comment]
Please close this.

The issues section is strictly for ***coding issues***. If you have issues with the jailbreak itself go to /r/Jailbreak.

**Comment by tootyta** [comment]
Sorry, I'm new to github. Where is r/Jailbreak?

**Comment by beanjo55** [comment]
its a subreddit, on another website called reddit.com
