### ISSUE TITLE
how can i: Include the IOKit headers, and add them to your search path. ?

### ISSUE THREAD

**Issue by AbouImran** [kpwn/yalu102#164]

**Comment by osxusr** [comment]
find IOKit headers yourself (not including a link) put the folder into yalu102 where offsets are located

**Comment by AbouImran** [comment]
<img width="698" alt="iokit" src="https://cloud.githubusercontent.com/assets/24853903/22400809/62dad062-e5b7-11e6-9ef9-61578cf563bc.png">
like that?

**Comment by Dason-g** [comment]
@Aboulmran iphone 6

**Comment by AbouImran** [comment]
@Dason-g i have iPhone 6+

**Comment by Dason-g** [comment]
@Aboulmran yalu102 is compatible with iphone 6

**Comment by AbouImran** [comment]
<img width="1403" alt="error" src="https://cloud.githubusercontent.com/assets/24853903/22400923/ab91c7e6-e5b9-11e6-8ce1-80e00cbd302b.png">
i have pb with Xcode project

**Comment by onchehuh** [comment]
Change #include <xxx> into #include "xxx"

**Comment by Dason-g** [comment]
Yes or no

**Comment by edrflt** [comment]
read this.
https://github.com/kpwn/yalu102

**Comment by AbouImran** [comment]
<img width="1394" alt="error2" src="https://cloud.githubusercontent.com/assets/24853903/22400994/ea0d6d2a-e5bb-11e6-825f-194011773ad4.png">
@onchehuh same pb

**Comment by edrflt** [comment]
This is not a support board. Only code issues.
