### ISSUE TITLE
A question about KPP

### ISSUE THREAD

**Issue by iOS4all** [kpwn/yalu102#168]
Hi there. I have a question about KPP.
What do you mean by bypass it? Did you fully defeat KPP? Or just avoid it like Pangu jailbreak?
I ask this simple question because if you fully defeat it. Is it mean we should have JIT recompiler functionality like TaiG jailbreak? Because TaiG always come with patch kernel unlike Pangu always come with broken kernel because they just avoid it instead of defeat it.

Thanks a lot for your hard work.

**Comment by kpwn** [comment]
1: you don't need kernel patches for jit
2: yes it's a complete defeat
3: no i don't patch it, although i could

**Comment by iOS4all** [comment]
Did you mean by your jailbreak we could get JIT functionality like TaiG jailbreak did?
I mean for example if I select a dynarec core (not Interperter) of Pcsx in retroarch could it run because of JIT here? because I still remember when I jailbreak my device by Pangu first but it didn't work then I restored and jailbreak by TaiG and it works without any issues.

Sorry to bother you about my question. Thanks for your kind. Really appreciate...

**Comment by iOS4all** [comment]
@kpwn my final request if you don't mind. You said you're able to patch kernel.
If that's helped to could use JIT please patch it. We really miss it.
Please forgive my interest.
Thanks a lot.
