### ISSUE TITLE
iPhone 6 crashing

### ISSUE THREAD

**Issue by osxusr** [kpwn/yalu102#171]
I think mobile substrate might need a fix for the early 4k devices you added, just letting you know

**Comment by drakecsmall** [comment]
crashlogs?

**Comment by Skiddi3** [comment]
@osxusr He has close 2 of these issues and is looking in2 them already.

**Comment by FranticUmbreon** [comment]
How am I supposed to build it in xcode it has 2 errors

**Comment by beanjo55** [comment]
@FranticUmbreon #162

**Comment by Skiddi3** [comment]
@FranticUmbreon You need to change the bundle ID and sign it. If you can't figure it out don't try.
