### ISSUE TITLE
No Kernal Panic, but no Cydia

### ISSUE THREAD

**Issue by thebeastgamer25** [kpwn/yalu102#174]
Weird.......

**Comment by Skiddi3** [comment]
Crash logs

**Comment by thebeastgamer25** [comment]
None.

**Comment by kpwn** [comment]
ssh?

**Comment by thebeastgamer25** [comment]
@Skiddi3 None

**Comment by thebeastgamer25** [comment]
@kpwn what port?

**Comment by kpwn** [comment]
... 22?

**Comment by thebeastgamer25** [comment]
Lol, give me a sec

**Comment by AGagarin** [comment]
iPad Mini 2 LTE

default	05:56:39.949766 +0300	yalu102	subsystem: com.apple.UIKit, category: StatusBar, enable_level: 0, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
default	05:56:40.427793 +0300	yalu102	subsystem: com.apple.BackBoardServices.fence, category: App, enable_level: 1, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
default	05:56:41.162746 +0300	yalu102	subsystem: com.apple.BackBoardServices.fence, category: Observer, enable_level: 1, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
default	05:56:41.209343 +0300	yalu102	subsystem: com.apple.BackBoardServices.fence, category: Workspace, enable_level: 1, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
default	05:56:41.210857 +0300	yalu102	subsystem: com.apple.BackBoardServices.fence, category: Trace, enable_level: 1, persist_level: 0, default_ttl: 0, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 0, privacy_setting: 0, enable_private_data: 0
default	05:56:56.896115 +0300	yalu102	subsystem: com.apple.UIKit, category: Touch, enable_level: 0, persist_level: 0, default_ttl: 1, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
default	05:56:56.900788 +0300	yalu102	subsystem: com.apple.UIKit, category: Gesture, enable_level: 0, persist_level: 0, default_ttl: 1, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
default	05:56:56.907470 +0300	yalu102	subsystem: com.apple.UIKit, category: GestureEnvironment, enable_level: 0, persist_level: 0, default_ttl: 1, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
default	05:56:56.910611 +0300	yalu102	subsystem: com.apple.UIKit, category: GestureExclusion, enable_level: 0, persist_level: 0, default_ttl: 1, info_ttl: 0, debug_ttl: 0, generate_symptoms: 0, enable_oversize: 1, privacy_setting: 2, enable_private_data: 0
default	05:56:57.621520 +0300	yalu102	found corruption 38103
default	05:57:06.432367 +0300	yalu102	found kernel text at fffffff024e04000
default	05:57:06.435780 +0300	yalu102	got tfp0 -> d0b
default	05:57:06.437838 +0300	yalu102	found procs at fffffff002719060
default	05:57:06.446354 +0300	yalu102	seg: __TEXT
default	05:57:06.447173 +0300	yalu102	seg: __DATA_CONST
default	05:57:06.447915 +0300	yalu102	seg: __TEXT_EXEC
default	05:57:06.448720 +0300	yalu102	seg: __KLD
default	05:57:06.449418 +0300	yalu102	seg: __LAST
default	05:57:06.450173 +0300	yalu102	seg: __DATA
default	05:57:06.450866 +0300	yalu102	seg: __PRELINK_TEXT
default	05:57:06.451745 +0300	yalu102	seg: __PLK_TEXT_EXEC
default	05:57:06.453378 +0300	yalu102	seg: __PRELINK_DATA
default	05:57:06.453872 +0300	yalu102	seg: __PLK_DATA_CONST
default	05:57:06.454265 +0300	yalu102	seg: __PLK_LINKEDIT
default	05:57:06.454634 +0300	yalu102	seg: __PRELINK_INFO
default	05:57:06.455047 +0300	yalu102	seg: __LINKEDIT
default	05:57:06.455469 +0300	yalu102	fffffff023f94000 - fffffff02569c000
default	05:57:06.522957 +0300	yalu102	ffffffff03e9c000
default	05:57:06.574652 +0300	yalu102	fffffff024e655a0
default	05:57:06.618199 +0300	yalu102	pmap: fffffff025314850
default	05:57:06.618980 +0300	yalu102	level 1c0
default	05:57:06.619444 +0300	yalu102	level 1c0
default	05:57:06.621604 +0300	yalu102	level 1c0
default	05:57:06.628459 +0300	yalu102	got phys at 81bd24000 for virt fffffff0190f7000
default	05:57:06.628729 +0300	yalu102	found cpu 0
default	05:57:06.629036 +0300	yalu102	found physz: fffffff024e87000
default	05:57:06.629324 +0300	yalu102	found cpu 1
default	05:57:06.629594 +0300	yalu102	found physz: fffffff024e87000
default	05:57:06.629872 +0300	yalu102	fffffff024f8733c - fffffff024f8719c
default	05:57:06.630137 +0300	yalu102	ttbr0: 8020bd000 fffffff024e65590
default	05:57:06.630759 +0300	yalu102	level 1c0
default	05:57:06.631381 +0300	yalu102	level 1c0
default	05:57:06.631843 +0300	yalu102	level 1c0
default	05:57:06.632300 +0300	yalu102	81b7a7000 - fffffff00082d000
default	05:57:06.636081 +0300	yalu102	got a cpacr
default	05:57:06.636544 +0300	yalu102	level 1c0
default	05:57:06.637059 +0300	yalu102	level 1c0
default	05:57:06.637514 +0300	yalu102	level 1c0
default	05:57:06.637968 +0300	yalu102	level 1c0
default	05:57:06.638428 +0300	yalu102	level fffffff03f1a7000 - 82d92e000
default	05:57:06.638944 +0300	yalu102	level 1c0
default	05:57:06.639420 +0300	yalu102	level 1c0
default	05:57:06.639873 +0300	yalu102	level 1c0
default	05:57:06.641229 +0300	yalu102	level 1c0
default	05:57:06.642158 +0300	yalu102	level fffffff05132e938 - 832c8f000
default	05:57:06.642618 +0300	yalu102	level 1c0
default	05:57:06.643064 +0300	yalu102	level 1c0
default	05:57:06.643527 +0300	yalu102	level 1c0
default	05:57:06.643985 +0300	yalu102	level 1c0
default	05:57:06.644429 +0300	yalu102	level fffffff05668f420 - 81b710000
default	05:57:06.644889 +0300	yalu102	level 1c0
default	05:57:06.645337 +0300	yalu102	level 1c0
default	05:57:06.645781 +0300	yalu102	level 1c0
default	05:57:06.646236 +0300	yalu102	level 1c0
default	05:57:06.649723 +0300	yalu102	level 1c0
default	05:57:06.650405 +0300	yalu102	level 1c0
default	05:57:06.650839 +0300	yalu102	level 1c0
default	05:57:06.651284 +0300	yalu102	level fffffff03f1a7000 - 822b11000
default	05:57:06.651740 +0300	yalu102	level 1c0
default	05:57:06.652193 +0300	yalu102	level 1c0
default	05:57:06.652657 +0300	yalu102	level 1c0
default	05:57:06.653114 +0300	yalu102	level 1c0
default	05:57:06.653535 +0300	yalu102	level fffffff046511938 - 81ab12000
default	05:57:06.654058 +0300	yalu102	level 1c0
default	05:57:06.654521 +0300	yalu102	level 1c0
default	05:57:06.654994 +0300	yalu102	level 1c0
default	05:57:06.655450 +0300	yalu102	level 1c0
default	05:57:06.655904 +0300	yalu102	level fffffff03e512020 - 817b93000
default	05:57:06.656366 +0300	yalu102	level 1c0
default	05:57:06.656818 +0300	yalu102	level 1c0
default	05:57:06.657289 +0300	yalu102	level 1c0
default	05:57:06.657736 +0300	yalu102	level 1c0
default	05:57:06.658151 +0300	yalu102	level 1c0
default	05:57:06.658486 +0300	yalu102	level 1c0
default	05:57:06.658884 +0300	yalu102	level 1c0
default	05:57:06.659224 +0300	yalu102	level 1c0
default	05:57:06.659539 +0300	yalu102	level 1c0
default	05:57:06.775978 +0300	yalu102	level 1c0
default	05:57:06.776743 +0300	yalu102	level 1c0
default	05:57:06.779498 +0300	yalu102	level 1c0
default	05:57:06.780235 +0300	yalu102	level 1c0
default	05:57:06.780752 +0300	yalu102	level fffffff03f1a7000 - 817aaf000
default	05:57:06.781249 +0300	yalu102	level 1c0
default	05:57:06.781864 +0300	yalu102	level 1c0
default	05:57:06.782428 +0300	yalu102	level 1c0
default	05:57:06.782940 +0300	yalu102	level 1c0
default	05:57:06.783558 +0300	yalu102	level fffffff03b4af930 - 817630000
default	05:57:06.784082 +0300	yalu102	level 1c0
default	05:57:06.784580 +0300	yalu102	level 1c0
default	05:57:06.785064 +0300	yalu102	level 1c0
default	05:57:06.785590 +0300	yalu102	level 1c0
default	05:57:06.786078 +0300	yalu102	level fffffff03b0309f8 - 835631000
default	05:57:06.786569 +0300	yalu102	level 1c0
default	05:57:06.787139 +0300	yalu102	level 1c0
default	05:57:06.787640 +0300	yalu102	level 1c0
default	05:57:06.835176 +0300	yalu102	level 1c0
default	05:57:06.835875 +0300	yalu102	level 1c0
default	05:57:06.836394 +0300	yalu102	level 1c0
default	05:57:06.837319 +0300	yalu102	level 1c0
default	05:57:06.837834 +0300	yalu102	level fffffff03f1a7000 - 818732000
default	05:57:06.838290 +0300	yalu102	level 1c0
default	05:57:06.838753 +0300	yalu102	level 1c0
default	05:57:06.839297 +0300	yalu102	level 1c0
default	05:57:06.839762 +0300	yalu102	level 1c0
default	05:57:06.840230 +0300	yalu102	level fffffff03c132938 - 817933000
default	05:57:06.840686 +0300	yalu102	level 1c0
default	05:57:06.841163 +0300	yalu102	level 1c0
default	05:57:06.841611 +0300	yalu102	level 1c0
default	05:57:06.842049 +0300	yalu102	level 1c0
default	05:57:06.842485 +0300	yalu102	level fffffff03b3330f8 - 8303b4000
default	05:57:06.842819 +0300	yalu102	level 1c0
default	05:57:06.843085 +0300	yalu102	level 1c0
default	05:57:06.843331 +0300	yalu102	level 1c0
default	05:57:06.843573 +0300	yalu102	level 1c0
default	05:57:06.843821 +0300	yalu102	level 1c0
default	05:57:06.844068 +0300	yalu102	level 1c0
default	05:57:06.849200 +0300	yalu102	level 1c0
default	05:57:06.849759 +0300	yalu102	level 1c0
default	05:57:06.850227 +0300	yalu102	level 1c0
default	05:57:06.850610 +0300	yalu102	level 1c0
default	05:57:06.850997 +0300	yalu102	level fffffff03f1a7000 - 81a494000
default	05:57:06.851367 +0300	yalu102	level 1c0
default	05:57:06.851735 +0300	yalu102	level 1c0
default	05:57:06.852103 +0300	yalu102	level 1c0
default	05:57:06.852466 +0300	yalu102	level 1c0
default	05:57:06.852838 +0300	yalu102	level fffffff03de94930 - 817195000
default	05:57:06.853206 +0300	yalu102	level 1c0
default	05:57:06.853542 +0300	yalu102	level 1c0
default	05:57:06.853854 +0300	yalu102	level 1c0
default	05:57:06.854101 +0300	yalu102	level 1c0
default	05:57:06.854346 +0300	yalu102	level fffffff03ab95418 - 817ebe000
default	05:57:06.854594 +0300	yalu102	level 1c0
default	05:57:06.854839 +0300	yalu102	level 1c0
default	05:57:06.855083 +0300	yalu102	level 1c0
default	05:57:06.865436 +0300	yalu102	fref at fffffff024f84fd0
default	05:57:06.882867 +0300	yalu102	amfistr at fffffff024c84510
default	05:57:06.883685 +0300	yalu102	level 1c0
default	05:57:06.884232 +0300	yalu102	level 1c0
default	05:57:06.884732 +0300	yalu102	level 1c0
default	05:57:06.885263 +0300	yalu102	level 1c0
default	05:57:06.885777 +0300	yalu102	level fffffff03f1a7000 - 831844000
default	05:57:06.886287 +0300	yalu102	level 1c0
default	05:57:06.886801 +0300	yalu102	level 1c0
default	05:57:06.887428 +0300	yalu102	level 1c0
default	05:57:06.888016 +0300	yalu102	level 1c0
default	05:57:06.888571 +0300	yalu102	level fffffff055244930 - 816bc5000
default	05:57:06.889244 +0300	yalu102	level 1c0
default	05:57:06.889815 +0300	yalu102	level 1c0
default	05:57:06.890231 +0300	yalu102	level 1c0
default	05:57:06.890588 +0300	yalu102	level 1c0
default	05:57:06.890968 +0300	yalu102	level fffffff03a5c5420 - 819fc6000
default	05:57:06.891337 +0300	yalu102	level 1c0
default	05:57:06.891703 +0300	yalu102	level 1c0
default	05:57:06.892072 +0300	yalu102	level 1c0
default	05:57:06.919081 +0300	yalu102	level 1c0
default	05:57:06.919781 +0300	yalu102	level 1c0
default	05:57:06.920332 +0300	yalu102	level 1c0
default	05:57:06.920819 +0300	yalu102	level 1c0
default	05:57:06.921323 +0300	yalu102	level fffffff03f1a7000 - 83691a000
default	05:57:06.921793 +0300	yalu102	level 1c0
default	05:57:06.922240 +0300	yalu102	level 1c0
default	05:57:06.923177 +0300	yalu102	level 1c0
default	05:57:06.924092 +0300	yalu102	level 1c0
default	05:57:06.924545 +0300	yalu102	level fffffff05a31a930 - 82e99b000
default	05:57:06.925070 +0300	yalu102	level 1c0
default	05:57:06.925557 +0300	yalu102	level 1c0
default	05:57:06.929004 +0300	yalu102	level 1c0
default	05:57:06.929594 +0300	yalu102	level 1c0
default	05:57:06.930165 +0300	yalu102	level fffffff05239bea0 - 82c89c000
default	05:57:06.930832 +0300	yalu102	level 1c0
default	05:57:06.931465 +0300	yalu102	level 1c0
default	05:57:06.932379 +0300	yalu102	level 1c0
default	05:57:06.932658 +0300	yalu102	level 1c0
default	05:57:06.933042 +0300	yalu102	level 1c0
default	05:57:06.933411 +0300	yalu102	level 1c0
default	05:57:06.933798 +0300	yalu102	level 1c0
default	05:57:06.934145 +0300	yalu102	level 1c0
default	05:57:06.934453 +0300	yalu102	level 1c0
default	05:57:06.934907 +0300	yalu102	level 1c0
default	05:57:06.935623 +0300	yalu102	level 1c0
default	05:57:06.935911 +0300	yalu102	level 1c0
default	05:57:06.936078 +0300	yalu102	level 1c0
default	05:57:06.936285 +0300	yalu102	level 1c0
default	05:57:06.936590 +0300	yalu102	level 1c0
default	05:57:06.937079 +0300	yalu102	level 1c0
default	05:57:06.937454 +0300	yalu102	level 1c0
default	05:57:06.937859 +0300	yalu102	level 1c0
default	05:57:06.938251 +0300	yalu102	level 1c0
default	05:57:06.938645 +0300	yalu102	level 1c0
default	05:57:06.939088 +0300	yalu102	level 1c0
default	05:57:06.939388 +0300	yalu102	level 1c0
default	05:57:06.939654 +0300	yalu102	level 1c0
default	05:57:06.940004 +0300	yalu102	level 1c0
default	05:57:06.940405 +0300	yalu102	level 1c0
default	05:57:06.940866 +0300	yalu102	level 1c0
default	05:57:06.941238 +0300	yalu102	level 1c0
default	05:57:06.941656 +0300	yalu102	level 1c0
default	05:57:06.941991 +0300	yalu102	level 1c0
default	05:57:06.942459 +0300	yalu102	level 1c0
default	05:57:06.942679 +0300	yalu102	level 1c0
default	05:57:06.943029 +0300	yalu102	level 1c0
default	05:57:06.943389 +0300	yalu102	level 1c0
default	05:57:06.943898 +0300	yalu102	level 1c0
default	05:57:06.944168 +0300	yalu102	level 1c0
default	05:57:06.944390 +0300	yalu102	level 1c0
default	05:57:06.944856 +0300	yalu102	level 1c0
default	05:57:06.945462 +0300	yalu102	level 1c0
default	05:57:06.945688 +0300	yalu102	level 1c0
default	05:57:06.946061 +0300	yalu102	level 1c0
default	05:57:06.946261 +0300	yalu102	level 1c0
default	05:57:06.946699 +0300	yalu102	level 1c0
default	05:57:06.946926 +0300	yalu102	level 1c0
default	05:57:06.947130 +0300	yalu102	level 1c0
default	05:57:06.947262 +0300	yalu102	level 1c0
default	05:57:06.947342 +0300	yalu102	level 1c0
default	05:57:06.947484 +0300	yalu102	level 1c0
default	05:57:06.947643 +0300	yalu102	level 1c0
default	05:57:06.947778 +0300	yalu102	level 1c0
default	05:57:06.947903 +0300	yalu102	level 1c0
default	05:57:06.948725 +0300	yalu102	level 1c0
default	05:57:06.948862 +0300	yalu102	level 1c0
default	05:57:06.949105 +0300	yalu102	level 1c0
default	05:57:06.949324 +0300	yalu102	level 1c0
default	05:57:06.949459 +0300	yalu102	level 1c0
default	05:57:06.949618 +0300	yalu102	level 1c0
default	05:57:06.949792 +0300	yalu102	level 1c0
default	05:57:06.950042 +0300	yalu102	level 1c0
default	05:57:06.950257 +0300	yalu102	level 1c0
default	05:57:06.950382 +0300	yalu102	level 1c0
default	05:57:06.950558 +0300	yalu102	level 1c0
default	05:57:06.950710 +0300	yalu102	level 1c0
default	05:57:06.950888 +0300	yalu102	level 1c0
default	05:57:06.951137 +0300	yalu102	level 1c0
default	05:57:06.951293 +0300	yalu102	level 1c0
default	05:57:06.951445 +0300	yalu102	level 1c0
default	05:57:06.951601 +0300	yalu102	level 1c0
default	05:57:06.951855 +0300	yalu102	level 1c0
default	05:57:06.951987 +0300	yalu102	level 1c0
default	05:57:06.952153 +0300	yalu102	level 1c0
default	05:57:06.952312 +0300	yalu102	level 1c0
default	05:57:06.952485 +0300	yalu102	level 1c0
default	05:57:06.952750 +0300	yalu102	level 1c0
default	05:57:06.952884 +0300	yalu102	level 1c0
default	05:57:06.953074 +0300	yalu102	level 1c0
default	05:57:06.953325 +0300	yalu102	level 1c0
default	05:57:06.953464 +0300	yalu102	level 1c0
default	05:57:06.953599 +0300	yalu102	level 1c0
default	05:57:06.953839 +0300	yalu102	level 1c0
default	05:57:06.954089 +0300	yalu102	level 1c0
default	05:57:06.954229 +0300	yalu102	level 1c0
default	05:57:06.954552 +0300	yalu102	level 1c0
default	05:57:06.955200 +0300	yalu102	level 1c0
default	05:57:06.955501 +0300	yalu102	level 1c0
default	05:57:06.955643 +0300	yalu102	level 1c0
default	05:57:06.955851 +0300	yalu102	level 1c0
default	05:57:06.955983 +0300	yalu102	level 1c0
default	05:57:06.956131 +0300	yalu102	level 1c0
default	05:57:06.956361 +0300	yalu102	level 1c0
default	05:57:06.956585 +0300	yalu102	level 1c0
default	05:57:06.956713 +0300	yalu102	level 1c0
default	05:57:06.956861 +0300	yalu102	level 1c0
default	05:57:06.957041 +0300	yalu102	level 1c0
default	05:57:06.957294 +0300	yalu102	d10103bf a9447bfd
default	05:57:06.957456 +0300	yalu102	level 1c0
default	05:57:06.957625 +0300	yalu102	level 1c0
default	05:57:06.957889 +0300	yalu102	level 1c0
default	05:57:06.958048 +0300	yalu102	level 1c0
default	05:57:06.958319 +0300	yalu102	level fffffff03f1a7000 - 81cc47000
default	05:57:06.958591 +0300	yalu102	level 1c0
default	05:57:06.958726 +0300	yalu102	level 1c0
default	05:57:06.958860 +0300	yalu102	level 1c0
default	05:57:06.959000 +0300	yalu102	level 1c0
default	05:57:06.959151 +0300	yalu102	level fffffff040647908 - 81f5c8000
default	05:57:06.959297 +0300	yalu102	level 1c0
default	05:57:06.959451 +0300	yalu102	level 1c0
default	05:57:06.959584 +0300	yalu102	level 1c0
default	05:57:06.959710 +0300	yalu102	level 1c0
default	05:57:06.959870 +0300	yalu102	level fffffff042fc87c0 - 81a8c9000
default	05:57:06.960095 +0300	yalu102	level 1c0
default	05:57:06.960267 +0300	yalu102	level 1c0
default	05:57:06.960427 +0300	yalu102	level 1c0
default	05:57:06.960571 +0300	yalu102	fffffff0242f865c fffffff03e2c965c
default	05:57:06.960713 +0300	yalu102	d10103bf d10103bf
default	05:57:07.954924 +0300	yalu102	enabled patches
default	05:57:07.958919 +0300	yalu102	remounting: -1
default	05:57:07.964518 +0300	yalu102	open on /bin/tar: Read-only file system
default	05:57:07.965925 +0300	yalu102	pid = 140
default	05:57:07.967147 +0300	yalu102	open on /bin/launchctl: Read-only file system
default	05:57:07.985136 +0300	yalu102	open on /usr/libexec/reload: Read-only file system
default	05:57:07.986205 +0300	yalu102	open on /Library/LaunchDaemons/0.reload.plist: No such file or directory
default	05:57:09.987650 +0300	yalu102	done

**Comment by kpwn** [comment]
wrong rootfs_vnode

**Comment by thebeastgamer25** [comment]
@kpwn no

**Comment by AGagarin** [comment]
iPad Mini 2 LTE 
[yalu102_alfa2.txt](https://github.com/kpwn/yalu102/files/737263/yalu102_alfa2.txt)
