### ISSUE TITLE
Cydia and APT issues

### ISSUE THREAD

**Issue by bobbysn0w** [kpwn/yalu102#177]
Long story short, APT doesn't work (using SSH from Terminal) and Cydia crashes despite any amount of reboots. I'll just sit back and let Luca do his godly work and fix some stuff before I try to update my tweaks...

**Comment by kpwn** [comment]
I think this is a long-known cydia bug.

Try with:
rm /private/var/mobile/Library/Cydia/metadata.cb0

**Comment by itsCozmikk** [comment]
What were you testing on @bobbysn0w

**Comment by akelly5** [comment]
when will the ipa come out? People with windows cant jailbreak

**Comment by itsCozmikk** [comment]
@akelly5 DONT SPAM. STOP ASKING FOR ETA.

**Comment by akelly5** [comment]
do you know where I can ask these questions??

**Comment by bobbysn0w** [comment]
@kpwn I suggest https://help.github.com/articles/blocking-a-user-from-your-personal-account/

**Comment by itsCozmikk** [comment]
About to test on my Verizon 5S. I can't remember what the device id is.

**Comment by bobbysn0w** [comment]
Thanks it works.

**Comment by Acelogic** [comment]
@akelly5 Ask someone to compile it for you and to send the IPA, but not on here though. This is for productive discussions relating to programming and etc only; not tech support.

**Comment by bobbysn0w** [comment]
@acelogic Lol Luca ***just*** tweeted to not ask for the IPA. Besides, if you're too lazy or dumb to get a hackintosh working or a mac then you're going to be to lazy and dumb to fix your jailbreak when it breaks.

**Comment by Acelogic** [comment]
@bobbysn0w  Agreed !
