### ISSUE TITLE
iPad Mini 2 LTE  SUCCSESS !!!

### ISSUE THREAD

**Issue by AGagarin** [kpwn/yalu102#178]
Thank you !!!
Works with latest commit from Mila

[yalu102_149_Mila.txt](https://github.com/kpwn/yalu102/files/737266/yalu102_149_Mila.txt)

**Comment by kpwn** [comment]
thanks, waiting on PR from @Mila432 if this is not the commit I already merged

**Comment by AGagarin** [comment]
It works with PR 149.

**Comment by 128keaton** [comment]
works here too, pull request #149, iPad mini 2 wifi 32gb

**Comment by Vitauser** [comment]
Can someone give me the new ipa so that i. Snt test if my ipad mini 2 also works ? That would be very nice

**Comment by beren12** [comment]
Sure. Download Xcode and hit build, and Xcode will give you the new ipa.

**Comment by Vitauser** [comment]
is this a joke from you ? How can i do this ?

**Comment by Vitauser** [comment]
ive tried it with xcode but how can i do this ? Everytime i click build it will give me an error with iokit or something like that. can you just give me maybe the ipa ? That would be easier for me. Thank You

**Comment by timonline** [comment]
@Vitauser i am happy to help you figure out that iokit but if you are a beginner and unfamiliar with building the code, I would suggest you avoid doing so less you ruin your device

**Comment by Vitauser** [comment]
@timonline yes iam very new and a beginner. So youre right can you maybe make me the new ipa so that i can test it ? On my iphone it does work flawlessly. Thank you very much

**Comment by 128keaton** [comment]
@Vitauser nope, we cannot do that, just wait patiently or read how to do it. Have a nice day.

**Comment by timonline** [comment]
@Vitauser beta3 is out now :)
