### ISSUE TITLE
after knowing KPP is fully bypass just a simple request.

### ISSUE THREAD

**Issue by iOS4all** [kpwn/yalu102#180]
@kpwn hi there. I just want tell you I talked to the creator of retroarch while ago about dynarec core of pcsx and he said we need patch the kernel in order to could use JIT again. Because I have a jailbroken iPhone 7 on iOS 10.1.1 and pcsx just crashes. Like TaiG team always release their jailbreak with kernel patched to could use JIT functionality.

So if you don't mind at least Patch the kernel before releasing the public version of jailbreak.
Or if you want make two versions of this amazing jailbreak one of them including the patch kernel.
Because as you see the most amazing feature of this jailbreak you could successfully bypass KPP. So because of that we could use JIT again after long time missed. we really appreciate all your hard work.
Thank you so much.

**Comment by iOS4all** [comment]
At least read my thread if you don't mind.
Anyway I'm sorry to bother you.

**Comment by kpwn** [comment]
https://www.reddit.com/r/jailbreak/comments/5qy2x0/beta_jitsupport_kernelless_jit_support_for_ios_9/

**Comment by iOS4all** [comment]
@kpwn thank you so much for adding JIT support. I'm really appreciate a lot. You can't imagine how I was happy. This is will help emulation project like ppsspp retroarch dolphin...etc to enhancing their apps because of this amazing feature that you give us.
Thank you again for all your hard work.

**Comment by iOS4all** [comment]
@kpwn just a simple question. After get JIT support functionality. Do you give us RWX as well please? In order to run other project. Just if you have a free time.
Thanks.

**Comment by kpwn** [comment]
JITSupport is a library that gives you the ability to allocate RWX pages on demand.

**Comment by iOS4all** [comment]
Got your point thank for replying and for everything you did to this community. Really appreciate a lot.

**Comment by iOS4all** [comment]
Sorry to bother you.
This my final question to leave this thread.
Did we need to download that deb file of JIT support that you gave it from reddit or not?

**Comment by iOS4all** [comment]
@kpwn sorry to bother you. I just want to ask you if you there is any update for JIT that you gave us as deb file?
Thanks.
