### ISSUE TITLE
Respringing doesn't run uicache

### ISSUE THREAD

**Issue by CrypticGit** [kpwn/yalu102#183]
I've noticed that sometimes when installing tweaks I reboot and it shows up on the homescreen. But if I don't run uicache or reboot it doesn't pop up on my springboard

**Comment by beanjo55** [comment]
pretty sure this is a #162

**Comment by CrypticGit** [comment]
@beanjo55 this issue doesn't occur in b3 or pangu

**Comment by beanjo55** [comment]
@CrypticGit if you look at #162 , this is not an issue directly relating to the code of this JB. the goal now it seems is to get the JB stable, and then please the people who just want tweaks and shit
