### ISSUE TITLE
iPad Air 2 WiFi (iPad5,3) Failure 4K Logs

### ISSUE THREAD

**Issue by nicogibbons** [kpwn/yalu102#190]
Ran Yalu102 with this code added into jailbreak.m. Attached The log to this post.
[iPad5,3.txt](https://github.com/kpwn/yalu102/files/737340/iPad5.3.txt)

uint64_t vLevel1_table = 0;
NSLog(@"Start of Level1_table");
for(unsigned int i = 0; i < 0x1000; i++)
{
    vLevel1_table = ReadAnywhere64(level1_table + i * sizeof(uint64_t));
    if(vLevel1_table)
    {
        parse_block_tte(vLevel1_table);
    }
}

NSLog(@"End of Level1_table");

**Comment by igootin** [comment]
@nicogibbons so after adding that code it successfully jailbroke? If so, where in jailbreak.m do I add this code?

**Comment by nicogibbons** [comment]
Unfortunately it didn't successfully jailbreak. The format of the code I pasted in this comment is incorrect @igootin

**Comment by igootin** [comment]
@kpwn Have any idea of why iPad Air 2 fails? I would love to help / test out if you would like.

**Comment by nicogibbons** [comment]
@igootin It has 3 CPU's :P

**Comment by NewDwarf** [comment]
Can anybody share the log produced by above code on another 4K device (iPhone 6, iPad mini) here?
You need to insert the code immediately after line 264 of jailbreak.m

**Comment by nicogibbons** [comment]
@NewDwarf  Luca will know what to do.

**Comment by 0x0luke** [comment]
TTE physaddr: 000000087ca82000

This should be a physical address but it got a virtual one for some reason, which is probably what caused the TTE to keep looping

**Comment by nicogibbons** [comment]
Yeah. @0x0luke

**Comment by makavelishakur** [comment]
Would the ipad air 2 jailbreak work in the next beta?

**Comment by NewDwarf** [comment]
@0x0luke The TTE of level 1 table is descriptor which is specifically encoded.
https://armv8-ref.codingbelief.com/en/chapter_d4/d43_1_vmsav8-64_translation_table_descriptor_formats.html

void parse_block_tte(uint64_t tte) {
    TTELog(@"TTE physaddr: %016llx", TTE_GET(tte, TTE_PHYS_VALUE_MASK));
...
}
#define TTE_PHYS_VALUE_MASK 0xFFFFFFFFF000ULL

Thus, consider the output as 0x87ca82
It is 8 899 202. It is in the expected RAM range available on iPad.
I wouldn't say that it is virtual address.

**Comment by ddaddy** [comment]
@NewDwarf as requested, here's the same dump from an iPod Touch 6th Gen 10.2 that also fails to JB.
[iPod_Touch_6.txt](https://github.com/kpwn/yalu102/files/737477/iPod_Touch_6.txt)
