### ISSUE TITLE
How to add IOkit headers/IOkit not found.

### ISSUE THREAD

**Issue by cemre2002** [kpwn/yalu102#191]
Please help me, I need to add them manually, but I don't know how....

**Comment by meyer9** [comment]
#187

**Comment by EGYbkgo9449** [comment]
https://www.reddit.com/r/jailbreak/comments/5q8os9/tutorial_fix_iokit_error_in_yalu_102/

**Comment by meyer9** [comment]
It's included in the iOS SDK. Why would you download it separately?

**Comment by cemre2002** [comment]
I don't know, but now it works

**Comment by cemre2002** [comment]
I now get this error:
ld: -ios_version_min argument is missing period as second character
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Should I make a different issue for this?

**Comment by meyer9** [comment]
no. this does not need more issues

**Comment by cemre2002** [comment]
Does it mean i need to update xcode?

**Comment by meyer9** [comment]
did you try the commands in my post?

**Comment by cemre2002** [comment]
yes, did not work

**Comment by cemre2002** [comment]
but the IOkit thing is fixed (I think)

**Comment by cemre2002** [comment]
I got this:
cp: /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Versions/A/Headers: No such file or directory

**Comment by EGYbkgo9449** [comment]
@meyer9 
Yeah but that is the only thing that fixed it

**Comment by cemre2002** [comment]
what to do about the (clang: error: linker command failed with exit code 1 (use -v to see invocation)
error

**Comment by EGYbkgo9449** [comment]
@cemre2002 
Make sure to follow the tutorial then restart Xcode

**Comment by meyer9** [comment]
Update your Xcode. Looks like it was a bug in previous versions.

**Comment by cemre2002** [comment]
Ok.

**Comment by cemre2002** [comment]
ah. I know the problem... My (very very old) xcode version does not support iOS 10 builds (Stupid lazy me)

**Comment by meyer9** [comment]
Alright cool. Please close the issue.

**Comment by cemre2002** [comment]
Will do when it is fixed, is that OK, if it is not I will close it now.

**Comment by cemre2002** [comment]
Btw thanks for your help.

**Comment by chaustark** [comment]
lol if u cant manage to compile it so dont jailbreak pls. Dont just create a issue before google it

**Comment by cemre2002** [comment]
Reopening, Got the IOKIT issue again....

**Comment by cemre2002** [comment]
Desktop/yalu/yalu102-master/yalu102/jailbreak.m:14:9: 'IOKit/IOKitLib.h' file not found

**Comment by chaustark** [comment]
Fucking download it on the google and put it in the file. Dont fucking jailbreak pls lol.

**Comment by samtulach** [comment]
Try download this: https://opensource.apple.com/source/IOKitUser/IOKitUser-388/IOKitLib.h
