### ISSUE TITLE
Fix iPhone 6 Crash issue 

### ISSUE THREAD

**Issue by karboN90** [kpwn/yalu102#192]
Would appreciate if you fix it with a much stable IPA

**Comment by cemre2002** [comment]
It is still in beta, you can expect it to be unstable.

**Comment by cemre2002** [comment]
Please close the issue, this is for !code! issues only. not for support

**Comment by meyer9** [comment]
He is working on it. Nothing we can do. He doesn't seem to want the community to work on this bug specifically. Please close this issue.

If you are referring to the lack of iPhone 6 support in the latest ipa, you have to compile it in Xcode to get support for that.

**Comment by karboN90** [comment]
Yes, I understand. 
Just need a stable IPA just like the one for iPhone 6s which doesn't crash. 
Closing this issue. 
Thank you.

**Comment by karboN90** [comment]
Yes 
I have compiled it myself and got it working. 
Installed tweaks. 
Everything is fine. 
But it automatically crashes, irrespective of which app you are using and reboots. 
Hope that gets fixed
