### ISSUE TITLE
iPhone 6s issue

### ISSUE THREAD

**Issue by konner1001** [kpwn/yalu102#193]
Yalu102 sometimes failes to jailbreak. Boots into safe mode every now and then when jailbroken. And then Automatically resprings after device has been unlocked from there. When back to Normal  Requires a device reboot and then a re jailbreak for tweaks to work again but other than that keep up the good work

**Comment by Skiddi3** [comment]
He knows.

Please close the issue.

**Comment by vhyme** [comment]
Same problem here.

**Comment by chaustark** [comment]
Yea my prob r the same. After safe mode it goes to nosubtrate mode make me have to respring again to enable subtrate

**Comment by kpwn** [comment]
substrate bug
