### ISSUE TITLE
怎么导入IOKit?

### ISSUE THREAD

**Issue by cj950825** [kpwn/yalu102#195]
请问如何导入IOKit?

**Comment by liudayu** [comment]
跑这里还拿中文问问题，谁能看得懂？

自己不查一下再来问，也是秀智商。
#187

**Comment by semvoigt** [comment]
https://wizardos.stackstorage.com/index.php/s/70DaU1wueOaCX6F
Use the headers I used in that project.

donate: https://paypal.me/20162017

**Comment by liudayu** [comment]
Donate? Are you kidding me?

**Comment by semvoigt** [comment]
It's a bot

donate: https://paypal.me/20162017

**Comment by kinosang** [comment]
@semvoigt It is **not** a good idea to distribute IOKit headers. And don't ask others to download files from **unofficial** sources, it's not trusted.

And I think u'd better stop using your _bot_ on repos u didn't contribute to, so rude.

**Comment by cj950825** [comment]
@liudayu 弄了几次不成功么，才来问问，难道有错？仗着你懂？你就牛逼？

**Comment by liudayu** [comment]
@cj950825 那你起码也拿英文问。要不是我在看代码，谁能看懂你说的东西？

**Comment by cj950825** [comment]
谢谢大家，因装了三个xcode，导致屡次失败

**Comment by cj950825** [comment]
@liudayu 那也有英语不好的看了这个问题，游刃而解。

**Comment by liudayu** [comment]
@cj950825 你说的也对。我个人认为不怎么会玩的去官网下载ipa是最好的方法。（没有冒犯的意思）
