### ISSUE TITLE
iPad Mini 3

### ISSUE THREAD

**Issue by xNako** [kpwn/yalu102#196]
'already jailbroken' but cydia don't install

**Comment by MattCowley** [comment]
Have you tried rebooting then re-running the yalu app?

**Comment by xNako** [comment]
Yes, and same. @MattCowley

**Comment by MattCowley** [comment]
I presume you calculated the offsets yourself?

**Comment by xNako** [comment]
No.. @MattCowley

**Comment by MattCowley** [comment]
No. Nor do I see them in the project (I may be wrong). It's not on the supported device list so I'd just wait till it is supported.

**Comment by xNako** [comment]
Yes,  the offsets maybe wrong. I will wait for any change.. thanks. @MattCowley

**Comment by MattCowley** [comment]
Can you mark this as closed please :)

**Comment by xNako** [comment]
Wait if someone has the solution @MattCowley

**Comment by Mila432** [comment]
https://github.com/kpwn/yalu102/issues/64
