### ISSUE TITLE
iPhone 6 crashlog

### ISSUE THREAD

**Issue by iM4CH3T3** [kpwn/yalu102#197]
A crashlog from iPhone 6 10.2 produced while suddenly rebooted as i launched safari...

http://pastebin.com/kv1Uj6ei

**Comment by karboN90** [comment]
Fix iPhone 6 crash please 
Now that you have the crash log

**Comment by lifebourne** [comment]
`Jan 29 10:52:15 Kpwn SpringBoard(FrontBoard)[1460] <Info>: no object found
Jan 29 10:52:15 Kpwn SpringBoard(FrontBoard)[1460] <Info>: fetching object for key=SBSPushStoreRemoteNotificationCategories bundleID=<private> checkPrefetch=NO (synchronously)
Jan 29 10:52:15 Kpwn SpringBoard(FrontBoard)[1460] <Info>: checking for prefetched object for key=SBSPushStoreRemoteNotificationCategories bundleID=<private>`

What is this and why is this looping in my log. Phone works fine. But i don't like that xD

**Comment by iM4CH3T3** [comment]
http://pastebin.com/tCQBfarG

**Comment by iM4CH3T3** [comment]
Another iPhone 6 crash log 


Am I the only one who sending crashlogs?

http://pastebin.com/XqAw2d9z

**Comment by kpwn** [comment]
i already have a lot of logs

**Comment by aeozy** [comment]
@kbwn i found when iturn on airplane mode the jailbreak worked perfect at iphone 6 plus  without any crash we i turned off and carrier appear the iphone crash and restart
