### ISSUE TITLE
Sources of closed part of the JB

### ISSUE THREAD

**Issue by NewDwarf** [kpwn/yalu102#199]
@kpwn I appreciate your work and time but may I ask you to share sources for closed parts (patchfinder64.o and iokitmig64.o) of your projects. Of course, one can use IDA/hex-ray decompiler but I guess no one has capability to use it without the valid license for ethical reasons. 
It would be good for community especially for people who want to look underneath of your solution.

**Comment by stefanstefan2001** [comment]
I think iokitmig64.o is just a compiled version of a file of the open sourced IOKit.
patchfinder64 is written by him, but you can see it does in the header, and I think that those things aren't that hard to implement, however you can use IDA/hopper.
