### ISSUE TITLE
iphone 5s (iphone 9,1) not supported ,iphone 9,2 supported

### ISSUE THREAD

**Issue by cloverdoser** [kpwn/yalu102#200]
why

**Comment by nicogibbons** [comment]
I can't wait for all of these to be closed.

**Comment by hcl2k** [comment]
i have 5s 6.2 its not supported atm

**Comment by cloverdoser** [comment]
https://pbs.twimg.com/media/C3VM72FWQAAad7P.jpg
https://pbs.twimg.com/media/C3VM74oW8AAstR2.jpg
#tihmstar 
iphone 6,2

**Comment by hcl2k** [comment]
uhm
new commit? 
i cant compile the ipa , no way to run a fonctional virtual machine grr

**Comment by hcl2k** [comment]
yes 10.1.1

**Comment by kinosang** [comment]
#64

**Comment by cloverdoser** [comment]
https://www.dropbox.com/s/abf08lkkgz6sc3m/yalu102_alpha%20by%20sonyccyong.ipa?dl=0

**Comment by maetrik92** [comment]
Why do you share the fcking ipas like this?he said no and no means no!

**Comment by hcl2k** [comment]
ohh thanks !

**Comment by Delived** [comment]
Please

**Comment by Delived** [comment]
@hcl2k Erase that IPA, it has malware, it can bootloop your device

**Comment by apaukraine** [comment]
That's IPA well working on my iPhone 5s, Thanks.

**Comment by timonline** [comment]
@apaukraine what version of iOS are you running on the iP5s? 10.2?

**Comment by apaukraine** [comment]
Yes

**Comment by apaukraine** [comment]
I have saved blobs, can try on another versions

**Comment by timonline** [comment]
@apaukraine weird, the latest commit still doesn't work on my iPhone 5S

**Comment by apaukraine** [comment]
@timonlone, You have iPhone 9,1 or 9,2

**Comment by timonline** [comment]
isn't iPhone9,1 an iPhone 7? (see below). Then why say "That's IPA well working on my iPhone 5s"

**iPhone9,1	iPhone 7 (A1660/A1779/A1780)
iPhone9,2	iPhone 7 Plus (A1661/A1785/A1786)
iPhone9,3	iPhone 7 (A1778)
iPhone9,4	iPhone 7 Plus (A1784)**

**Comment by kpwn** [comment]
please use #186

**Comment by kpwn** [comment]
this issue is *CLOSED*

**Comment by apaukraine** [comment]
@timonlone I install IPA from dropbox
