### ISSUE TITLE
Can confirm the Jailbreak works with i5s and i6 

### ISSUE THREAD

**Issue by turnerrocks1** [kpwn/yalu102#202]
Before I hit yalu go button safari and messages and twitter mainly all third party apps. So I restart the phone into safe mode by using the vol down+ power+home button to get into safe mode even tho that's isn't safe mode it just disable everything installed by cydia so if I don't have anything installed other than zeppelin and substrate safe mode, and cydia substrate and regular packages required by cydia then its 

something in your code ?

**Comment by nullpixel1** [comment]
Can you close this please. #162, known issue.
