### ISSUE TITLE
Only for kpwn!

### ISSUE THREAD

**Issue by TopArwin** [kpwn/yalu102#203]
Disclaimer: DO NOT INSTALL THIS IPA ON i5S! IT IS ONLY FOR KPWN! KPWN,DON'T CLOSE THIS,JUST ANSWER!
Hello,5 minutes ago i found working JB for iPhone 5S,but i installed this on Restored iPhone,because i worried about my passwords.Can you check this IPA on steallers?
https://www.dropbox.com/s/abf08lkkgz6sc3m/yalu102_alpha%20by%20sonyccyong.ipa?dl=0

**Comment by TopArwin** [comment]
Omg...I just asked u to check IPA on malware,and u closed this "Issue"...

**Comment by AppleBetas** [comment]
It's not his job to check the shit you download for malware. He specifically said don't trust IPAs not compiled by yourself or him.

**Comment by AcedArmy** [comment]
Don't share malware. Its not his job to scan for you don't download from other sites compile it yourself and you won't have a problem
