### ISSUE TITLE
iPad Pro - Cydia gone

### ISSUE THREAD

**Issue by Haroon-Sharif** [kpwn/yalu102#209]
Since I jailbroke there is no Cydia on the spring board; jailbroken tweaks all work. I can access Cydia by using safari (Cydia://). Is it my iPad's problem or is it the jailbreak's problem. All other jailbroken apps are also not showing on the springboard (such as MTerminal and iCleaner and Filza). Is there anything I can do (par restore) or just wait till the Yalu update.

**Comment by kpwn** [comment]
Add a boolean YES called SBShowNonDefaultSystemApps in /var/mobile/Library/Preferences/com.apple.springboard.plist

**Comment by kpwn** [comment]
(yalu does this, but maybe it failed for you)

**Comment by Haroon-Sharif** [comment]
Wow; thanks it actually worked. Must have had some error in the jailbreak procedure. I was so close to restoring. Thanks!
