### ISSUE TITLE
Could not build module 'IOKit'

### ISSUE THREAD

**Issue by Sn0wFr1tz** [kpwn/yalu102#21]
Also says this when i try to compile

**Comment by Sn0wFr1tz** [comment]
Could not build module 'IOKit'

**Comment by nicogibbons** [comment]
That's not a problem with the source. If you can't get the headers you shouldn't be trying to use this

**Comment by onchehuh** [comment]
Download headers
Go in Project -> build settings
Add headers path to Header Search Paths

**Comment by Sn0wFr1tz** [comment]
na i can im importing them jus says this lol

**Comment by Sn0wFr1tz** [comment]
alright thank you mixed that up

**Comment by malhal** [comment]
Enter these two commands:

sudo cp -r /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Versions/A/Headers /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/System/Library/Frameworks/IOKit.framework

sudo cp /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/usr/include/libkern/OSTypes.h /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS.sdk/usr/include/libkern

Happy to PR to update the Readme with these commands, but lots of Readme PRs already waiting.
