### ISSUE TITLE
Yalu iPhone 6+ 64GB

### ISSUE THREAD

**Issue by FrodoToto** [kpwn/yalu102#211]
Hello, i just installed the Yalu latest version and compiled myself..

When i ran it first time it just rebooted and nothing more no cydia..

Now when i run it second time it just says "Already jailbroken", and i still got no cydia..

**Comment by nullpixel1** [comment]
Seems related to #209: try the steps there

**Comment by RajPatel0929** [comment]
same. happen to me...  but it is still under beta hope it will be fix soon

**Comment by kpwn** [comment]
you have ssh available, run uicache. the #209 thing is iPad specific.

**Comment by FrodoToto** [comment]
No i don't have SSH available..
