### ISSUE TITLE
Iphone 5s/ipad mini 3 Apps crashes after jailbreak

### ISSUE THREAD

**Issue by marcocorriero** [kpwn/yalu102#212]
Title says all.

**Comment by beanjo55** [comment]
any logs? you dont give us much to go on

**Comment by kpwn** [comment]
you are not using the git version but the leaked ipa.

**Comment by marcocorriero** [comment]
in the leaked ipa it works cydia, but what tweak i need to install @kpwn ?

**Comment by marcocorriero** [comment]
#162
