### ISSUE TITLE
Cydia error 

### ISSUE THREAD

**Issue by skimaskngun** [kpwn/yalu102#215]
Error occurred while processing com.cpdigitaldarkroom.catalyst (NewVersion1) 
You may want to run apt-get update to correct these problems. I run update command and get unable to lock list directory. Didn't even have darkroom repo installed. This happened on 6s and IPad Pro just today

**Comment by beanjo55** [comment]
#162

**Comment by skimaskngun** [comment]
Also no issues as far as installing tweaks and everything works ok but get that error every time Cydia is done refreshing repos

**Comment by beanjo55** [comment]
also #64

**Comment by bakirfatah** [comment]
My iphone 6S have error

Error occurred while processing com.cpdigitaldarkroom.catalyst (NewVersion1)
You may want to run apt-get update to correct

**Comment by beanjo55** [comment]
@bakirfatah #162 and #64
