### ISSUE TITLE
Cydia won't launch iPhone 6+

### ISSUE THREAD

**Issue by GlennMurphy** [kpwn/yalu102#216]
Hey, I tried with the latest master from yesterday and the latest master from an hour ago. The jailbreak succeeds fine every time, cydia just crashes on launch. I am able to ssh into the iPhone so I think there is just something wrong with cydia on 6+. I tried copying and running "tar" from the source code again (to reinstall cydia) but this did not help. 

Can you point me to the direction of the logs for this? I can attach them here, I'm just unsure where to look...

**Comment by skimaskngun** [comment]
Stop deleting issues that can possibly pertain to coding issues thank you

**Comment by beanjo55** [comment]
@skimaskngun if kpwn is deleting them, then they are not code issues

**Comment by GlennMurphy** [comment]
How is this unrelated? I see people having success on iPhone 6's but I haven't heard anything from 6+. So I am sharing what is happening. I don't think it is unrelated and I'm willing to try and help. The problem would need to be solved before a public release anyway?

**Comment by beanjo55** [comment]
@GlennMurphy the cydia issue is not related to the issue with the jailbreak. there have been many of these. they were all closed due to being unrelated to yalu.

**Comment by FrodoToto** [comment]
I'm on 6+ here too, my cydia doesnt install at all and i can't SSH

**Comment by beanjo55** [comment]
@FrodoToto #162 and #64

**Comment by FrodoToto** [comment]
@beanjo55 Why? Still trying to help, to get the jb stable.

**Comment by beanjo55** [comment]
@FrodoToto if you looked at the issues that i linked, it would explain that your issue is not related to the code of the jailbreak, rather its related to something else.

**Comment by kpwn** [comment]
I believe this is a Cydia issue I've encountered myself. Try backing up the /var/mobile/Library/Cydia/metadata.cb0 file, then removing the original, then running Cydia.

If it solved it, please give me the backup.

**Comment by GlennMurphy** [comment]
@FrodoToto just wait for kpwn to weigh in. If he closes this then he doesn't want to deal with it. I just want to make sure he's aware there is an issue on 6+ as he is using a 6.

**Comment by RKO1195** [comment]
Cydia works fine on my 6 Plus

**Comment by masbog** [comment]
@FrodoToto did you install OpenSSH from cydia? https://twitter.com/qwertyoruiopz/status/816641460569341952

**Comment by kpwn** [comment]
Can you all stop weighing in with useless info?

**Comment by skimaskngun** [comment]
Cydia works fine for me just get that annoying com.codigitaldarkroom.catalyst(newversion1) error every single damn time the repos refresh lol but can't complain too much

**Comment by MDallak** [comment]
Hi
me too I have this Problem 
u can install Filza on ur phone with Cydia impacter
Always need jailbreak working from yalu102
open filza /var/mobile/library/preferences/
and delete com.suarik.cydia.plist

**Comment by skimaskngun** [comment]
This removes that error? Thank you was gonna restore wheeew

**Comment by GlennMurphy** [comment]
[metadata.zip](https://github.com/kpwn/yalu102/files/737707/metadata.zip) @kpwn You're a god man. That solved it! I've attached the old metadata file. Seems live garbage to me but hopefully it helps.

**Comment by FrodoToto** [comment]
@masbog no i dont have cydia at all

**Comment by s0ram** [comment]
How did you do it ? @GlennMurphy
