### ISSUE TITLE
Cydia wont open after jailbreak 

### ISSUE THREAD

**Issue by DillHD** [kpwn/yalu102#220]
Using the latest IPA after jailbreaking cydia opens and instantly closes (tried roughly 10 times either hard resetting or normal restart) using iPhone 6, 10.2.

**Comment by beanjo55** [comment]
any logs?

**Comment by DillHD** [comment]
Where would I find the logs?

**Comment by jtv7** [comment]
@DillHD This isn't untethered, after reboot you have to re-run yalu...

**Comment by beanjo55** [comment]
@DillHD probably where the normal ios logs are

**Comment by bobbysn0w** [comment]
Go into Terminal

SSH into the device (use google if you have no idea how)

run

`rm /private/var/mobile/Library/Cydia/metadata.cb0`

**Comment by bobbysn0w** [comment]
Please close now :+1: #162

**Comment by DillHD** [comment]
Yes, I only restart because Yalu says im Jailbroken

**Comment by DillHD** [comment]
Also I cannot get Terminal because Cydia does not open.

**Comment by beanjo55** [comment]
@DillHD you do ssh from a computer, not on device

**Comment by jtv7** [comment]
@DillHD Don't reboot after jailbreaking, and close this issue. #162

**Comment by DillHD** [comment]
I only reboot because Cydia doesnt work, so I reboot and rejailbreak. I will try the ssh method and report back.

**Comment by beanjo55** [comment]
@DillHD this is a #64 and #162 the jailbreak works fine, so its not an issue with the jailbreak. please close the issue

**Comment by bobbysn0w** [comment]
@beanjo55 It's actually just an issue with Cydia. All he needs to do is SSH and run the command above.

**Comment by DillHD** [comment]
This JB comes with dropbear right?

**Comment by beanjo55** [comment]
@DillHD yes

**Comment by DillHD** [comment]
How do i SSH using cyberduck?

**Comment by beanjo55** [comment]
@DillHD google it. if you cant do that, than the JB may not be for you

**Comment by DillHD** [comment]
I have, but every article is saying use OpenSSH

**Comment by beanjo55** [comment]
@DillHD its no different. ssh is ssh. you get ip, you connect, you put in pasword, then you run commands

**Comment by DillHD** [comment]
What is the dropbear password? Google wont help me

**Comment by beanjo55** [comment]
@DillHD no password for dropbear. its the iphone account password
google should have told you that

**Comment by DillHD** [comment]
Do you mean my icloud pass? Also user is "root" right?

**Comment by beanjo55** [comment]
@DillHD no, not icloud or root. the account should be 'mobile' with password 'alpine'

**Comment by beanjo55** [comment]
again, google should have told you that

**Comment by OGKevin** [comment]
Try asking in r/jailbreak ;) if u don't know the answer to these simple questions ur asking i suggest u wait for stable.

**Comment by DillHD** [comment]
Nope I figured it out, Cydia now works. Thanks alot @beanjo55!

**Comment by s0ram** [comment]
How did you do it ? @DillHD

**Comment by DillHD** [comment]
just follow what beanjo said

**Comment by s0ram** [comment]
You used cyberduck ? @DillHD

**Comment by OGKevin** [comment]
@s0ram Cyberduck is a FTP client and doesn't work with Dropbear SSH

**Comment by DillHD** [comment]
I used Putty

**Comment by LegitSoulja** [comment]
@beanjo55 im having the same issue on my 6. 

I cannot get Cydia to run, I'm unaware of the term "dropbear". There's no port 22 open on my phone for SSH. So how exactly running the above command possible in this case?

**Comment by OGKevin** [comment]
Ssh only works over USB there is a tutorial how to achieve thin on Reddit. @LSoulja

**Comment by LegitSoulja** [comment]
@OGKevin after connected, and executing the command above cydia still crashes on launch.

Also, after checking the files within the directory of `/private/var/mobile/Library/Cydia` the file `metadata.cb0` is always generated on restart of the video.

Any other solutions? Thanks

**Comment by LegitSoulja** [comment]
EDIT:

The file `metadata.cb0` is generated after every restart, and opening of Cydia. What's the point of deleting this file if it will be instantly created when Cydia opens? Also, How can I get a log of the crash, so I can diagnose this issue myself with an exact reason of the crash. Thanks.

**Comment by LegitSoulja** [comment]
Model: Iphone 6
Version: 10.0.2
