### ISSUE TITLE
iPad Mini 4 Cellular doesnt Work

### ISSUE THREAD

**Issue by Vitauser** [kpwn/yalu102#223]
Hello,
Beta 2 a bunch of ipad minis does work now, but the ipad mini 4 cellular doesnt right ? i tried it about 40 times but sometimes there is standing failed, retry and after the reboot no cydia icon is there. is this a known problem ? Sorry because my bad English.

**Comment by beanjo55** [comment]
do you see the apple logo when it fails? any logs?

**Comment by Vitauser** [comment]
where is the log ? Where can i find it ? no i dont see the apple logo when it fails. in the yalu app there is after the go standing fails,retry. but not often.

**Comment by beanjo55** [comment]
once you run the app,  ssh into the device from a computer and:

Add a boolean YES called SBShowNonDefaultSystemApps in /var/mobile/Library/Preferences/com.apple.springboard.plist

**Comment by beanjo55** [comment]
no guarantees that woks though. might be the issue you have

**Comment by Vitauser** [comment]
what should i do know ? iam a beginner and the yalu app tells me go and then the ipad reboots but cydia still not there. so please tell me what to do now :-)

**Comment by beanjo55** [comment]
google it. the JB is still in beta, so things were not guaranteed to work.

**Comment by Vitauser** [comment]
what should i google ?

**Comment by beanjo55** [comment]
if you cant get that far, this jailbreak may not be for you, sorry

**Comment by beanjo55** [comment]
you should google how to ssh into an idevice though

**Comment by Vitauser** [comment]
i dojt know what you mean. my iphone and my ipad air does work flawlessly with the jailbreak but only my ipad mini does not work and iam only asking why,because the minis should work or ?

**Comment by beanjo55** [comment]
just because some devices work does not mean all devices work 100% of the time. every model has minor differences that may make the JB work or fail

**Comment by Vitauser** [comment]
yes i know this already but my question is, is there maybe anybody that the jailbreak work with his ipad mini 4 or is it normal that this ipad mini 4 isnt supported yet. you know what i mean ?

**Comment by beanjo55** [comment]
it seems there may be an issue with this code with the mini 4. not entirely confirmed, but maybe

**Comment by Vitauser** [comment]
ok where do you know this ?

**Comment by beanjo55** [comment]
other issues have been opened, and just the general issues with compatability this JB had before the bugs were found

**Comment by Vitauser** [comment]
ok thank you.

**Comment by Vitauser** [comment]
beta 3 also does not fix it. still not working

**Comment by Vitauser** [comment]
I think one thread with the issue is enough. So i close here
