### ISSUE TITLE
iPhone 6 Plus Cydia is not showing

### ISSUE THREAD

**Issue by xXDjMikeXx** [kpwn/yalu102#224]
iPhone 6 Plus
iOS 10.2
Yalu102 beta 2

No Cydia icon after pressing go (app says already jailbroken)

I tried to reprocess the jailbreak but Cydia won't appear

**Comment by beanjo55** [comment]
this may help. kpwn said
Add a boolean YES called SBShowNonDefaultSystemApps in /var/mobile/Library/Preferences/com.apple.springboard.plist

you need to ssh in and do it

**Comment by xXDjMikeXx** [comment]
Is ssh installed? I cant install because Cydia is not there

**Comment by beanjo55** [comment]
yes, its called dropbear and is installed by default

**Comment by OGKevin** [comment]
@xXDjMikeXx  it comes with dropbear so u don’t have to install any SSH client from cydia

**Comment by xXDjMikeXx** [comment]
Ok thanks for your help

**Comment by kpwn** [comment]
that thing is only significant to iPads.
just try running uicache.

**Comment by xXDjMikeXx** [comment]
I am using WinSCP and it says Connection not accepted

Username: root
Pass: alpin

**Comment by xXDjMikeXx** [comment]
Oh wrong pass but its not working either 
alpine

**Comment by xXDjMikeXx** [comment]
How to uichache?

**Comment by OGKevin** [comment]
WinSCP is not a SSH client but a SFTP FTP client if im not mistaken so this wont work. Again u better ask on r/jailbreak.

**Comment by shdkpr2008** [comment]
@xXDjMikeXx use putty for win.

**Comment by xXDjMikeXx** [comment]
How to uicache?
Not working (connection refused)

**Comment by OGKevin** [comment]
try these steps: https://www.reddit.com/r/jailbreak/comments/5qoi4i/question_how_do_i_use_ssh_on_yalu102/dd26od9/?context=10000

**Comment by xXDjMikeXx** [comment]
There are no steps

**Comment by shdkpr2008** [comment]
@xXDjMikeXx Reboot and re-jailbreak. Dropbear (server) might got session terminated. Ssh to your device ip only after you jailbreak. See the ip in settings/wifi/access-point-name (i). Click that i and you will see ip allocated to your device.
After a successful login type the command
`/usr/bin/uicache`
and do hit enter key.

@OGKevin  OP might not have installed Terminal app as no Cydia situation there.

**Comment by OGKevin** [comment]
I see, if you don’t have terminal than the link I’ve provided will be indeed useless for you.
