### ISSUE TITLE
iPad Mini 4 WiFi, does not work

### ISSUE THREAD

**Issue by jackb992** [kpwn/yalu102#225]
I've just come from the precompiled website after trying on my iPad mini 4, it seems though when I try to do it. It shows a half-filled black/white screen then reboots. Is this a confirmed issue? I don't know how to send logs, but I'll certainly send one if I'm instructed.

Thanks in Advance

**Comment by beanjo55** [comment]
do you see the apple logo?

**Comment by jackb992** [comment]
Yes, after the black/white screen

**Comment by beanjo55** [comment]
ok, other people are saying ipad mini 4 is not working. may be incompatable. @kpwn should the ipad mini 4 work or is this something else?

**Comment by msamuel002** [comment]
go to settings > privacy > diagnostics and usage > diagnostics and usage data and copy and paste any one of the "panic" or "com.apple.WebKit.WebContent" logs to pastebin.com and then send the link here. this will help @kpwn  a lot

**Comment by kpwn** [comment]
webcontent is not related with yalu

**Comment by jackb992** [comment]
I'll send a panic over in just a sec

**Comment by msamuel002** [comment]
sorry lol but i thought it was related with yalu in my case since it was over using the cpu and then that caused it to crash?? must not be related after all! thanks for the info

**Comment by jackb992** [comment]
Here's a Pastebin link: http://pastebin.com/zqhS5ArV

**Comment by msamuel002** [comment]
@jackb992 holy

**Comment by Vitauser** [comment]
thats what i have exactly with my mini 4 cellular

**Comment by Matchstic** [comment]
Can confirm too, with iOS 10.2 (14C92) and iPad5,2. I've repeated for 10 attempts, using both the latest publicly available IPA, along with compiling directly from source at commit: https://github.com/kpwn/yalu102/commit/731b7a1bf5c5a2ce3f4fb119829af6c3f3425021

Logs:
Yalu: https://ghostbin.com/paste/yekfw
Panic: https://ghostbin.com/paste/cw4y6

**Comment by Vitauser** [comment]
beta 3 also does not fix it. still not working

**Comment by bluntavious** [comment]
I am having the same issue on iPad Mini 4 WiFi with beta 2 & beta 3.

**Comment by TheLukeGuy** [comment]
Same issue. 😐

**Comment by Vitauser** [comment]
Maybe you could be right. Hopefully it will be fixed soon. Iam waiting for my ipad mini4 to be jailbroken :-)

**Comment by NewDwarf** [comment]
It is not a problem of amount of RAM. It looks like both iPad air2 and iPad mini 4 are 16K devices with similar MMU.

**Comment by hduarte** [comment]
"In OS X and in earlier versions of iOS, the size of a page is 4 kilobytes. In later versions of iOS, A7- and A8-based systems expose 16-kilobyte pages to the 64-bit userspace backed by 4-kilobyte physical pages, while A9 systems expose 16-kilobyte pages backed by 16-kilobyte physical pages."

(https://developer.apple.com/library/content/documentation/Performance/Conceptual/ManagingMemory/Articles/AboutMemory.html)

The iPad Air 2 is the only device with an A8X SoC with 2GB LPDDR3.
The iPad mini 4 is the only device with an A8 SoC with 2GB LPDDR3.

Does it have to do with the fact that they are 4K devices but expose 16K page table size to the 64bit iOS ?

**Comment by hduarte** [comment]
By forcing the pagesize to 4k i was able to run yalu successfully on the iPad mini 4.

**Comment by KILLCAMPER** [comment]
Do you think this what's happening with pad Air 2 as well

**Comment by hduarte** [comment]
@KILLCAMPER yep the same. I believe it is related to what I had explained in the post above.

**Comment by Vitauser** [comment]
So is it possible that the jailbreak for the ipad mini 4 and the ipad air 2 is coming today ?

**Comment by jackb992** [comment]
Could you show how to force the 4K page size?

**Comment by german8835** [comment]
@hduarte if you forced it, could there be any performance issues?
