### ISSUE TITLE
iPad Air 2 WiFi failed, with logs

### ISSUE THREAD

**Issue by Steve-luo** [kpwn/yalu102#227]
Tried the latest commit 8c21acb on my iPad Air 2 WiFi on iOS 10.2 (14C92). It reboots after running the app.

Panic Log: http://pastebin.com/X9Grhjyx
Yalu Log: http://pastebin.com/tN0Xt6X5

Hope this helps, and thanks for your hard work.

**Comment by beanjo55** [comment]
ipad air 2 is not yet supported

**Comment by Steve-luo** [comment]
@beanjo55 Oops, I never checked the website. I assumed 4K devices mentioned include it. Awaiting update. Thanks
