### ISSUE TITLE
Iphone 7 & 7 plus support

### ISSUE THREAD

**Issue by B0ngL0rd** [kpwn/yalu102#23]
How much more for the 7 & 7+ to be supported??

**Comment by nicogibbons** [comment]
It has been said for a long time iPhone 7 only has 10.1 and below support

**Comment by B0ngL0rd** [comment]
Was kindly asking a question, didn't want a hostile situation.

**Comment by nicogibbons** [comment]
Didn't mean to be hostile haha

**Comment by GusToughSon** [comment]
If User = 10.1.1 then
            While being built 
             (wait)
            wend
endif
if user = 10.2 < then
            user = Boned
endif

**Comment by B0ngL0rd** [comment]
sysname: Darwin
nodename: iPhone
release: 16.3.0
version: Darwin Kernel Version 16.3.0: Tue Nov 29 21:40:08 PST 2016; root:xnu-3789.32.1~4/RELEASE_ARM64_T8010
machine: iPhone9,4
missing offset, prob crashing
2017-01-26 14:20:23.272130 yalu102[230:7770] found corruption 38503

**Comment by B0ngL0rd** [comment]
Probably no hope for iOS 10.2 jb iPhone 7 plus
