### ISSUE TITLE
assert ./plist.hpp:343 fails

### ISSUE THREAD

**Issue by lucysan** [kpwn/yalu102#230]
None of the betas work, all fail while uploading using Impactor with the following error:

Error
./plist.hpp:343
_assert(plist != ULL)

Using iPhone 6s+ and impactor on os x, happens on both beta 1 and 3 (using pre-compiled files).

**Comment by kpwn** [comment]
update your impactor

**Comment by lucysan** [comment]
It is on the latest version.

**Comment by shdkpr2008** [comment]
@lucysan Refer to https://www.reddit.com/r/sideloaded/comments/5jrxq6/question_can_someone_help_me_with_this_error/

**Comment by lucysan** [comment]
@shdkpr2008 I am using 0.9.38

**Comment by OGKevin** [comment]
Is your Developer account associated with a developing team? This is a question you should ask in r/jailbreak.

**Comment by shdkpr2008** [comment]
@lucysan There is no problem with latest beta 3 ipa and impactor version 0.9.38.
As @OGKevin said verify that you are using a developer account. Try to enroll if you aren't. Go to https://developer.apple.com/membercenter/ and login with your apple-id enroll for free apple developer account.
