### ISSUE TITLE
iPod 6th Gen 10.2 Cydia wont install

### ISSUE THREAD

**Issue by king4q** [kpwn/yalu102#232]
so i went to jailbreak for the first time ever on IOS 10 i did however jailbreak on IOS 9.3.2 when i first got the ipod and so i went and downloaed the beta so i used cydia impactor and installed it and trusted it and ran the jailbreak but it wont install cydia it keeps freezing on the application and then rebooting not a re-spring a reboot and so im wondering if anybody can help me please and thank you

**Comment by beanjo55** [comment]
do you see the apple logo? any logs?

**Comment by king4q** [comment]
i dont know how to access the logs if you tell me how i can most likely do it and yes i see the apple logo but like i said before its a rebooting not a respring

**Comment by beanjo55** [comment]
what yalu102 version are you using?

**Comment by king4q** [comment]
beta 3

**Comment by beanjo55** [comment]
you see cydia? logs should be where the normal ios logs are

**Comment by beanjo55** [comment]
google the log location. you are on 10.2 not 10.2.1 right?

**Comment by king4q** [comment]
yes and i tried with the lates one more time and it randomly decided to work

**Comment by king4q** [comment]
because he released beta2 and beta3 i was originally trying with beta 2 not 3 and now it worked

**Comment by beanjo55** [comment]
ok. you can close the issue now

**Comment by king4q** [comment]
also so i was earlier trying to jailbreak a iphone 6s and it kept doing to exact same thing and i do not have access to the device currently, but its a friends and you see the apple log and it keeps rebooting but he hasnt ever jailbroken his phone before

**Comment by king4q** [comment]
i cannot access his logs, for the iPhone 6s

**Comment by beanjo55** [comment]
just use latest beta. close the issue please

**Comment by king4q** [comment]
k thank you
