### ISSUE TITLE
iPad mini 2 does not Jailbreak

### ISSUE THREAD

**Issue by JoeGodz** [kpwn/yalu102#236]
I press go, the storage is full notification shows up, then it says already jailbroken. No reboot. No respring. No cydia.

**Comment by beanjo55** [comment]
logs? yalu beta version?

**Comment by beanjo55** [comment]
does the app say already jailbroken if you open it again?

**Comment by kpwn** [comment]
you are actually jailbroken.
ssh into your device and run uicache to make Cydia show up, or refer to #209

**Comment by bakirfatah** [comment]
Luca you release untether jailbreak ios 10.2?
