### ISSUE TITLE
Appsync not working

### ISSUE THREAD

**Issue by Macros2003** [kpwn/yalu102#237]
Does anyone know why appsync does not work on ios 10.2

**Comment by KILLCAMPER** [comment]
Yawwwwwwwwwwn

**Comment by OGKevin** [comment]
App sync doesn't work #162

**Comment by JMccormick264** [comment]
omg. go ahead and install it if you want to fuck up your phone. Just search on google "AppSync on iOS 10"
@kpwn please close. due to the dumbness of this

**Comment by personifigiaovsiin** [comment]
App sync needs to be updated. Come on people be patient!

**Comment by neuro-mantik** [comment]
Fuckin noob...
