### ISSUE TITLE
Why does it not work on ipad air 2?

### ISSUE THREAD

**Issue by cemre2002** [kpwn/yalu102#239]
It sais it doesn't work, but why not..... 
Ipad air 2 is the only device I want to jailbreak, and it doesn't support it...

**Comment by maetrik92** [comment]
Just close this issue and rest in piece.fcking noobs.

**Comment by beanjo55** [comment]
dont know specifics, but its usually memory. if not then its the cpu or kpp. close isue please though

**Comment by JMccormick264** [comment]
check #190

**Comment by cemre2002** [comment]
.... I know that it does not work, but I'm asking why is does work on all other ipads (like ipad air 1) that are also 64 bit and 4K, so why not on ipad air 2?

**Comment by nicogibbons** [comment]
The iPad Air 2 has 3 CPU's

**Comment by JMccormick264** [comment]
it has 3 CPUs instead of 2 which is the max number (2 CPUs) that this has been tested on

**Comment by cemre2002** [comment]
Ok, lets just take a drill, drill the ipad open, pull one cpu out. Then destroy the cpu (with fire!!!) and then jailbreak!

**Comment by beanjo55** [comment]
@cemre2002 you have been answered, please close issue

**Comment by JMccormick264** [comment]
Answered. please close

**Comment by OGKevin** [comment]
#162

**Comment by cemre2002** [comment]
Closed
