### ISSUE TITLE
iPhone 6 yalu102 Issues (as of now)

### ISSUE THREAD

**Issue by vec1phyr** [kpwn/yalu102#240]
Recently installed this and as you've mentioned before that performance is affected.
I'm not certain if you're able to but after updating the Tape Archive, Debian Packager and installing the Cydia beta. It solved most issues. Would shipping the beta software with these said updates solve this initial lag?

I also have plenty of xCode related problems during compile that I shall be including shortly as a reply (need to rerun in a couple of hours as I'm on mobile.) If you would prefer I'd send those separately, I'll open a new issue.

I have no logs to provide as the lag was solved after these updates. Thanks

**Comment by beanjo55** [comment]
#64 #162 not a yalu issue. please close

**Comment by JMccormick264** [comment]
this is not a JB issue.

**Comment by vec1phyr** [comment]
Ah okay, wasn't sure if it was related to the shipped Cydia in Yalu. Thanks.

**Comment by beanjo55** [comment]
please close the issue

**Comment by OGKevin** [comment]
#162
