### ISSUE TITLE
10.2.1 OTA Update Still Loading

### ISSUE THREAD

**Issue by tsuehpsyde** [kpwn/yalu102#242]
Using beta3 IPA on an iPhone 6S (TSMC), the OTA update is still loading under settings and offering to install 10.2.1.

https://github.com/kpwn/yalu102/commit/718bdc80cbe9f31ebdca3d05b53a0c6886c4499a

Assuming the above commit is in beta3 (I assume it is), something's not quite right.

Since I've had the OTA bugging me prior to jailbreaking, I let the OTA update download fully, deleted it from storage, rebooted, re-jailbroke using yalu immediately, re-checked and it's still offering to allow to update. 

If you need any further information, let me know.

**Comment by beanjo55** [comment]
install the tvos profile to stop OTA. search it on r/jailbreak

**Comment by maetrik92** [comment]
Or just mikoto..

**Comment by JMccormick264** [comment]
Download the tvOS profile from here https://beta.applebetas.tk/

**Comment by OGKevin** [comment]
here is the link to tvOS https://hikay.github.io/app/tvos10.mobileconfig don’t think u will find it on r/jailbreak due to the rules.

**Comment by bigfrog** [comment]
follow this link on safari on the iPhone or whatever you tying to stop the OTA update:

hikay.github.io/app/NOOTA.mobileconfig

**Comment by keldegar** [comment]
@maetrik92 Mikoto is removing the update menus but is not stopping ota from downloading

**Comment by masbog** [comment]
check my PR #146

**Comment by mailinglists35** [comment]
```
launchctl disable system/com.apple.softwareupdateservicesd
launchctl disable system/com.apple.OTATaskingAgent
launchctl disable system/com.apple.mobile.softwareupdated
```
=> forever spinning wheel instead of download and install button

also others say just blocking mesu.apple.com (http://www.richard-purves.com/2016/09/10/apple-services/) is enough https://www.reddit.com/r/jailbreak/comments/5r54yi/tutorial_blocking_ota_updates_without_jailbreak/
