### ISSUE TITLE
exported kernel_pmap

### ISSUE THREAD

**Issue by NewDwarf** [kpwn/yalu102#243]
@kpwn Is it possible to use the exported symbol 'kernel_pmap' directly through offset like 
 'allproc_offset' and 'rootvnode_offset' to access level1 table?

**Comment by NewDwarf** [comment]
Just checked it. Assumption works.
    uint64_t pmap_store = find_kernel_pmap();    
    uint64_t pmap_store1 = pmap_store = ReadAnywhere64(kernel_pmap_offset + kernbase);

(lldb) p/x pmap_store
(uint64_t) $0 = 0xfffffff01cf9a868
(lldb) p/x pmap_store1
(uint64_t) $1 = 0xfffffff01cf9a868

**Comment by kpwn** [comment]
find_kernel_pmap requires no symbol.
