### ISSUE TITLE
No cydia

### ISSUE THREAD

**Issue by JoaoPadilha** [kpwn/yalu102#244]
Hi. I've installed the beta2 version, and after that decided to remove cydia, and yalu to upgrade to the latest build (beta3).

I've restored my iphone 6 and installed the beta3 .ipa and yalu runs fine, and shows the message saying "already jailbroken" but I don't get cydia installed.

Any help please?

**Comment by beanjo55** [comment]
ssh and run uicache

**Comment by OGKevin** [comment]
Not an issue w YALU. And i think this has been asked multiple times.  #162

**Comment by callum-99** [comment]
"ssh into your device and run uicache to make Cydia show up, or refer to #209 if it still doesn't work"

**Comment by JoaoPadilha** [comment]
uicache doesn't work. I mean, it runs but no cydia icon...

**Comment by beanjo55** [comment]
@JoaoPadilha refer to issue #209

**Comment by JoaoPadilha** [comment]
I'm sorry for such a dumb question, but I don't have nano or vi... how can edit the plist?

**Comment by beanjo55** [comment]
via ssh. you can copy the file to a pc, edit it in notepad or something, then move it back and overwrite the original

**Comment by JoaoPadilha** [comment]
ok, I will try that.

**Comment by OGKevin** [comment]
SCP doesnt currently work to copy paste files u use this instead if u run in issues copy pasting. https://www.reddit.com/r/jailbreak/comments/5pk3am/questionscp_on_dropbearssh_yalu_b3_1011/dcrrz0f/

**Comment by beanjo55** [comment]
didnt know about the issue with dropbear. follow advice from @OGKevin

**Comment by JoaoPadilha** [comment]
Well... I'm running windows, I only have putty...

**Comment by OGKevin** [comment]
ah, not sure if you can/how perform these steps w putty/windows.

**Comment by kpwn** [comment]
> Hi. I've installed the beta2 version, and after that decided to remove cydia, and yalu to upgrade to the latest build (beta3).



You removed Cydia. Brilliant fucking idea.


Remove /.installed_yaluX to reinstall it.

**Comment by JoaoPadilha** [comment]
I removed Cydia after the beta2 installation. I restored my device, and I installed beta3 after that.
But even after that I don't get Cydia icon.

**Comment by JoaoPadilha** [comment]
Btw, thank you for the help, removing /.installed_yaluX did fix it.
