### ISSUE TITLE
iMessage application #images addon does not load

### ISSUE THREAD

**Issue by Crazy-Clown** [kpwn/yalu102#245]
iPhone6 plus on 10.2 yalu102 beta3 - iMessage application addon #images does not load.

![imageserror](https://cloud.githubusercontent.com/assets/20711887/22408257/7518f6ea-e644-11e6-9932-bd58f76240f8.png)

**Comment by beanjo55** [comment]
#64 #162 not a yalu code issue please close

**Comment by eXhumer1149** [comment]
I believe this is Yalu102/Subtrate problem. Until qwertyoruiop says it is not a Yalu code problem, this should stay open.

**Comment by nullpixel1** [comment]
@beanjo55 shut up, we think it's a yalu issue

**Comment by OGKevin** [comment]
Do not be rude, me and @beanjo55 has been helping allot of people these past 2 nights and ofc we could be wrong sometime but that doesn't give you the right to be rude.

**Comment by nullpixel1** [comment]
I've been helping a lot too, but referring actual issues is wrong

**Comment by OGKevin** [comment]
And thats good/nice of you, but still telling someone to shut up who also has been helping allot is not nice. U could have told him another way that he was/is wrong. But lets not get off topic here.

**Comment by bobbysn0w** [comment]
This is an actual issue not a #162 lol...

**Comment by EricRabil** [comment]
@OGKevin he told you to shut up because you jumped to conclusions and instead of suggesting this is not a code issue, simply stated that it was a #162 without consulting others, resulting in it being mistakenly closed.

**Comment by OGKevin** [comment]
Please go and re read the comments and get your facts straight.

**Comment by venturac** [comment]
This isn't working for me either and when not running yalu it works. enable the jailbreak and it doesn't load and you can't search. Does @qwertyoruiop know about this?

**Comment by eXhumer1149** [comment]
Yes

#294
