### ISSUE TITLE
Broken springboard

### ISSUE THREAD

**Issue by MAMASWAN** [kpwn/yalu102#247]
I opened Curia and only downloaded 1 tweak it resprung and came back with a broken springboard

**Comment by MAMASWAN** [comment]
"Cydia"

**Comment by beanjo55** [comment]
#162 #64 not a yalu issue. its an issue with the tweak

**Comment by OGKevin** [comment]
#162 not Yalu related

**Comment by beanjo55** [comment]
contact the developer of the tweak. please close issue

**Comment by MAMASWAN** [comment]
Oops
