### ISSUE TITLE
I wasn't done XD

### ISSUE THREAD

**Issue by MAMASWAN** [kpwn/yalu102#248]
After I restored I rejailbroke my iPhone and it resprung after clicking go and my iPhone didn't come back on t started to boot loop and I had to restore again i saved my blobs and I'm currently unjailbroken

**Comment by beanjo55** [comment]
#162 #64 STILL NOT A YALU ISSUE. please close

**Comment by OGKevin** [comment]
#162

**Comment by beanjo55** [comment]
if your issue was closed, its not an excuse to just open another one

**Comment by MAMASWAN** [comment]
How not

**Comment by MAMASWAN** [comment]
I was in the process of using Yalu and it bricked iOS

**Comment by beanjo55** [comment]
because, yalu work fine, you fucked up. not yalu

**Comment by MAMASWAN** [comment]
So let me get this straight

**Comment by MAMASWAN** [comment]
Let me see what I did wrong

**Comment by OGKevin** [comment]
@beanjo55 so much patience

**Comment by MAMASWAN** [comment]
I used Cydia impactor to use Yalu trusted the developer and then ran it. Seems to me like I followed exactly the fuck I was supposed to do

**Comment by beanjo55** [comment]
you restored through itunes the first time?

**Comment by MAMASWAN** [comment]
Yes

**Comment by MAMASWAN** [comment]
And that's not it

**Comment by beanjo55** [comment]
what phone? its on 10.2 right? no tweaks? and did you restore a backup?

**Comment by MAMASWAN** [comment]
I restored it no tweaks and it was on 10.2 I used a backup of before it was jail broken

**Comment by beanjo55** [comment]
ever jailbroken before a ios 10 jb?

**Comment by MAMASWAN** [comment]
I apologize for opening a new issue I thought that when it was closed I couldn't comment

**Comment by neuro-mantik** [comment]
dude go on reddit it's not the right place here!

**Comment by OGKevin** [comment]
Ur better of finding help in r/jailbreak

**Comment by MAMASWAN** [comment]
I have jail broken iOS 7 before with an iPod 5

**Comment by beanjo55** [comment]
did you use the backup from the ipod to go to the current device? (had an ipod, got a phone and transfered everything)

**Comment by MAMASWAN** [comment]
Yes

**Comment by beanjo55** [comment]
i know back in the old days (ios 4-6 days may be a stretch) tweaks could be in backups or just configs that cydia and stuff use. Its possible that it affects newer jailbreaks. this was years ago that these things happened, but it could still happen. its the only reason that a restored phone would bootloop after jailbreaking

**Comment by MAMASWAN** [comment]
Oh

**Comment by MAMASWAN** [comment]
That makes sense

**Comment by OGKevin** [comment]
in other words restore and start fresh

**Comment by MAMASWAN** [comment]
I'll try restoring without a backup and then try it again

**Comment by beanjo55** [comment]
10.2 signing window is still open, try and start fresh.

**Comment by MAMASWAN** [comment]
Okay thanks

**Comment by beanjo55** [comment]
get anything you need off of the phone by restoring the backup first

**Comment by beanjo55** [comment]
then restore so its fresh, then jailbreak

**Comment by MAMASWAN** [comment]
Got it
