### ISSUE TITLE
Not working on iPad Air 2 on 10.2.

### ISSUE THREAD

**Issue by KittyCatCode** [kpwn/yalu102#249]
I know this is known, it's even in the readme, I just wanted to post the logs for it.
Console Output: http://pastebin.com/FhjNRSgt
Panic: http://pastebin.com/qzyK5WQ9
ResetCounter: http://pastebin.com/imEq8Y9v

**Comment by beanjo55** [comment]
cool, i think there are enough logs collected though

**Comment by KittyCatCode** [comment]
I didn't know.
