### ISSUE TITLE
Are just the correct offsets needed to support other devices

### ISSUE THREAD

**Issue by andrewwiik** [kpwn/yalu102#25]
I was just wondering if just the correct offsets are needed for other devices or if other things are needed as well. A straight forward answer will suffice, thanks.

**Comment by ninjaprawn** [comment]
afaik only the offsets

**Comment by drake90001** [comment]
Offsets will help, I believe. allproc and rootvnode. If you have 10.2 IPSW and can find those, feel free to contribute them for other devices. Also, make sure to make a case for it and not override defaults.

**Comment by andrewwiik** [comment]
But are they the only other things needed, I have the IPSW and hopper+IDA

**Comment by onchehuh** [comment]
Take the ipsw decompress the kernelcache, find allproc with IDA
Then find rootvnode with `nm decompressed_kernel | grep rootvnode`

**Comment by drake90001** [comment]
You'll need to calculate rootvnode

**Comment by darkplace** [comment]
iPhone SE N69uAP using correct offsets:
allproc_offset = 0x5a8438;
fffffff0075b20b8 S _rootvnode

finish with:

2017-01-26 04:10:28.316701 yalu102[243:4678] enabled patches
2017-01-26 04:10:28.318011 yalu102[243:4678] remounting: -1
2017-01-26 04:10:28.318234 yalu102[243:4678] done

**Comment by andrewwiik** [comment]
calculate as in math?

**Comment by kpwn** [comment]
remounting: -1 -> rootvnode is wrong.

**Comment by drake90001** [comment]
yes math, as in hex - hex

-1 means you didn't convert it right

**Comment by andrewwiik** [comment]
got a twitter? @drake90001

**Comment by drake90001** [comment]
yes it's @drake90001

**Comment by darkplace** [comment]
(Using same kernelcache.decompressed to find allproc_offset)

DarkPlace:extractor darkplace$ nm kernelcache.decompressed | grep rootvnode
fffffff0075b20b8 S _rootvnode
fffffff0071d3eac S _vfs_rootvnode

using: rootvnode_offset = 0x5b20b8;

returning remounting: -1

**Comment by nullpixel1** [comment]
the SE offsets are the same as https://github.com/kpwn/yalu102/pull/18/

**Comment by darkplace** [comment]
cool, seems returning a wrong rootvnode offset, with 5ae0b8 works perfectly. tftp working correctly.

**Comment by onchehuh** [comment]
Yes, you have to subtract the __TEXT:HEADER value from rootvnode just like allproc

**Comment by darkplace** [comment]
@nullpixel1 @kpwn working on SE N69uAP
allproc 0x5a8438 / rootvnode 0x5ae0b8 (same as 6S)

**Comment by nullpixel1** [comment]
Awesome! 👍

**Comment by DarknesGaming** [comment]
Wow. I didn't know Luca would go so far as to get help for his next Yalu release. Something tells me he's not going to keep working on iOS 10.1.1 anymore.
Still searching for offsets for iPhone 6. Went crazy disassembling the broken beta. Aren't you disappointed, qwertyoruiop? I disassembled your code because I'm crazy and I know almost zero Objective-C.

**Comment by lucid727** [comment]
Will these offsets open the ip7 on 10.2 to be able to jailbreak?? Just wondering what it would take for the iPhone 7 on 10.2 to be jail broken..thanks for the help..

**Comment by B0ngL0rd** [comment]
As a iPhone 7 plus 10.2 user DOOOOMED

**Comment by B0ngL0rd** [comment]
sysname: Darwin
nodename: iPhone
release: 16.3.0
version: Darwin Kernel Version 16.3.0: Tue Nov 29 21:40:08 PST 2016; root:xnu-3789.32.1~4/RELEASE_ARM64_T8010
machine: iPhone9,4
missing offset, prob crashing
2017-01-26 14:20:23.272130 yalu102[230:7770] found corruption 38503

**Comment by liudayu** [comment]
@lucid727 @B0ngL0rd  No. NO jailbreak for 10.2 iPhone 7.
