### ISSUE TITLE
iPhone 7 + issue 

### ISSUE THREAD

**Issue by codivilian** [kpwn/yalu102#251]
any planned support or no i just would like to know so i knows whether or not to get my hopes up on 10.2

**Comment by OGKevin** [comment]
#162

**Comment by aididhaiqal** [comment]
I guess #162

**Comment by codivilian** [comment]
i kinda put wanted lucas response

**Comment by maetrik92** [comment]
The answer that you seek is on the readme.

**Comment by timonline** [comment]
@codivilian for the love of GOD, did you even attempt to read the readme?

Plus THIS IS NOT AN ISSUE!
