### ISSUE TITLE
Performance for yalu102 (iphone 6)

### ISSUE THREAD

**Issue by msamuel002** [kpwn/yalu102#252]
Hey @kpwn, just wanted to ask if you think that the performance issues caused by the jb will be an easy fix? I know this is not freakin related to jb directly but still.

**Comment by OGKevin** [comment]
This isn't a bug with Yalu #162

**Comment by kpwn** [comment]
Is it any significant? I don't think it is. Haven't seen this affect real-life usage outside of targeted microbenchmarks.

**Comment by justinoboyle** [comment]
Can confirm that real-life usage has not been affected at all. Been using this for six or seven hours a little heavier than usual and nothing is out of the ordinary.

iPhone 6.

Also, this isn't a bug, please close the topic.

**Comment by bobbysn0w** [comment]
#162

**Comment by msamuel002** [comment]
@kpwn It is SUPER slow on my device. before this, it would run super smoothly, and now, every single thing lags.

**Comment by justinoboyle** [comment]
That's very specific.

**Comment by msamuel002** [comment]
if it isn't supposed to hinder my usage, what should I do to get it running more smoothly? i have updated to the latest commit

**Comment by msamuel002** [comment]
lol i meant that all the apps would become laggy and say on snapchat when i double tap to reply to a snap, it would take forever to bring the picture screen up, same with messages, etc.

**Comment by timonline** [comment]
#162

**Comment by msamuel002** [comment]
I GET IT @timonline chill out. i am seeing what i can do to get my device running smoothly

**Comment by jsidnsiandsnfjnsf** [comment]
hey did you compile the newest beta number 4 if yes send link of it in google drive to check it

**Comment by timonline** [comment]
@msamuel002 do you know the difference between issue and performance lag?

**Comment by jsidnsiandsnfjnsf** [comment]
my iPhone 6 on ios 10.2 loads cydia and wont show any apps or tweaks. any ideas

**Comment by msamuel002** [comment]
@jsidnsiandsnfjnsf i use xcode since i dont want to keep signing it every 7 days

**Comment by jsidnsiandsnfjnsf** [comment]
I know but did you compile the latest beta cuz there isn't an ipa made yet if u didn't do it now and try it if u already did and same issues put the ipa for beta 4 that u compiled in google drive and send link so we could check if its right or not

**Comment by msamuel002** [comment]
soo @kpwn what do u suggest i do? should i clear all unused dependencies, cache files, etc. using iCleaner Pro? maybe it still has many crash logs from before affecting the usage?

**Comment by jsidnsiandsnfjnsf** [comment]
hes busy I'm here waiting for link, also he will just delete ur post cuz it isn't related to coding

**Comment by msamuel002** [comment]
oh i see @jsidnsiandsnfjnsf i cant compile the ipa cuz xcode says i have to be a developer even though i am a part of the free developer program

**Comment by timonline** [comment]
@msamuel002 no, you don't have to be a developer. The developer account is only useful for publishing the ipa

**Comment by msamuel002** [comment]
@timonline so i have to go to product > archive right?

**Comment by msamuel002** [comment]
and then the only option i get is "download dSYMs"

**Comment by msamuel002** [comment]
the "export" button is greyed out

**Comment by timonline** [comment]
@msamuel002 you can just build + run.

You sure you want to be messing with compiling beta code, i ask coz it seems you are just starting out

**Comment by timonline** [comment]
Dammit you sucked me in with your non-issues. @kpwn please close this

**Comment by msamuel002** [comment]
wait sorry for recommenting @kpwn but would installing yalu on xcode VS on impactor change the performance?

**Comment by nicogibbons** [comment]
How you install the IPA won't change anything.

**Comment by msamuel002** [comment]
lol yea i figured. i reinstalled yalu from xcode, re did the jb, and now its perfect!

**Comment by jsidnsiandsnfjnsf** [comment]
send me link of the beta 4 you compiled on google drive need it too lol

**Comment by msamuel002** [comment]
since the way i install it wont change anything, i used xcode still
