### ISSUE TITLE
Apple Mach-O Linker Error Group

### ISSUE THREAD

**Issue by AbouImran** [kpwn/yalu102#253]
Apple Mach-O Linker Error Group

<img width="484" alt="mach-o linker error" src="https://cloud.githubusercontent.com/assets/24853903/22409135/1f7c10d0-e67d-11e6-8b1e-e41a7e62e8b4.png">

**Comment by timonline** [comment]
Incorrectly linked IOKit headers

**Comment by beanjo55** [comment]
#162 #64 not a yalu bug please close

**Comment by timonline** [comment]
@beanjo55 precisely!

**Comment by nicogibbons** [comment]
double precisely!

**Comment by AbouImran** [comment]
@timonline can u help me plz

**Comment by beanjo55** [comment]
@AbouImran the information is already on this repo if would look first

**Comment by AbouImran** [comment]
@beanjo55 I search but I can not find

**Comment by timonline** [comment]
@AbouImran This place is only for actual issue with Yalu, not being unable to compile the code on your side.

If you do not know how or can't find the info in this repo, then try searching in /r/jailbreak, twitter, or google.

**Comment by beanjo55** [comment]
@AbouImran then this isnt for you or haven't search hard enough

**Comment by kpwn** [comment]
> ipohne simulator

grow a brain

**Comment by AbouImran** [comment]
its ok its good now

**Comment by AbouImran** [comment]
A human can forget, miss things.
This is why we ask for help

**Comment by timonline** [comment]
@AbouImran that's fine but this is not the place to provide support. Only ISSUES
