### ISSUE TITLE
Already Jailbroken after Rebooting

### ISSUE THREAD

**Issue by amineangx** [kpwn/yalu102#254]
Firstly i want to thank you for your efforts to give us this tool.
here is my problem :
iphone 5s dock , Safari icon, Settings, cydia app icon not showing up anymore  and i can't rejailbreak after rebooting my iphone , when i open yalu it tell me that its already jailbroken
what should i do.
The last thing i had do is installing appsync unfied

**Comment by justinoboyle** [comment]
Sigh. Appsync is not supported for hundredth time.

Not yalu related. Close this issue. #162

**Comment by timonline** [comment]
#162 

Appsync unified is known to cause a bootloop, you're lucky that it didn't

**Comment by timonline** [comment]
@justinoboyle yes for the millionth time it seems

**Comment by justinoboyle** [comment]
@timonline At this point a massive warning needs to be placed in the README so that we don't keep getting this shit

**Comment by timonline** [comment]
@justinoboyle oh C'MON as if people who are <insert word of choice> to install AppSync would actually read that warning in the README

**Comment by justinoboyle** [comment]
Fair point.

**Comment by timonline** [comment]
yes yes, please close

**Comment by amineangx** [comment]
thank you guys for your help . i will restore my phone and not doing this mistake again.

**Comment by amineangx** [comment]
what should i install instead of appsync, appsync for ios 7+ not working for me

**Comment by justinoboyle** [comment]
@amineangx You should pay for software and support hardworking developers instead.

Also, this issue tracker is specifically about issues with yalu102. You're better off asking that question on [r/jailbreak](https://reddit.com/r/jailbreak).

Please close this issue.

**Comment by 1337jay** [comment]
you should **not** be installing AppSync at all and there is **no** compatible version as of now.

**Comment by timonline** [comment]
@justinoboyle thing is, AppSync can be used outside cracking apps.

**Comment by justinoboyle** [comment]
@timonline I have a strong feeling of what the use case is in this example, and it's not outside cracking apps, lol

**Comment by timonline** [comment]
@justinoboyle true true, hate making assumptions but......yeah you can smell it in this case
