### ISSUE TITLE
Dropbear not working / How to get SFTP

### ISSUE THREAD

**Issue by nerdtron123** [kpwn/yalu102#256]
"Error forking: Operation not permitted"
When I run it as root with "dropbear -FRE"
iPhone 6s TSMC iOS 10.2
Not working...
How can I get SFTP?

**Comment by timonline** [comment]
#162 

Not related to Yalu

**Comment by nerdtron123** [comment]
It is..

**Comment by timonline** [comment]
@nerdtron123 have you taken a look at #74?

**Comment by nerdtron123** [comment]
@timonline please tell me where that shows how to run an SFTP server.
Appearently this error is coming from iOS sandbox.

**Comment by mologie** [comment]
scp works fine if you install scp. scp is not part of dropbear, this is not a bug.

Get scp from, for example, http://newosxbook.com/tools/iOSBinaries.html and install it to /usr/bin.

**Comment by timonline** [comment]
I was hinting to use SCP instead

**Comment by timonline** [comment]
@mologie, *sigh* as i said but @nerdtron123 wouldn't listen that it isn't related to issue in Yalu102

**Comment by warhouse512** [comment]
I really don't want to disturb anyone, but was dropbear removed in the recent beta 3? I can't ssh in (just ssh not sftp or scp). Using Nmap, I can see that my iPhone's port 22 is closed.

**Comment by nerdtron123** [comment]
@warhouse512 in mterminal run "/usr/local/bin/dropbear -FRE" (no quotes) and then connect + tell me output

**Comment by timonline** [comment]
@warhouse512 not that I know of. Try rebooting and re-running Yalu102, worked for me when ssh was blocked

**Comment by nerdtron123** [comment]
@timonline I had two parts to my question. So please be quiet.

**Comment by timonline** [comment]
@nerdtron123 classy.

**Comment by nerdtron123** [comment]
Also I implied I wanted sftp not scp

**Comment by nerdtron123** [comment]
@timonline bye you're irrelevant you can't help me

**Comment by timonline** [comment]
@nerdtron123 no one probably will with that attitude. Psssst this is not a support forum, this space is for issues.

*sigh*

**Comment by warhouse512** [comment]
@timonline @nerdtron123 A reboot fixed it.. Sorry I did not want to cause any issues. Thank you both for the help!

**Comment by timonline** [comment]
@warhouse512 glad your problem was resolved.

I believe this should be closed but let's see what @kpwn thinks

**Comment by keldegar** [comment]
I've also noticed that dropbear stops running after a while. Must be crashing.

**Comment by timonline** [comment]
@keldegar nah, it's by design. (dropbear comes with a default session timeout of 3 consecutive)

See this #217

**Comment by dweinstein** [comment]
here's an `sftp-server` build for you guys fwiw, https://github.com/dweinstein/openssh-ios/releases. works on my device w/ yalu102 when put into `/usr/libexec/sftp-server`

HTH
