### ISSUE TITLE
does not work for ota disable and nonceEnabler

### ISSUE THREAD

**Issue by ichitaso** [kpwn/yalu102#257]
https://twitter.com/ichitaso/status/825870590166781954

**Comment by liudayu** [comment]
For blocking OTA updates: use https://hikay.github.io/app/tvos10.mobileconfig to block it (its tvOS update profile)

**Comment by nicogibbons** [comment]
I think they know.

**Comment by kpwn** [comment]
nonceEnabler is baked in on the last commit. No need to run it separately.
