### ISSUE TITLE
Dropbear not working?

### ISSUE THREAD

**Issue by nerdtron123** [kpwn/yalu102#259]
"Error forking: Operation not permitted"
When I run it as root with "dropbear -FRE"
iPhone 6s TSMC iOS 10.2
Not working...

**Comment by kpwn** [comment]
dropbear is ran from a launchdaemon automatically by yalu. from b4 it only listens on 127.0.0.1

**Comment by nerdtron123** [comment]
How do I SSH over USB?

**Comment by kpwn** [comment]
#162
