### ISSUE TITLE
dropbear disabled over wifi

### ISSUE THREAD

**Issue by osxusr** [kpwn/yalu102#260]
whats the point of ssh via usb? i would like to ssh into my device without the usb, it defeats the whole purpose of ssh

**Comment by kpwn** [comment]
>defeats the whole purpose of ssh
you're tripping

**Comment by timonline** [comment]
#162

**Comment by nicogibbons** [comment]
Let it go @timonline haha, it's already closed.

**Comment by timonline** [comment]
@nicogibbons we commented at the same second :D

**Comment by nicogibbons** [comment]
;o @timonline
