### ISSUE TITLE
Dropbear isn't working

### ISSUE THREAD

**Issue by nerdtron123** [kpwn/yalu102#263]
Whenever I try to connect to Dropbear, it says connection refused from putty. Can someone actually help me? It was working yesterday. I've rebooted many times.

**Comment by felipejfc** [comment]
@nerdtron123 it's now listening @127.0.0.1, which means that you can only connect using a usb connection

**Comment by chaustark** [comment]
Even that. Connect through usb via 127.0.0.1:22 still get refuse

**Comment by kpwn** [comment]
google ios ssh over usb

**Comment by chaustark** [comment]
And beta4 and 5 is quite hard to rejb, need 4-5 times

**Comment by kpwn** [comment]
No changes impacted reliability, and you are off topic, plus not providing logs, firmware version and device model. 

Stay off this repo, I don't have time to handle clueless ppl

**Comment by nicogibbons** [comment]
Well his GitHub picture is Minecraft @kpwn

**Comment by nerdtron123** [comment]
@kpwn logs from where? All I get is "fork: operation not permitted"

**Comment by nerdtron123** [comment]
I'm restoring my device, because you guys are no help and /r/jailbreak is clueless.

**Comment by bobbysn0w** [comment]
@nerdtron1 good, serves you right for completely disregarding #64 and #162

**Comment by nerdtron123** [comment]
@bobbysn0w it's a development device anyways, so...
