### ISSUE TITLE
iPhone 6 10.2 rebooted on beta 5

### ISSUE THREAD

**Issue by iM4CH3T3** [kpwn/yalu102#265]
Just tried to delete the downloaded ota file as my iPhone freezes and rebooted

**Comment by iM4CH3T3** [comment]
{"bug_type":"115","timestamp":"2017-01-30 05:57:22.44 +0100","name":"Reset count","os_version":"iPhone OS 10.2 (14C92)","incident_id":"3160C870-4AFD-4DAD-B8CC-E03BEAD3D8F5"}
Incident Identifier: 3160C870-4AFD-4DAD-B8CC-E03BEAD3D8F5
CrashReporter Key:   853de4af2f2b17c71b562c36dacb31f27a1e52b3
Date: 2017-01-30 05:57:22.38 +0100
Reset count: 0
Boot failure count: 1
Boot faults: wdog
Boot stage: 255
Boot app: 2724057959

**Comment by nicogibbons** [comment]
New commit.

**Comment by kpwn** [comment]
dupe
