### ISSUE TITLE
iPad Air (Wifi) not installing Cydia.

### ISSUE THREAD

**Issue by mspencer92** [kpwn/yalu102#266]
I installed Yalu102b5 on my iPad Air, I ran it the first time and it sat there for 5 minutes and then respringed but there is no Cydia icon. I reopened the Yalu102 app and it says that it is jailbroken. Does anyone know how to fix this problem?

**Comment by timonline** [comment]
see #209

**Comment by nicogibbons** [comment]
Beat me @timonline

**Comment by timonline** [comment]
@nicogibbons muwhahahahaha :)

**Comment by mspencer92** [comment]
Thanks for this, what is the best way to edit that file? I have nothing installed on the iPad that could do it.

**Comment by kpwn** [comment]
Closing since it's solved, you can still comment for further details.
