### ISSUE TITLE
substrate not working at all 

### ISSUE THREAD

**Issue by eriksmets** [kpwn/yalu102#268]
6S+ TSMC, iOS 10.2
Every time I respring, substrate crashes to Safe Mode after unlock.
Afterwards after unlock, Safe Mode crashes to [Dead Mode](https://www.reddit.com/r/jailbreak/comments/1wf5ec/psa_holding_volume_up_while_booting_is_not_safe/cf1gccy/).

I've already tried restoring. Issue started on beta1 and persists in every beta so far (currently beta6).

**Comment by kpwn** [comment]
Safe mode is broken in iOS 10. Some tweak is triggering Safe Mode, and you can't get out of it.
