### ISSUE TITLE
Disable OTA

### ISSUE THREAD

**Issue by SeMoOoR** [kpwn/yalu102#276]
I just noticed that OTA is not disabled. I received a notification to update to 10.2.1, when i went to Settings>General>Software Update, i can see the update is there. I'm using iPhone 6 with yalu102b6 on 10.2

**Comment by OGKevin** [comment]
Delete the downloaded OTA general>Storage>manage storage>delete the OTA

As a short term solution use TvOS profile.

**Comment by jeonghyeonchoe** [comment]
already committed, wait b7.

**Comment by SeMoOoR** [comment]
@OGKevin I did remove the update from Storage. I was wondering if going out of JB state will still have the Launchdaemon working to fetch any updates ?

**Comment by OGKevin** [comment]
Im not sure, i didn't get a chance read how Yalu disables OTA. Will know more when i do.

**Comment by msamuel002** [comment]
@kpwn will you make a b7 dedicated just to fixing the ota update error. or will you push this in with another fix?

**Comment by mailinglists35** [comment]
using b7 I still had the download and install button.
this fixed it for good, forever spinning wheel:

```
launchctl disable system/com.apple.softwareupdateservicesd
launchctl disable system/com.apple.OTATaskingAgent
launchctl disable system/com.apple.mobile.softwareupdated
```


also others say just blocking mesu.apple.com (http://www.richard-purves.com/2016/09/10/apple-services/) is enough https://www.reddit.com/r/jailbreak/comments/5r54yi/tutorial_blocking_ota_updates_without_jailbreak/
