### ISSUE TITLE
Cydia Substrate error

### ISSUE THREAD

**Issue by ahmed422** [kpwn/yalu102#279]
I just jailbreak my iPhone 6 and I've tried to install tweaks and it just shows... Sub-process/usr/libexes/Cydia/cydo and error code (2) .....any Solution Please help me out of this Problem

**Comment by timonline** [comment]
#162 

Not related to Yalu jailbreak

**Comment by OGKevin** [comment]
Try on r/jailbreak

**Comment by ahmed422** [comment]
Okay I believe that but what do you think what it could be ?

**Comment by timonline** [comment]
@kpwn please close

**Comment by aboagzail1** [comment]
Check Storage of Cydia

**Comment by msamuel002** [comment]
This is saurik's job, not luca's. close this
