### ISSUE TITLE
Cydia Impector Stuck on VerifyingApplication.

### ISSUE THREAD

**Issue by ramisali85** [kpwn/yalu102#280]
I have trying to sideload Yalu beta6 on my iPhone 6 iOS 10.2 freshly restored device. Even after 100 times it stuck on same point.

Windows 7 64bit

**Comment by Mila432** [comment]
https://github.com/kpwn/yalu102/issues/64

**Comment by PwnK** [comment]
Please ask for support in r/jailbreak and close this issue.

**Comment by atkr** [comment]
#162
