### ISSUE TITLE
Dropbear not creating keys.

### ISSUE THREAD

**Issue by rudyrolf** [kpwn/yalu102#281]
Having troubles with Dropbear.

After a clean (DFU) restore and jailbreak with B6 or git source, the directory /private/etc/dropbear is empty. 

No keys are created. I have tested it several times and it happens over and over. Used an iPad mini 2. Some people on [r/jailbreak also reported](https://www.reddit.com/r/jailbreak/comments/5qvvej/question_dropbear_ssh_deamon_not_loaded_by/) the same on their iPhone 6S.

I could manually create the keys but that wouldn't fix it fro everybody, just me.

Hope submitting it here will help others.

**Comment by OGKevin** [comment]
This is not a Yalu issue but a dropbear issue. Try asking on one of stack exchange's community's.

I haven't tried making keys w dropbear ill give it a shot tonight.

**Comment by rudyrolf** [comment]
How is this not a Yalu issue? The keys get generated while jailbreaking for pretty much everybody else. Somewhere keys aren't generated when jailbreaking the mini 2. I think it is too easy to blame it on Dropbear. If I manually create the keys it works fine, the problem is that they should've been created during the jailbreak process.

**Comment by nerdtron123** [comment]
Are you using b4-5 those broke ssh for me. Try running /usr/local/bin/dropbear -F -R -E -p 127.0.0.1:22 and then connect. Tell me what it outputs to ur screen

**Comment by OGKevin** [comment]
I don't think u need to specify the IP address it listens to(i might be wrong). However -p is to specific the port it listens to. So I suggest u try without the ip as @nerdtron123 suggested if this doesn't doesn't work, then run it exactly as he has written.

**Comment by kpwn** [comment]
tried sshing in? i believe they are automatically generated on the first connection. anyhow it's working fine over here
