### ISSUE TITLE
pls add sftp support

### ISSUE THREAD

**Issue by 0neday** [kpwn/yalu102#283]
get /usr/libexec/sftp-server from openssh and get /usr/lib/libcrypto.0.9.8.dylib from openssl, and then put them to bootstrap.tar, thx

**Comment by upal212** [comment]
Don't you think it's better to modify the OS just the way you want it to be?
I don't even know why Luca even releases jailbreaks for the dumb ones.

**Comment by 0neday** [comment]
@upal212 Yeah
