### ISSUE TITLE
will it need to be reinstalled after 7 day?

### ISSUE THREAD

**Issue by mrsiu** [kpwn/yalu102#284]
will it need to be reinstalled after 7 day?

**Comment by upal212** [comment]
If you do not own a developers account then yes.

**Comment by mrsiu** [comment]
why does pangu's jailbreak not need to?

**Comment by upal212** [comment]
Bc it's signed by the devs already.
And people don't see the point by wasting their precious time by signing over beta's.

**Comment by mrsiu** [comment]
will yalu102 sign this too after the release version?

**Comment by upal212** [comment]
It should. Now we are not prophets who can predict the future.
But there are always other signing providers available.

**Comment by mrsiu** [comment]
can u give me an email ,so i can contect u?

**Comment by Mila432** [comment]
https://github.com/kpwn/yalu102/issues/64

**Comment by OGKevin** [comment]
#162

**Comment by TheMerkyShadow** [comment]
http://udidregistrations.com

**Comment by nathanaccidentally** [comment]
This isn't _code_ related.
