### ISSUE TITLE
erase all data after using yalu102 jb

### ISSUE THREAD

**Issue by 0neday** [kpwn/yalu102#286]
After erase all date, I got " PAM Model 104 error " when I open MTerminal and got mobilesubstrate work failed. I'm  surprised why MTerminal doesn't work.

**Comment by 0neday** [comment]
edit: I reinstall yalu102 and rerun it after erasing all data

**Comment by OGKevin** [comment]
U just posted this on reddit there is no need to post it here aswell.

**Comment by 0neday** [comment]
Maybe you're right, thx

**Comment by OGKevin** [comment]
Please close this issue for now.
