### ISSUE TITLE
Cydia Error Message Could not Open file...

### ISSUE THREAD

**Issue by xXDjMikeXx** [kpwn/yalu102#287]
Could not open file var/lib/dpkg/status - open(2 No such file or direction)

The package list or status file could not be parsed or opend

What I have to do? 
No packages
Tried rebooting
iPhone 6 Plus iOS 10.2
Yalu beta6

**Comment by timonline** [comment]
#64 
#162 

Plus google is your friend (first result)

https://www.cydiageeks.com/fix-not-open-varlibdpkgstatus-ios-9-3-3.html

**Comment by xXDjMikeXx** [comment]
Thanks for your help I will try this :)

**Comment by xXDjMikeXx** [comment]
I am sorry but there could be a easier way sorry

**Comment by Mila432** [comment]
ye restore to 10.2.1 problem solved

**Comment by timonline** [comment]
@Mila432 i see what you did there

**Comment by xXDjMikeXx** [comment]
When I open mTerminal it say not allowed to fork inside Sanbox and the it exit

**Comment by xXDjMikeXx** [comment]
Please help

**Comment by xXDjMikeXx** [comment]
:/
