### ISSUE TITLE
Error Running Debian Packager

### ISSUE THREAD

**Issue by whoscreare** [kpwn/yalu102#288]
When attempting to install anything from Cydia, in this case a simple icon pack for a repo, it would download it but when the Debian Packager would begin, I would get this error:

Sub-Process /usr/libexec/cydia/cydo returned an error code (2)

iPhone 6+
iOS 10.2
Yalu Beta 3

**Comment by whoscreare** [comment]
Update: I ended up searching the error code and it seems as though iFile is needed to fix it but seeing as I am unable to install anything ATM, I'm stuck.

**Comment by OGKevin** [comment]
Can u SSH ?

**Comment by whoscreare** [comment]
Without installing any necessary files from Cydia that would allow that, no I don't think so.

**Comment by OGKevin** [comment]
U dont need to install anything to use SSH.

**Comment by Rikifire** [comment]
SSH via USB is possible by default.

**Comment by OGKevin** [comment]
I recommend u di your research on how to SSH on to your phone and continue from there .

**Comment by whoscreare** [comment]
Alright. Will update after.

**Comment by Rikifire** [comment]
Just follow this 

http://iphonedevwiki.net/index.php/SSH_Over_USB

**Comment by whoscreare** [comment]
It's just not allowing me to make any changes.

**Comment by whoscreare** [comment]
Would reinstalling the jailbreak help?

**Comment by atkr** [comment]
#162

**Comment by Rikifire** [comment]
Have you connected your device via SSH?
