### ISSUE TITLE
Safari reload issue is back

### ISSUE THREAD

**Issue by jyotisoumensaha** [kpwn/yalu102#297]
Safari reload issue that came with Pangu 9.3.3 jb, is happening with Yalu102. Please fix this Luca.

**Comment by eXhumer1149** [comment]
#162 #64

**Comment by tangalbert919** [comment]
@eXhumer1149, it helps to add a message so @jyotisoumensaha knows why you would reference this issues.
Also, to @jyotosoumensaha: This is not a code-related issue. Check Reddit for help. Read the README on this repository before you make another issue. Please close this issue.

**Comment by tangalbert919** [comment]
EDIT: THESE issues, not this. I can't do actual editting because this is coming from a mobile phone, so...
