### ISSUE TITLE
Since you released incomplete source, would it be against EULA to open this and learn a little?

### ISSUE THREAD

**Issue by rpalmieri99** [kpwn/yalu102#3]
With the current status of the jailbreak community going to an absolute pile of garbage, would it be ok if I opened the source to learn a little about how the jailbreak works?

Thanks and with much respect,

rpalmieri

**Comment by NotAlexNoyle** [comment]
It's open-source. That's the point... so yeah.

**Comment by kpwn** [comment]
this is WTFPL, you are encouraged to do anything with this.
