### ISSUE TITLE
not an issue but question

### ISSUE THREAD

**Issue by Matoo69** [kpwn/yalu102#300]
i must re-jailbreak my phone every 7days or??

**Comment by mologie** [comment]
No, unless you restart it. #162

**Comment by Matoo69** [comment]
noo i didnt meen that,i know that becose is semi-unthedeard (sorry for my bad english i am from croatia)
i ask this becose itwe4kz say you must re-jailbreak you idevice evey 7days now i asking you people if this is true??

**Comment by MelkyPie** [comment]
#162

**Comment by OGKevin** [comment]
U must reload the ipa on to your device every 7 days. However if you are in jb mode and 7 days has past, Nothing bad will happen until you reboot. Look on r/jailbreak for more info #162

**Comment by Matoo69** [comment]
will this be fix??

**Comment by Aaahh** [comment]
No
Close issue please
