### ISSUE TITLE
HUGE PROBLEM

### ISSUE THREAD

**Issue by natezoom** [kpwn/yalu102#303]
OK so I have a huge problem iphone 7 is not supported lol jk.
Ok real problem, there is no where to donate to such a wonderful and dedicated man.

**Comment by eXhumer1149** [comment]
Not code related #162 #64

**Comment by nerdtron123** [comment]
Donate to a charity of your choice.

**Comment by nerdtron123** [comment]
Close this please

**Comment by tjsreece** [comment]
Whoa there guys, @natezoom wants to donate to @kpwn and not a charity.
