### ISSUE TITLE
HUGE HUGE PROBLEM

### ISSUE THREAD

**Issue by natezoom** [kpwn/yalu102#304]
@kpwn I have 100 dollars with your name on it help where do I send it???

**Comment by kpwn** [comment]
pick a charity of your choice and donate in my name if you wish!

**Comment by kpwn** [comment]
bitcoin I'll take: 1CwMpxv4Afpbwf4C3ccXVgReTFnCuNeD8a

**Comment by KILLCAMPER** [comment]
😉😉👍

**Comment by tjsreece** [comment]
Oh in that case I have some that I should throw your way at some point!
