### ISSUE TITLE
Mobile data not working

### ISSUE THREAD

**Issue by JoaoPadilha** [kpwn/yalu102#305]
I don't know if this is yalu related or not, but if its not then plz close this issue.

After a day with jailbreak my i6 ended up with no mobile data connection.
At first I thought that resetting network settings would work. It didn't.
I then tried the following chmod commands also with no efect:
chmod 777 /var 
chmod 777 /var/mobile 
chmod 777 /var/mobile/Library 
chmod 777 /var/mobile/Library/Preferences

Before restoring my device, do you have any idea about what may have done this?  Thanks.

**Comment by kpwn** [comment]
i do not believe this is yalu related. closing, but if you have any interesting crashlog, feel free to comment again

**Comment by JoaoPadilha** [comment]
Sorry, where should I look for the crashlog related to this mobile data problem?

Thank you once again.

**Comment by JoaoPadilha** [comment]
Well... Decided to do a restore from an iCloud backup and it didn't fix it. 
Ended up doing a complete restore and it solved the issue.
:|
