### ISSUE TITLE
Cydia home page not opening 

### ISSUE THREAD

**Issue by adi2k17** [kpwn/yalu102#307]
When I tap something on a home page of cydia it won't open HELP

**Comment by msamuel002** [comment]
what devcice

**Comment by adi2k17** [comment]
iphone 5s

**Comment by msamuel002** [comment]
ok and what do you tap on and what doesnt open?

**Comment by msamuel002** [comment]
do you tap on the cydia icon and it doesnt open?

**Comment by adi2k17** [comment]
Noo wait let me tell you

**Comment by msamuel002** [comment]
if it crashes, paste your crash logs at pastebin.com so luca could know what is wrong.

**Comment by adi2k17** [comment]
You know when you open you open to the cydia welcome page

**Comment by msamuel002** [comment]
yea, then what

**Comment by adi2k17** [comment]
and you scroll down and see user guide and other stuff

**Comment by adi2k17** [comment]
and when*

**Comment by adi2k17** [comment]
right

**Comment by msamuel002** [comment]
yea

**Comment by redpr1sm** [comment]
not related to jailbreak code. stop asking about cydia issues here. #162

**Comment by msamuel002** [comment]
lol
