### ISSUE TITLE
installation.cpp:42 

### ISSUE THREAD

**Issue by ryderrr** [kpwn/yalu102#308]
I'm on iOS 10.2 on my iPhone 5s and it keeps giving me this error every time it i try and install yalu with cydia impactor. 

failed to verify code signature of /private/var/Library/Caches/com.apple.mobile.installd.staging/temp.vECWd8/extracted/Payload/yalu102.app : 0xe8008018 (the identity used to sign the executable is no longer valid)

**Comment by msamuel002** [comment]
not related to yalu...close it @kpwn
