### ISSUE TITLE
beta 7 - ipad mini 4 wifi

### ISSUE THREAD

**Issue by keiskodeniz** [kpwn/yalu102#309]
I have tried several times with different apple ids.. but beta 7 on ipad mini 4 doesn't work.. just restarting after a few secnds or minutes than nothing happens..

version 10.2
Never jailbreaked before.

**Comment by iOS4all** [comment]
@keiskodeniz me too I have this exact issue on my wifi iPad Air 2 on iOS 10.2

**Comment by 1337jay** [comment]
You will have to try more times, it worked for me after 22 tries on an Air 2 WiFi 10.2.

**Comment by msamuel002** [comment]
dang, that sucks

**Comment by keiskodeniz** [comment]
22 tried, are you kidding lol ?

**Comment by 1337jay** [comment]
@keiskodeniz not kidding, lol. @msamuel002 hopefully it gets better in the final version, this is the first supported beta for these two devices.

**Comment by nicogibbons** [comment]
worked first try for me. You can close this

**Comment by keiskodeniz** [comment]
how did you count it lol..

**Comment by kpwn** [comment]
i am puzzled that this is happening, and will try to improve reliability.

**Comment by nicogibbons** [comment]
My screen goes all funny and has these white lines everywhere when it sometimes fails. I think it's text but it's way to small to read @kpwn

**Comment by keiskodeniz** [comment]
@nicogibbons mee too.. and sometimes it says failed, retry.. once I click, my device restarting with apple logo immediately.

**Comment by nicogibbons** [comment]
12th time worked a charm for me :).

**Comment by keiskodeniz** [comment]
i didnt count it lol but just pressed on go again.. i think maybe 12-13 in a row.

**Comment by keiskodeniz** [comment]
now i see white screen before my device restart and apple logo appears.

**Comment by nicogibbons** [comment]
lmao

**Comment by nicogibbons** [comment]
it always eventually works

**Comment by keiskodeniz** [comment]
worked after 30 tries loool..

**Comment by keiskodeniz** [comment]
after 5 minutes restarted it self :(

**Comment by iOS4all** [comment]
It works with me after 6 times

**Comment by sehlio** [comment]
Yeah this sucks on ipad mini 4

**Comment by sehlio** [comment]
On ipad mini 4 it does keep rebooting without installing cydia so i put my ipad on the wall charging and it does finally install cydia hoping the next beta or the final release will be more stable on ipad mini 4 and install cydia from the first time

**Comment by ghost** [comment]
Before jailbreaking: Put iPad in airplane mode, then restart. Open Yalu, wait 10 seconds, then hold the go button for 5-7 seconds. All of these can raise your chance of successfully jailbreaking.

**Comment by keiskodeniz** [comment]
We can jailbreak but the problem is it isnt stable!!

**Comment by ghost** [comment]
Yeah, I did see that some people were having trouble getting it to jailbreak as well, that's why I commented that.

**Comment by KILLCAMPER** [comment]
For sum random thing I have I pad Air 2 after the 7days ran out so deleted the app and reinstalled with inpact now jb 1st time every time and no reboots

**Comment by ghost** [comment]
Wow, lucky
