### ISSUE TITLE
'libkern/OSReturn.h' file not found

### ISSUE THREAD

**Issue by Urboi** [kpwn/yalu102#31]
Trying to compile ( Error Message: 'libkern/OSReturn.h' file not found) idk whats happening because i added header and put everything in right places so it shouldn't be saying that??? Im obviously doing something wrong. I am trying to use an old device to just test it out and get a feel for a jailbreak so

**Comment by CrypticGit** [comment]
figure it out if you dont know how to fix it theres no reason you should be trying to compile open source https://github.com/obaby/IOKit @Urboi
