### ISSUE TITLE
Pesonal hotspot broken

### ISSUE THREAD

**Issue by ahjek** [kpwn/yalu102#315]
On 6+ with beta 6 the personal hotspot is broken and SSID is continuing broadcast and can't get contented with other devices. Reboot to non-jalbroke mode worked.

**Comment by ahjek** [comment]
I mean the SSID is still broadcasting even the hotspot was turned off.

**Comment by juandiii** [comment]
Yes, it happens to me. I think be forgot activate hotspot daemon

**Comment by bobbysn0w** [comment]
In #226 the /LauncDaemons were unloaded and loaded so that includes the MobileInternetSharing daemons. Not sure why this is broken...

**Comment by ReddestDream** [comment]
Odd. Personal Hotspot works for me on iPad Pro with beta 7 on 10.2.

**Comment by juandiii** [comment]
Personal Hotspot not working in iPhone 6s Plus Beta 7 on 10.2

**Comment by bobbysn0w** [comment]
#323 might not be needed though because people report it works. Probably just a personal bug for you guys.

**Comment by ahjek** [comment]
After leaving it for few hours surprisingly it does get connected, but something is not right. 

Tried on both 5S and iPad mini, it does connected to my 6+ but there are no data activities going on. 

I do not have any tweaks installed on my 6+

**Comment by onchehuh** [comment]
Same here.
Computer joins wifi but no data

**Comment by ReddestDream** [comment]
@bobbysn0w Might be I'm on a Cellular iPad, not an iPhone . . .

**Comment by justinoboyle** [comment]
Please check if you are still having problems with the latest beta. If no, please close the issue :)

**Comment by kpwn** [comment]
Closing due to no answer (cleaning issues up), please follow up with latest beta
