### ISSUE TITLE
Showing Update on Beta 7

### ISSUE THREAD

**Issue by cdecker15** [kpwn/yalu102#318]
I am still seeing a notification that there is an update available, not on the settings app itself, but next to General from within the settings app, then if you continue to go to the update section, I am able to see 10.2.1.

**Comment by DarknesGaming** [comment]
That's not good. I guess unlinking the file that makes the update thing work isn't enough.

**Comment by msamuel002** [comment]
even with beta7 of yalu?

**Comment by tsuehpsyde** [comment]
Same, beta 7 here as well. Update is still showing.

**Comment by GR3YH4TT3R** [comment]
Try deleting the update settings>general>storage&icloud usage>Storage>iOS update or download the tvOS beta profile and install it on your iPhone itll block any iOS updates

**Comment by msamuel002** [comment]
@kpwn i thought you found a definite fix to this?

**Comment by cdecker15** [comment]
@GR3YH4TT3R Ive already deleted the update, it still shows up. Installing the TV profile would solve the issue, however, the jailbreak should disable them automatically to prevent "accidents/stupidity".

**Comment by DarknesGaming** [comment]
We should've went with that pull request that involved renaming the file. The device can't create a new one, can it?

**Comment by DarknesGaming** [comment]
My phone suddenly rebooted. I used beta 7 and it took 2 tries for it to work.
**it's just like Pangu 1.1 sometimes, and they said it's stable.**

**Comment by cdecker15** [comment]
@DarknesGaming I'm not sure, I'd have to check tomorrow. I would imagine it does, not sure.

**Comment by DarknesGaming** [comment]
I can't stand the iOS 10.2.1 update. Also, Apple stopped signing iOS 10.2, so for once, I don't regret saving SHSH blobs this time.

**Comment by maetrik92** [comment]
Guys,I am on 10.1.1 on ip7+ have Yalu b3 on and mikoto.i disabled updates on mikoto and I don't hav a single update window.did anyone try this?

**Comment by mwoolweaver** [comment]
If yalu102 doesn't disable OTA updates plz try this 

https://twitter.com/IvanoBilenchi/status/826346214199324672

**Comment by kpwn** [comment]
this is normal: it doesn't remove the ota update, just blocks installation and downloading

**Comment by mailinglists35** [comment]
>If yalu102 doesn't disable OTA updates plz try this
>
>https://twitter.com/IvanoBilenchi/status/826346214199324672

I tried that and it didn't work. 

instead this is the cleanest method without touching any binary or permissions. no need for complicated way via filza method as described in above tweet.

```
V:/Applications/iCleaner.app root# launchctl disable system/com.apple.softwareupdateservicesd
V:/Applications/iCleaner.app root# launchctl disable system/com.apple.OTATaskingAgent
V:/Applications/iCleaner.app root# launchctl disable system/com.apple.mobile.softwareupdated
V:/Applications/iCleaner.app root# launchctl print-disabled | egrep -i 'ota|update'
        "com.apple.OTATaskingAgent" => true
        "com.apple.mobile.softwareupdated" => true
        "com.apple.softwareupdateservicesd" => true
```

this gives the forever spinning wheel on general > software update but i still don't get rid of the notification


also others say just blocking mesu.apple.com (http://www.richard-purves.com/2016/09/10/apple-services/) is enough https://www.reddit.com/r/jailbreak/comments/5r54yi/tutorial_blocking_ota_updates_without_jailbreak/
