### ISSUE TITLE
Some of the App Store app are crashing every 

### ISSUE THREAD

**Issue by patrickawsomeness1** [kpwn/yalu102#319]
Every time you want to go on musical.ly or other app it just crashes

**Comment by At0m0s** [comment]
That's probably not a problem with the jailbreak.  Just the apps jailbreak detection.  Go get xCon or similar.

**Comment by bobbysn0w** [comment]
#162

**Comment by RajPatel0929** [comment]
same happening to me... snapchat and spotify keep making it crashes
