### ISSUE TITLE
I have iPad Air 2 Wi-Fi 10.2 Offsets

### ISSUE THREAD

**Issue by nicogibbons** [kpwn/yalu102#32]
_allproc: 0x5b8528
_kernproc: 0x5be0e0
fffffff0075c20b8 S _rootvnode
fffffff0071e1258 S _vfs_rootvnode

**Comment by drake90001** [comment]
can you post kernel version from console output?

**Comment by nicogibbons** [comment]
Eh sorry I'm off my computer now, is it needed?

**Comment by drake90001** [comment]
for differentiation of devices, so yes, but no rush since it's unsupported atm

**Comment by nicogibbons** [comment]
Could you convert these 
fffffff0075c20b8 S _rootvnode
fffffff0071e1258 S _vfs_rootvnode
Into the correct format for me too use?

**Comment by drake90001** [comment]
rootvnode is 0x5be0b8

**Comment by nicogibbons** [comment]
Also it didn't print me off a kernel version

**Comment by drake90001** [comment]
it should, when you compile the app and it runs on your device, watch the console output in Xcode

**Comment by nicogibbons** [comment]
Oh kk

**Comment by B0ngL0rd** [comment]
sysname: Darwin
nodename: iPhone
release: 16.3.0
version: Darwin Kernel Version 16.3.0: Tue Nov 29 21:40:08 PST 2016; root:xnu-3789.32.1~4/RELEASE_ARM64_T8010
machine: iPhone9,4
missing offset, prob crashing
2017-01-26 14:20:23.272130 yalu102[230:7770] found corruption 38503

**Comment by B0ngL0rd** [comment]
Any use

**Comment by drake90001** [comment]
not for this issue, sorry

**Comment by nicogibbons** [comment]
@drake90001 how do I show console output on Xcode when I run the app?

**Comment by drake90001** [comment]
it should show automatically when you compile it, then hit go on the app. it'll start printing text in xcode, at the top is kernel version:

**Comment by nicogibbons** [comment]
Here you go @drake90001 
sysname: Darwin
nodename: iPad
release: 16.3.0
version: Darwin Kernel Version 16.3.0: Tue Nov 29 21:40:09 PST 2016; root:xnu-3789.32.1~4/RELEASE_ARM64_T7001
machine: iPad5,3
missing offset, prob crashing

**Comment by drake90001** [comment]
Woooo, thank you.

**Comment by nicogibbons** [comment]
;) anytime

**Comment by nicogibbons** [comment]
if you add it to your fork I can test @drake90001

**Comment by drake90001** [comment]
@nicogibbons it wont work atm, luca needs to add 4k device support

**Comment by nicogibbons** [comment]
What's the difference with a 4k device?

**Comment by nicogibbons** [comment]
@drake90001 Also how did you get 0x5be0b8 from 
fffffff0075c20b8 S _rootvnode
fffffff0071e1258 S _vfs_rootvnode

**Comment by drake90001** [comment]
@nicogibbons you have to subtract the header from it to get the correct offset

**Comment by DarknesGaming** [comment]
What exactly is the header? Is it without the hexadecimal without "fffffff00"?
