### ISSUE TITLE
Apple Stooped Signing 10.2

### ISSUE THREAD

**Issue by zencowboy007** [kpwn/yalu102#324]
Shite!!  Could not get the file downloaded for iphone 6s+ and installed in time...only a few minutes behind as was busy with work.  Well, got the 9.33 JB back working and sooooo happy.  

Just got iPad Air 2 working with cydia...a guy (I'll find name in sec, said hold on the Go button...did that for about 10 seconds then let up, it took about 20-30 seconds and did the first circle dot dot dot and rebooted and Bam, Cydia app there!!)

**Comment by tsuehpsyde** [comment]
#162

**Comment by justinoboyle** [comment]
Unrelated. Please close.
