### ISSUE TITLE
iphone 6s cydia removed after restart

### ISSUE THREAD

**Issue by mohammadabumoosa** [kpwn/yalu102#328]
after restarting my iPhone 6s cydia disappeared when i try to Rejailbreak it fails there is no installed tweak

**Comment by joshmedia2016** [comment]
you have to    rejailbreak with yalu    if you restart your phone  as its  semi  jailbreak  like  pangu  one you gotta patch  Kernal with app

**Comment by atkr** [comment]
#162 
This is not an issue with the jailbreak but rather with you not understanding how it works.  Please consult r/Jailbreak on reddit.

**Comment by mohammadabumoosa** [comment]
you cant understand what i wrote
isaid that even if i Rejailbreak cydia doesn't appear

**Comment by mohammadabumoosa** [comment]
iam a developer not normal user

**Comment by timonline** [comment]
Hey @mohammadabumoosa, close this issue and contact me on admin@timourrashed.com. I may be able to help you.
