### ISSUE TITLE
iPhone 5S Offset

### ISSUE THREAD

**Issue by Slonick** [kpwn/yalu102#33]
allproc_offset = 0x5b20e0;
rootvnode_offset = 0x5b20b8;
Darwin Kernel Version 16.3.0: Tue Nov 29 21:40:09 PST 2016; root:xnu-3789.32.1~4/RELEASE_ARM64_S5L8960X

**Comment by drake90001** [comment]
thank you

**Comment by Cydios** [comment]
thx

**Comment by timonline** [comment]
@slonick, didn't work for me
