### ISSUE TITLE
Reveal Menu not working in 102 JB

### ISSUE THREAD

**Issue by angelo1979** [kpwn/yalu102#330]
When I installed Reveal Menu and clicked restart springboard in Curia when I installed it so the springboard restarted and when I unlocked the screen my wallpaper was gray instead of normal wallpaper so it restarted the device but now reveal Menu and power tap does not work after the random springboard restart could you fix this issue

**Comment by angelo1979** [comment]
And I'm running on iPod 6G

**Comment by harshevil** [comment]
Please don't post such stuff here, go to reddit.com/r/jailbreak

**Comment by tjsreece** [comment]
No @angelo1979 we cannot fix your issue as it is a problem with the Cydia package and not Yalu. Please close this issue.

**Comment by eXhumer1149** [comment]
#162 #64

**Comment by RajPatel0929** [comment]
lol this need to be updated by dev of the tweak not here

**Comment by Oakman978** [comment]
I think you downloaded an impatable tweak and your iPod went into safe mode. You should go into Cydia and uninstall reveal menu and it should work fine after. In the future it is bettering to post these on jailbreak reddit instead of here

**Comment by angelo1979** [comment]
I'm closing this right now
