### ISSUE TITLE
Issue with Boom Beach game

### ISSUE THREAD

**Issue by nguyenduongngoc** [kpwn/yalu102#332]
Hello, I am new to jailbreaking. And today, when I try installing beta7 of yalu, I get problem with boom beach game. For sometimes attacking, the device auto reboot. As I mention above, I am new to jb. Should anyone tell me what I can do to give logs to you? 
I didn't encounter this before I jb the device :)
My device is iphone 6, running ios 10.2 
Thanks and regards

**Comment by maetrik92** [comment]
Lol.this is the best thread here and deserves to stay open! 😂😂😂

**Comment by OGKevin** [comment]
....... #162

**Comment by tjsreece** [comment]
@nguyenduongngoc Please close this issue, we cannot help you.
