### ISSUE TITLE
Cydia is not 64bit

### ISSUE THREAD

**Issue by LastPust** [kpwn/yalu102#336]
hi cydia was not 64bit version at my iphone 6s plus... it was 32 bit.

and after installing 2-3 tweaks.. when it respring: cydia, settings, phone, sms, and so much more apps and home dock was deleted (not icons vanished it was like completely deleted)

for example phone app was gone and when someone called me there was nothing on phone...

and when will stable build will come out?

**Comment by OGKevin** [comment]
I do not mot think this has anything to do with yalu but with cydia. Saurik is working on updating cydia. Ur better off asking this question in r/jailbreak #162

**Comment by LastPust** [comment]
but cydia is updated daily  http://apt.saurik.com/beta/cydia-arm64/

yalu app is the one installs cydia for the first time? so yalu app is need to be updated right? idk

**Comment by Mila432** [comment]
https://github.com/kpwn/yalu102/issues/64

**Comment by OGKevin** [comment]
U update cydia from within cydia.

**Comment by pbrocker** [comment]
@LastPust: Cydia 64-bit is still in beta. When 64 bit is stable and ready it will be release for cydia. And the correct debian packages can be added to yalu. until then 32-bit is the default stable.

**Comment by OGKevin** [comment]
Can u close this issue please @LastPust
