### ISSUE TITLE
failed,retry

### ISSUE THREAD

**Issue by Uni9k** [kpwn/yalu102#34]
before used yalu b3,now use yalu102,show "failed,retry"
iPhone 7 iOS10.1.1

**Comment by B0ngL0rd** [comment]
sysname: Darwin
nodename: iPhone
release: 16.3.0
version: Darwin Kernel Version 16.3.0: Tue Nov 29 21:40:08 PST 2016; root:xnu-3789.32.1~4/RELEASE_ARM64_T8010
machine: iPhone9,4
missing offset, prob crashing
2017-01-26 14:20:23.272130 yalu102[230:7770] found corruption 38503

**Comment by Skiddi3** [comment]
@B0ngL0rd  There are no offsets for your device yet.

**Comment by imterryt** [comment]
But this also happens to me on my iPhone 6S Plus
