### ISSUE TITLE
iphone 6s yalu crash

### ISSUE THREAD

**Issue by skimaskngun** [kpwn/yalu102#342]
beta7 was strong all night, today random reboots while jailbroken seems while on twitter, no new tweaks at all, trying to rejailbreak with yalu just keeps saying failed try again, then crashes to reboot. went from working first time clicking go to crashing everytime.

**Comment by skimaskngun** [comment]
worked after 5 attempts, may wanna delete this, not sure if it was worth me bringing up or not im aware this is still beta, sorry if any time was wasted lol

**Comment by iM4CH3T3** [comment]
Same for me. Yesterday stable and today randomly freezes and reboots right after.
![](http://i.imgur.com/g7THvo4.jpg)

![](http://i.imgur.com/MIr6DFa.jpg)

**Comment by skimaskngun** [comment]
what are you using to record logs?

**Comment by iM4CH3T3** [comment]
IPhone 6 by the way. 
When go to "Storage- & iCloud Usage"
then also freezing and rebooting right after.

**Comment by dr016** [comment]
beta7 was strong all night, today random reboots while jailbroken seems while on twitter, no new tweaks at all, trying to rejailbreak with yalu just keeps saying failed try again, then crashes to reboot. went from working first time clicking go to crashing everytime
iphone 5s 32gb A1453

**Comment by XeNoW** [comment]
Could be related to what I reported for issue #343 (https://github.com/kpwn/yalu102/issues/343)

**Comment by kpwn** [comment]
looks like a watchdog kill, it should have nothing to do with yalu unless you see a panic
