### ISSUE TITLE
Yalu102 all beta 

### ISSUE THREAD

**Issue by modz2014** [kpwn/yalu102#346]
Hi tfp0 isn't enabled or it doesn't work I can not use any binary like nonceEnabler or kernel dumping or patching because there is no tfp0 enable

**Comment by nerdtron123** [comment]
are you on root access? and nonceenabler is already enabled on the jailbreak tool

**Comment by modz2014** [comment]
Of course you can't use tfp0 doesn't allow kernel task faild

**Comment by modz2014** [comment]
I found a fix for it

**Comment by turingsecurity** [comment]
What was the fix?
