### ISSUE TITLE
Save Dropbear configuration

### ISSUE THREAD

**Issue by jonisc** [kpwn/yalu102#348]
Since yalu102 is rewriting the Dropbear configuration every time would it be possible to add a switch in Yalu that doesn't rewrite the .plist (I don't want Dropbear listening only on localhost)
See: http://reddit.com/r/jailbreak/comments/5qyils/question_dropbear_daemon_not_running/dd3wfoy

**Comment by 0neday** [comment]
just comment dropbear related code in jailbreak.m

**Comment by modz2014** [comment]
That makes no sense

**Comment by jonisc** [comment]
Thanks.
