### ISSUE TITLE
NonceEnabler doesn't work with any iOS 10

### ISSUE THREAD

**Issue by modz2014** [kpwn/yalu102#350]
nonceEnabler doesn't work at any of the iOS 10 jailbreaks i have been trying kernel base fails is the error

**Comment by nicogibbons** [comment]
It is already enabled. All you should have to do is write generator to nvram. I've restored to 10.2 after a bootloop with nonceenabler

**Comment by modz2014** [comment]
nope can't write generator to nvram i get this error, error setting variable  (iokit/common) general

**Comment by modz2014** [comment]
i fix the problem so i wrote my generated to nvram but when trying to downgrade it doesn't do anything just reboot and reboot waiting been like this for 2 hours

**Comment by modz2014** [comment]
now i get --boardconfig how to fix this to get latest futurestore i get Xcode project
