### ISSUE TITLE
Cydia Crashing but tweaks working

### ISSUE THREAD

**Issue by EdoEdii** [kpwn/yalu102#353]
My yalu102 app is working but cydia continues to crash

**Comment by Mila432** [comment]
https://github.com/kpwn/yalu102/issues/64

**Comment by EdoEdii** [comment]
yes its a 64 bit

**Comment by EdoEdii** [comment]
its an iphone 6S

**Comment by timonline** [comment]
#64: "Stop asking for support here"

**Comment by EdoEdii** [comment]
why
this is a server problem

**Comment by timonline** [comment]
@EdoEdii because if the tweaks are working then jailbreak was successful.

If cydia is crashing that's a problem Saurik or yourself should fix.

How about you close this issue and contact me via email at admin@timourrashed.com, can help you there

**Comment by EdoEdii** [comment]
ok

**Comment by EdoEdii** [comment]
done
