### ISSUE TITLE
Thread:Yalu IPA For all Ios Beta updates till 10.2/Fix(Cydia Not Appearing)

### ISSUE THREAD

**Issue by karandeepdps** [kpwn/yalu102#354]
Please post all the compiled ipa with build number to this thread.

**Comment by karandeepdps** [comment]
For ios 10.2 beta 2 and beta 3
https://drive.google.com/file/d/0Bw-eKoFAPzPqVURrMENBX2ZTU1U/view?usp=sharing

@jtv7

**Comment by Aaahh** [comment]
Or post last commit pulled in

**Comment by kpwn** [comment]
what

**Comment by tjsreece** [comment]
@kpwn There was this stupid idea that started here where people wanted include the offsets of all 10.2 betas in the offsets.c file
