### ISSUE TITLE
hmm.. i just get more and more errors ( iphone 6s ios 10.2)

### ISSUE THREAD

**Issue by steph-2w** [kpwn/yalu102#36]
![screen shot 2017-01-26 at 12 35 07 am](https://cloud.githubusercontent.com/assets/25360460/22321074/d20d82ae-e35f-11e6-8288-94fcb434d888.png)

**Comment by DarknesGaming** [comment]
First off, you need to sign that product. An Apple Developer account is required to do that.

**Comment by Skiddi3** [comment]
God now I understand why he hates the community.

If you can't solve this problem please don't try and jailbreak. Just wait for the full release.

**Comment by r4m1live** [comment]
No architectures to compile for (ONLY_ACTIVE_ARCH=YES, active arch=arm64, VALID_ARCHS=armv7).

**Comment by DarknesGaming** [comment]
Chances are you're trying to run this on a simulator. That's not going to work.
You need to be compiling AND running that on a physical device made by Apple's cold, Chinese hands (no offense, China).
