### ISSUE TITLE
Random reboots - iPad Air 2 - Beta 7

### ISSUE THREAD

**Issue by jakeajames** [kpwn/yalu102#363]
I have been experiencing random reboots on my iPad Air 2. Known issue or just my iPad?

**Comment by atkr** [comment]
Mine has never rebooted randomly, been jailbroken since beta 7 was released.
I have not installed any packages yet (it's actually my wife's iPad Air 2).

**Comment by virginsince1997** [comment]
really? only post code problems related to Yalu

**Comment by jakeajames** [comment]
@virginsince1997 I think this is an issue with Yalu

**Comment by jackb992** [comment]
I've been getting this on iPad Mini 4

**Comment by MDallak** [comment]
need install Cydia 1.1.28~b9

**Comment by jackb992** [comment]
as it happened on mine as well (iPad Mini 4) and iPad Air 2. It probably has something to do with the recent support and btw it shouldn't be the cydia (I already have it installed)

**Comment by atkr** [comment]
it could very well be any of the tweaks you have running.  Like I said in my earlier post, my ipad air 2 has been running in a jailbroken state for a few days now and has never randomly rebooted.  How about you try uninstalling all the tweaks you have installed (ie the state where you are jailbroken but have never installed any package) and see what happens?  Otherwise, how can you prove this is yalu related?

**Comment by jackb992** [comment]
@atkr fair enough, @jakeajames could you post a tweak list on your iPad and I'll see if I got anything the same.

**Comment by kremedved** [comment]
I have the same issues on mini 4:

1) random reboots
2) can't rejailbreak quickly - sometimes it takes 30-40 tries

My log: http://pastebin.com/tKwkJLi5
If I can help - let me know.

**Comment by jakeajames** [comment]
All of these + Sleek'n'Bounce
![img_1053](https://cloud.githubusercontent.com/assets/20666361/22527345/22c428a0-e8cf-11e6-8635-0d6f9cde2dae.PNG)

**Comment by jakeajames** [comment]
Apparently this happens sometimes when browsing through Safari.  @kremedved I also have to try a lot of times to rejailbreak

**Comment by atkr** [comment]
Asking for help, but shamelessly showing you like to steal, lol.

**Comment by jackb992** [comment]
@jakeajames I've got two of the same tweaks the most recent of the two would of been power tap (I also had some issues with this tweak earlier), I'm gonna remove to see if it effects anything

**Comment by medipadx** [comment]
Same problem on my ipad air 2, 9 times out of 10 while browsing the web on safari 
I only have 3 Tweaks : wgradremover transparentdock batterylife 
I m going to remove all 3 and see if the problem persist

**Comment by AdibSadman** [comment]
My iPad Air 2 randomly reboots but I don't have tweaks installed

**Comment by DontAskMeIt** [comment]
Same thing but with my IPhone 6

**Comment by ahmedgadirov** [comment]
it happened to my i7 too.

**Comment by jakeajames** [comment]
@ahmedgadirov The i7 is not supported yet. Are you using mach_portal?

**Comment by ahmedgadirov** [comment]
no. just i installed yalu 102 to my iphone 7.  failed yes. but sometimes randomly rebotted. and i deleted ipa file from my iphone. solved

**Comment by KILLCAMPER** [comment]
It sum times reboots when installing jb you will get gfx glitch but hard re set will boot then you your app it will go in to jb state it's more like bad tweaks that the most likely for crash in jb state

**Comment by kpwn** [comment]
Friendly reminder that iPad Air 2 is only partially supported. I believe there are bugs in my code that only trigger on that specific device. Closing, a fix is planned but I do not really own the device so it will take a while.

**Comment by sinfulslave** [comment]
i takes man times to jailbreak now i can't log in to m google account to access purchased tweaks is this general issue?
