### ISSUE TITLE
SSH doesn't work

### ISSUE THREAD

**Issue by Amcio** [kpwn/yalu102#364]
iPhone SE iOS 10.2

Well ssh never worked for me. I tried running dropber -R -F -p 22 but it doesn't work. all dropbear files are in place and it says it's running. But it doesn't even open port 22. It didn't work since the beginning. SSH Tunnel doesn't work. It says: Server unexpectedly closed connection. I'm connecting with putty on Windows.

Note: From my understanding this IS a code issue as it didn't work since the beginning and is implemented by yalu itself.

**Comment by OGKevin** [comment]
This is not an issue. Ssh works fine over usb. Please close this issue, u can still comment after its closed. There is a turkey on reddit how to ssh over usb.

**Comment by Amcio** [comment]
Yes this is a issue I already asked for help on Reddit but nothing fixes it. I tried USB tunnel etc. but they do not work. Port scan doesn't even show port 22 as open.

**Comment by OGKevin** [comment]
Seeing that u want to ssh to port 22 means that y haven't done ur research right. Unfortunately im not on pc and cannot provide with the link to the tutorial. But again SSH over usb seems to work just fine so this isn't a issue.

**Comment by OGKevin** [comment]
https://www.reddit.com/r/jailbreak/comments/5r2mwr/tutorial_how_to_use_dropbear_ssh_via_usb_on/

**Comment by Amcio** [comment]
Here's what I tried:

SSH over USB port 22 phone computer port 2222 connecting to local host = server unexpectedly closed connection 

iFunBox tunnel never actually worked for me 

I made a post about it on Reddit and someone told me I need to run dropbear -R -F -p 22 and then use ssh tunnel. I did that and it also didn't work. Also I don't know if it should but dropbear doesn't start automatically after jb. I think that's all I tried...

**Comment by OGKevin** [comment]
reboot and rejailbreak and follow the tutorial that i have provided to you. Dropbear -F -R -p 22 is a fix for iOS 10.1.1 not 10.2

**Comment by Amcio** [comment]
Did that and still: Server unexpectedly closed connection

**Comment by 0neday** [comment]
chech the directory /etc/dropbear whether exist or not on your device. Do you install MTerminal? If you install it, you can just tap dropbear command, and then try again

**Comment by 0neday** [comment]
Or install xshell on your windows, then tap "ssh mobile@127.0.0.1 -p 2222 -v" to view verbose info

**Comment by Amcio** [comment]
It exists and when i type the command it still doesn't work... and I try xshell when I get access to my pc

**Comment by 0neday** [comment]
Pls paste the verbose info in here

**Comment by kpwn** [comment]
This is expected behaviour if you install OpenSSH on top of dropbear. Are you sure you didn't do so?

**Comment by Amcio** [comment]
It appears that it's something wrong with putty. Because Xshell works just fine and putty gives me an error. This is the last thing i would think about. As i tried connecting once from my linux machine and it didn't work. Or maybe the: "Have you tried turning it off and on again?" rule fixed it. I will never know... Well the issue can be closed now. Thanks for help.

**Comment by thosuperman** [comment]
This solution works like a charm

https://www.reddit.com/r/jailbreak/comments/5r2mwr/tutorial_how_to_use_dropbear_ssh_via_usb_on/
