### ISSUE TITLE
When will stable version come out

### ISSUE THREAD

**Issue by LastPust** [kpwn/yalu102#365]
we cannot use any of beta versions because we can't risk it anymore since ios 10.2 is not signed..

i am wondering when will stable version come out?

**Comment by eXhumer1149** [comment]
@qwertyoruiop said on twitter this is as stable as the jailbreak will be.

Also, not code related issue.

#162 #64

**Comment by OGKevin** [comment]
#162 #64 close this please

**Comment by haidev12** [comment]
not code related.

**Comment by ahmedgadirov** [comment]
he said that. beta 7 is very stable. expect for some devices. example 5s or ipad.  but 6,6s,se models very stable. and u can update ur yaluapp

**Comment by nathanaccidentally** [comment]
This isn't code related.
