### ISSUE TITLE
No more reinstall after 7 Days !

### ISSUE THREAD

**Issue by i0s1q** [kpwn/yalu102#366]
Here is the tutorial! 
1. Open Cydia and Install 
2. - MTerminal (free) 
 - Filza (free) 
3. Restart your Device ! 
4. Open Safari to http://yalu.qwertyoruiop.com/ and 
Download ipa (cydia impactor) 
5. Download end ? - Open to Filza 
6. Open yalu102_beta7.ipa tap yalu102_beta7.ipa tap 
Payload tap yalu102.app and Copy ! 
7. Back (Filza) to ರ/ಯ and Open Applications and paste ! 
8. Open MTerminal and tipping uicache + Enter ! Close 
MTerminal 
9. Restart your Device and Open Yalu102 tap Go 
10. Happyend

**Comment by eXhumer1149** [comment]
A) The app won't work in non jailbroken mode.
B) Not code related issue

#162 #64

**Comment by OGKevin** [comment]
#162 close this please

**Comment by i0s1q** [comment]
A. After each restart, Yalu must be restarted and run.
B. Only the profile you do not have to renew every 7 days over PC it is.
C. Work fine for me.
