### ISSUE TITLE
Safe Mode

### ISSUE THREAD

**Issue by toniqyteza** [kpwn/yalu102#367]
yeah i know that this shouldn't be posted here but luca needs to know this so apparently when i rejb with yalu102 beta 7 for iph5s iOS 10.2 its goes directly to safe mode i asked on reddit and some guy had the same problem i know this is not a major issue but luca needs to be aware (if he isn't) thanks!

**Comment by eXhumer1149** [comment]
Safe mode is caused by tweaks AFAIK. I'm pretty sure this is not Yalu Code related.

@kpwn should respond on this.

**Comment by toniqyteza** [comment]
i even tried it without tweaks

**Comment by justinoboyle** [comment]
Please post logs.

**Comment by toniqyteza** [comment]
i think this issue happens only on iph6 and 5s not sure

**Comment by ahmedgadirov** [comment]
there is maybe some tweaks. what tweaks u have installed on ur idevice. and when u trying to delete some tweaks there were some 1-2 tweaks that u have to manullay delete. i mean: when u install 'tweak a' u have to instal 'tweak a1.0' and 'tweak a1.1'. but when u delete 'tweak a' that will be deleted. but 'tweak a1.0' and 'tweak a1.1' not
