### ISSUE TITLE
Random Crash while using an app other than Cydia

### ISSUE THREAD

**Issue by msamuel002** [kpwn/yalu102#368]
While I was using Snapchat, all of a sudden my phone freezes and restarts by itself. I then go into Settings, Privacy, Diagnostics & Usage, and Diagnostics & Usage Data, and there is a crash log with the name "com.apple.WebKit.WebContent.cpu_resource....". The pastebin for it is: http://pastebin.com/as59bk4j. Could anyone, preferably @kpwn tell me why it keeps doing this?

**Comment by haidev12** [comment]
Did you try downgrading SnapChat?

**Comment by msamuel002** [comment]
I already successfully did that 3 days ago. That's definitely not the cause

**Comment by ahmedgadirov** [comment]
do u have localiapstore

**Comment by msamuel002** [comment]
nope @ahmedgadirov i have App Admin, Barrel, Beam, CCLowPower, DarkMessages, Docker, FlipControlCenter, Horseshoe, iCleaner Pro, Incognito Messages, Noctis, Phantom (Lite) for Snapchat, PowerDown, and WinterBoard (with Ace Sierra theme)

**Comment by ahmedgadirov** [comment]
I doubt on phantom lite

**Comment by DontAskMeIt** [comment]
@ahmedgadirov could localiapstore have something to do with my crashes on snapchat?..

**Comment by ahmedgadirov** [comment]
either snapchat or another app. it did to me. i turned off and everything turned to ok

**Comment by DontAskMeIt** [comment]
This is the only app crashing me.. (SNAPCHAT)

**Comment by ahmedgadirov** [comment]
@DontAskMeIt if u have any tweak for snapchat thats too bad. snapchat devs will ban u

**Comment by jake-cryptic** [comment]
I had this happen to me too, although it put it in a bootloop and now I'm on 10.2.1, going to try use Prometheus with my saved SHSH2 blobs

**Comment by msamuel002** [comment]
@kpwn it crashed and restarted again: http://pastebin.com/1C1CXqda (assetsd-2017-02-01-200727.ips). then, when i go to re-enable the jb, instead of respringing it and enabling it, it restarts and doesnt activate jb. before, it was working fine😔

**Comment by DontAskMeIt** [comment]
Update the Yalu102 app, That worked for me and fixed all problems

**Comment by tangalbert919** [comment]
That's a good idea.
Also, remove the tweaks you have for Snapchat. I didn't install any, and I didn't install App Admin either. Check App Admin, because it might be messing up Snapchat.

**Comment by kpwn** [comment]
... phones have issues, and these crash logs have nothing out of the ordinary.

Yalu has a 50/50 chance of reboot/success. You are arguing coincidences.
