### ISSUE TITLE
cydia not opening

### ISSUE THREAD

**Issue by fer6666** [kpwn/yalu102#369]
from the first time i did jailbreak cydia didnt open
i tried many times to delet yalu and install again but it is the same

how can you help me 
ip5s.ios10.2.yalu b7

**Comment by ahmedgadirov** [comment]
if u don't want to lose your jailbreak chance. wait!

**Comment by fer6666** [comment]
so if i wait for the next jailbrek ...will it work
becouse when i delet yalu .. cydia doesnot... the proplem not with my cydia?
thank you

**Comment by ahmedgadirov** [comment]
no. whenever u want u can update or downgrade yaluapp betas. but if u want to jailbreak. wait. stable jailbreak will release soon :)

**Comment by fer6666** [comment]
thank you >>> i will delet yalu and leave cydia till the new betas

**Comment by ahmedgadirov** [comment]
you are very wellcome (:

**Comment by ahmedgadirov** [comment]
but if u know about this try it: ssh into your device and run uicache  

ps: i prefer to wait for full release!

**Comment by MDallak** [comment]
I know this problem talk me on twitter
@m_dallak
