### ISSUE TITLE
Iphone 6 10.2 Snapchat Crashes phone Randomly (Almost every time)

### ISSUE THREAD

**Issue by DontAskMeIt** [kpwn/yalu102#370]
Snapchat Just keeps crashing my IPhone, Only in Jailbreak mode. I cant find a fix. Any ideas?
NO SNAPCHAT TWEAKS ARE INSTALLED
I read the issue posting guidelines.

**Comment by ahmedgadirov** [comment]
delete snapchat tweaks

**Comment by ahmedgadirov** [comment]
what tweaks you have?

**Comment by ErickJR13** [comment]
List your tweaks installed

**Comment by tangalbert919** [comment]
#162 
This is not an issue regarding this jailbreak. It could be because you have tweaks installed that modifies Snapchat, and it doesn't support the newest version of Snapchat.
Close this issue. This is not a concern whatsoever.

**Comment by DontAskMeIt** [comment]
installed:
- Bigboss Icon set
- Catalyst
- Cydia installer
- Cydia Substrate
- Cydia Translations
- DarkMessages (IOS 10)
- Debian Packager
- Horseshoe
- HYI Repo Icons
- Lithium Ion
- LockScreenGestureCleanUp
- Noctis
- NoMoreExpire
- Patcyh
- Peek-a-boo
- Power Tap
- RoundDock
- Substrate Safe Mode
- Tape Archive

**Comment by DontAskMeIt** [comment]
I have no tweaks modifying Snapchat

**Comment by tangalbert919** [comment]
Then we have a problem. When you said "crash", do you mean your phone reboots or just the application?

**Comment by DontAskMeIt** [comment]
Phone all together The screen like cuts off, and then the apple logo appears, and jailbreak state is not initiated.

**Comment by tangalbert919** [comment]
This is weird. I have Snapchat and a jailbroken iPhone. What doesn't make sense is how your phone crashes and mine doesn't.
Are you on the latest jailbreak? If so, which iPhone are you using?

**Comment by DontAskMeIt** [comment]
IPhone 6, Cydia Version: Cydia64_1.1.28~b9 (en-us)

**Comment by DontAskMeIt** [comment]
One thing I know is different between both of our devices is:
- Mine has a notification center malfunction, where no text shows up in the notification with an exception of the app name. ( Exempt messages or system notifications, such as "ICloud backup alerts")

**Comment by tangalbert919** [comment]
What do you know? We have the same device AND we are on the same Cydia version! :smile:
In this case, I don't know why Snapchat would crash your phone. Are you using the Yau beta 7 jailbreak or something older?
Also, thanks for introducing us to Lithium Ion. I can't believe I never found such a tweak that was so awesome with the battery icon (which is the kind of thing I would say when I have the heartbeat animation for a loading animation).

**Comment by DontAskMeIt** [comment]
I was just about to ask that, Do I need to update the Yalu102 application, and if so .. How do I do that on a Windows based machine (Win10)

**Comment by tangalbert919** [comment]
First, you need to download the IPA file from @kpwn's official website.
Use [Cydia Impactor](http://cydiaimpactor.com) to install it. Just extract all the files from the Impactor zip folder into its own little folder (that means everything, including the dlls and stuff), and then run the program.
Just drag the ipa file onto Impactor, and put in your credentials. The credentials are sent to Apple, and nowhere else (still suspicious on that, but not 100% worried due to 2-factor authentication).

**Comment by DontAskMeIt** [comment]
would you be able to link me to the IPA file. I have looked and looked for Kpwn's website, and All I'm finding is some school in the netherlands

**Comment by tangalbert919** [comment]
Go [here](http://yalu.qwertyoruiop.com).
By the way, I AM LOVING LITHIUM ION!

**Comment by DontAskMeIt** [comment]
Lithium Ion, must have tweak no doubt. and wow... it helps to know that "ipa (cydia impactor)" means the ipa and not the download link to cydia impactor.., I will check to see if the beta I was on was the problem. Conflicting with Cydia Substrate.

**Comment by DontAskMeIt** [comment]
I would also like to say a quick thanks @tangalbert919 , for helping me so far with this issue.

**Comment by DontAskMeIt** [comment]
Huston! We have a FIX. @tangalbert919 your an amazing person, I have followed you on GitHub. ps my snapchat username is "DontAskMeIt". (Just in case you wanna add me ;)) #SOLVED

**Comment by skyllerkyller** [comment]
Did you ever find out how to fix this? I'm still having issues with mine.
