### ISSUE TITLE
Apps crache iphone 6+ ios10.2

### ISSUE THREAD

**Issue by AbouImran** [kpwn/yalu102#371]
All applications crache, I am obliged to reboot the iphone to be able to reuse the apps
iphone 6+ ios10.2 Cydia b9
![img_0213](https://cloud.githubusercontent.com/assets/24853903/22541909/25678cb2-e921-11e6-89f6-a8faac1a9256.PNG)

**Comment by maetrik92** [comment]
Are you on beta 7?did you triple check your installed tweaks?try to remove every tweak you extra installed and try to use your apps again!

**Comment by AbouImran** [comment]
not work, same pb
