### ISSUE TITLE
can't find older beta yalu102 

### ISSUE THREAD

**Issue by modz2014** [kpwn/yalu102#372]
hi I'm trying to find the older beta of yalu102 but the links are broken can someone fix them or find them please

**Comment by maetrik92** [comment]
It's not fuckin code related!!!jesus read the fucking readme!

**Comment by modz2014** [comment]
mate i know this but link is broken i can't download beta 4 or 5

**Comment by mologie** [comment]
Yep, the website's config is broken, probably while trying to screw with that icrackuridevice site.

Workaround:

`curl -O --referer https://yalu.qwertyoruiop.com/ https://yalu.qwertyoruiop.com/yalu102_beta5.ipa`

**Comment by modz2014** [comment]
thank you what about beta 4 please

**Comment by mologie** [comment]
Really? Look closely at the command and take an educated guess...

**Comment by modz2014** [comment]
shit sorry my bad i didn't look proplery hahah umm just trying to fix dropper over ssh

**Comment by modz2014** [comment]
ok i fixed ssh vai dropper but i patch nonceEnabler this a new ipa

**Comment by ahmedgadirov** [comment]
https://github.com/kpwn/yalu102/blob/master/README.md

**Comment by kpwn** [comment]
There is absolutely no need to use older betas.
