### ISSUE TITLE
Button text when removing Yalu

### ISSUE THREAD

**Issue by abdelkafiahmed** [kpwn/yalu102#373]
When removing Yalu (to update it to the latest beta version) the two buttons indicates "None".
![16358398_10211995219138617_2110072902_n](https://cloud.githubusercontent.com/assets/7271421/22548356/48a40d70-e946-11e6-860e-0a52aa561c63.jpg)

**Comment by kpwn** [comment]
You don't even need to remove yalu to install a new version. Anyway looks like some tweak side effect
