### ISSUE TITLE
Why in yalu app There si a pic of nord Corea dictator  Kim Jong-un?

### ISSUE THREAD

**Issue by christo98** [kpwn/yalu102#375]

**Comment by Amcio** [comment]
Because that's the design also #64

**Comment by Aaahh** [comment]
If you are being oppressed than replace the image

**Comment by christo98** [comment]
There is this pic becouse luca todesco is kim jong-un and he wanna kill ios users 😭

**Comment by kpwn** [comment]
We should add a $10 fee for posting dumb comments here, we'd be rich.
