### ISSUE TITLE
Cydia not working correctly

### ISSUE THREAD

**Issue by zigajuhca** [kpwn/yalu102#377]
When I open Cydia on the main page I can't access anything pike featured or themes. When I choose them it colors grey.

**Comment by XAVERRenogadeAngle** [comment]
#162 Use Reddit don't post questions here like this. 
Try swiping slightly from the right to left while tapping should work or get the cydia beta.

**Comment by zigajuhca** [comment]
Ok thanks

**Comment by learntofly83** [comment]
What worked for me, download from cydia: "ifile", "mobileterminal" (lordscotlands fork works for me)

Double click home and close cydia.

Then download these in safari, open them in ifile and use the install option. Do them one at a time, in the order I give:

1) http://apt.saurik.com/beta/cydia-arm64/tar_1.29-10_iphoneos-arm.deb

2) http://apt.saurik.com/beta/cydia-arm64/dpkg_1.18.10-12_iphoneos-arm.deb

3) http://apt.saurik.com/beta/cydia-arm64/cydia_1.1.28~b12_iphoneos-arm.deb


(All taken from this page: http://apt.saurik.com/beta/cydia-arm64/ )

Open cydia again, refresh data... possibly there are language packs needed.... I didn't need them, you may need to do some research 

LTF

**Comment by kpwn** [comment]
congrats for not being able to google
