### ISSUE TITLE
can't update or install apps

### ISSUE THREAD

**Issue by TheNightRider12** [kpwn/yalu102#380]
I can't update or install apps. Has anyone else had this and can anyone help? This is frustrating

**Comment by aaron1421** [comment]
Me too someone please help I try to install a tweak or something and it stays on loading screen forever.

**Comment by TheNightRider12** [comment]
I am trying to install App Store apps. I'm fine with tweaks

**Comment by aaron1421** [comment]
My App Store doesn't update either

**Comment by ghost** [comment]
Unrelated to jailbreak, BUT seeing how im here, FIRST hold power and home for 10 sec let your shit reboot. THEN go into itunes, and log out. Log back in. (this has worked for me in the past) and if not... your fucked burn your phone and stomp on it cause its plain out fucked.

**Comment by tangalbert919** [comment]
That's odd. My App Store works just fine.
Did you download the IPA from @kpwn's website? If not, that might be the problem: You added a backdoor to your own phone. And it doesn't have a single lock.

**Comment by aaron1421** [comment]
Can you send a link
