### ISSUE TITLE
Cydia forever loading

### ISSUE THREAD

**Issue by aaron1421** [kpwn/yalu102#382]
This is not a support forum or generic mailing list.

This form is exclusively for reporting issues caused directly by the inner workings of yalu.

Direct your jailbreaking questions to one of these fine communities:

* https://reddit.com/r/jailbreak
* http://www.jailbreakqa.com/

Issues, which are not related to yalu's code, may be closed without comment. Do NOT post about: Cydia, tweak, respring/bootloop or app issues UNLESS you have evidence that they are caused by an error in the jailbreaking software itself.

(Delete this bit after reading, and replace it by "I read the issue posting guidelines.")

**Comment by aaron1421** [comment]
My Cydia just says loading for like 40 mins and doesn't say resorting or reboot please help

**Comment by tangalbert919** [comment]
You forgot to do the last part of those guidelines from #162 (I forgot which issue it was already). Also, YOU BROKE THE GUIDELINES!

**Comment by ghost** [comment]
#162 #64

**Comment by aaron1421** [comment]
What do I do

**Comment by aaron1421** [comment]
App sync. Fucked up my phone

**Comment by timonline** [comment]
@aaron1421 not to be rude but you didn't read any readme or do ANY research and now you are bitching that you fucked your phone, do you expect people to have sympathy?

If you are not up to running beta jailbreaks and following the precautions, maybe it's not for you.

In any case, you should close this issue as it has nothing to do with the jailbreak code
