### ISSUE TITLE
iPad Air 2 Error

### ISSUE THREAD

**Issue by sniper497** [kpwn/yalu102#383]
After using impactor to get the Yalu app onto my iPad Air 2, I hit the blue "go" button but my screen turns black and the apple logo comes up and reboots my iPhone. I'm 100% certain the device is on iOS 10.2 and I am using the yalu102_beta7.ipa file for the JB. There is no Cydia app once the iPad is back on. I also sometimes get an error message saying "failed, retry" when attempting to install Cydia.

**Comment by 1337jay** [comment]
This is a known issue and will mostly likely be improved in the future versions, just keep on trying untill the device resprings, not reboot. Rey to avoid rebooting after succeeding as you will have to try your luck gain after each reboot.

**Comment by danielkoller** [comment]
Luca is already aware of that problem and said that he currently doesn't have a fix for it and at the moment not the time to do any further research. I can only recommend to put your iPad Air in Airplane mode, restart it and wait for some seconds and then try to jailbreak it. This gave me a higher success rate.

**Comment by darkfus10n** [comment]
So Luca has resigned from this project or am I misunderstanding?

**Comment by danielkoller** [comment]
No, not at all. He will surely work on it anytime soon but just stated that he currently doesn't have the time to work on a fix.

**Comment by KILLCAMPER** [comment]
Luca has a life and he has already put a lot of time in to this project he deserves time off there are plenty of coders on hear and they all have dun an excellent  job it will all come in time . People do have other commitments/life

**Comment by tjsreece** [comment]
The Air 2 is supported but still buggy. We know about this, @sniper497 please close this issue.
