### ISSUE TITLE
taking lots of time for deleting photos 

### ISSUE THREAD

**Issue by vikassaroha84** [kpwn/yalu102#384]
Hi 
First of all thanks lot for public the jailbreak tool you done a great job 
you are life line for all IOS users

Know my problem is after the jailbreak ios 10.2 with Aplha.ipa my phone start working slowly and storage is start automatically full and second issue with photos if i try to delete multi pal pic like 1000 of number phone stuck and restart automatically  

please help and suggest the correct version of ipa

Thanks

This is not a support forum or generic mailing list.

This form is exclusively for reporting issues caused directly by the inner workings of yalu.

Direct your jailbreaking questions to one of these fine communities:

* https://reddit.com/r/jailbreak
* http://www.jailbreakqa.com/

Issues, which are not related to yalu's code, may be closed without comment. Do NOT post about: Cydia, tweak, respring/bootloop or app issues UNLESS you have evidence that they are caused by an error in the jailbreaking software itself.

(Delete this bit after reading, and replace it by "I read the issue posting guidelines.")

**Comment by timonline** [comment]
@vikassaroha84 you broke the guidelines and I do not believe this is a Yalu issue.

Secondly, what Alpha.ipa? You do know there are 7 betas that are WAY more stable than the Alpha.ipa?

| Version | Download | SHA1 |
|---------|----------|------|
| Beta 7  | [Link](https://yalu.qwertyoruiop.com/yalu102_beta7.ipa) | 4afa99d4b568aa8cbb9ac61fddd584111fed79c5  |
| Beta 6  | [Link](https://yalu.qwertyoruiop.com/yalu102_beta6.ipa) | 0130ebe60c97e2013a4b849b7d9bc321d749f304  |
| Beta 5  | [Link](https://yalu.qwertyoruiop.com/yalu102_beta5.ipa) | f8eb6cd37054a9d25b818e3bddd13bfedbf72df1  |
| Beta 4  | [Link](https://yalu.qwertyoruiop.com/yalu102_beta4.ipa) | f8270e59d7d7267613ffa63217b91fea425eec36  |
| Beta 3  | [Link](https://yalu.qwertyoruiop.com/yalu102_beta3.ipa) | b2e0bdd31566f876d67cba036b5d29aef7ff257d  |
| Beta 2  | [Link](https://yalu.qwertyoruiop.com/yalu102_beta.ipa) | 4fddad7cca8aa0c0a6579c1d63d00917f15efc86  |
| Beta 1  | [Link](https://yalu.qwertyoruiop.com/yalu102_alpha.ipa) | 2fe14f1c1e1a0d26203bbb123f6747a978dd2b4f  |

**Comment by ghost** [comment]
#162 #64

**Comment by kpwn** [comment]
.. wat
