### ISSUE TITLE
Won't boot after pressing go

### ISSUE THREAD

**Issue by xXDjMikeXx** [kpwn/yalu102#385]
Sometimes it won't boot after pressing go it say "already jailbroken" but It is not booting :/ how to fix this ? Only happening sometimes! 

i6+
iOS 10.2
Yalu beta7

**Comment by KILLCAMPER** [comment]
Tried hard re set power and home and then re jb

**Comment by kpwn** [comment]
what if i told you that you are already jailbroken?
