### ISSUE TITLE
Cyida is crashing after Jailbreak

### ISSUE THREAD

**Issue by TrickArtist** [kpwn/yalu102#387]
I jailbroke my device (iPhone 6 iOS 10.2) and i try to open cydia app it's crashing then I went to yalu app it's says already JailBroken but still i cant access Cydia app it crashing again. I deleted the yalu app and re installed it but the same problem continuing. is there any way to remove cydia app from device ?? please someone advice how to resolve this problem.

**Comment by timonline** [comment]
Close this issue #64 and contact me @timourrashed on twitter
