### ISSUE TITLE
no cydia icon and cydia crash 

### ISSUE THREAD

**Issue by sinfulslave** [kpwn/yalu102#391]
i have ipad air 2 10.2 after clean restoer i tried to jailbreak using beta 7
icon of cydia did't appear tried to many times dont know what i did i disconnected from lab and disconnect internet and tried to rejailbreak again with oher acc many times it appeared 
now after restart i try to rejailbreak again i press go and it respring and nothing happens i delete yalu and reinstall it no use so i  there solution for this

**Comment by beanjo55** [comment]
read #360

**Comment by sinfulslave** [comment]
i think this issue is related to the jailbreak yalu version

**Comment by timonline** [comment]
@beanjo55 yes and no. It is code related but @kpwn is aware of it, see  #363

**Comment by sinfulslave** [comment]
it is not  a random reboot but now i figured that it takes many many times to jailbreak u can close the post thank but i wish this is fixed in the next update

**Comment by timonline** [comment]
@sinfulslave the highlight was "partially supported", you can close it yourself

**Comment by kpwn** [comment]
#397

**Comment by timonline** [comment]
@sinfulslave if still interested in solving Cydia crash contact me on twitter @timourrashed.

I know the solution and helped like 10 people so far
