### ISSUE TITLE
Yalu102 app broke

### ISSUE THREAD

**Issue by McGamezZPlayer** [kpwn/yalu102#392]
The app has for some reason within a few hours of jailbreaking and rebooting start to crash my phone, and not just once
So i deleted the app, and things have started to screw up
The app keeps reappearing 
Deleting it from settings will after a while freeze/crash it, and reopening it breaks settings
My phone will also crash sometimes

**Comment by McGamezZPlayer** [comment]
Also im on iPhone SE ios 10.0.1

**Comment by blobbyblo** [comment]
Did you remove the developer account from your device? Also this is potentially not a code related problem... see #162

**Comment by McGamezZPlayer** [comment]
Ok thx
Also i have tried to reinstall,
Multiple times
I just get stuck on installing ipa

**Comment by McGamezZPlayer** [comment]
I dont know why the app after restarting reappears though
