### ISSUE TITLE
Cyida is crashing after Jailbreak

### ISSUE THREAD

**Issue by FunkeyPanda** [kpwn/yalu102#395]
I jailbroke my device and i try to open cydia app it's crashing, iPhone 6s 10.2 Tried everything I re downloaded backup and started all again still same cydia wont go or work It never has

**Comment by TrickArtist** [comment]
Having same issue :(

I jailbroke my device and i try to open cydia app it's crashing then I went to yalu app it's says already JailBroken but still i cant access Cydia app it crashing again. I deleted the yalu app and re installed it but the same problem continuing. is there any way to remove cydia app from device ?? please someone advice how to resolve this problem.

**Comment by DarkKnight01** [comment]
it happen to my ipad air 2, i was able to download some of my tweaks one night but the next day cydia wouldn't open up. i deleted yalu n reinstalled but still cydia won't open. the jailbreaks works but can't get into cydia for updates

**Comment by Mila432** [comment]
https://github.com/kpwn/yalu102/issues/64

**Comment by kpwn** [comment]
If you are able to enter ssh, try with first:
<pre>rm /var/mobile/Library/Caches/Cydia/metadata.cb0</pre>

if it doesnt work try reinstalling cydia with:
<pre>rm /.installed_yaluX</pre>

and reboot and rejailbreak.
