### ISSUE TITLE
Will it support 32bit devices?

### ISSUE THREAD

**Issue by Sunbelife** [kpwn/yalu102#396]
I really wish my iPhone 5 (running on iOS 10.1.1) can be Jailbreaked.
looking for reply.

**Comment by Aerozolic** [comment]
your only reply is going to be "closed" and "banned"

**Comment by TrickArtist** [comment]
No you cant it's only for 64bit Devices

**Comment by NickGP** [comment]
#162

**Comment by Mila432** [comment]
https://github.com/kpwn/yalu102/issues/64
