### ISSUE TITLE
There is no Cydia or cydia icon

### ISSUE THREAD

**Issue by cydiasnotthere** [kpwn/yalu102#397]
When I was installing some tweaks to custimize my keyboard to deadpool theme, it got rid of all my emojis completely so I couldn't look or text any emoji's period. But I was deleting tweaks to see if I could fix this issue and I may have done something that got rid of cydia because I still have all the tweaks I installed before cydia broke and ive tried doing ssh and going through the whole jailbreak process again but every time the cydia icon does pop up. Any ideas on how to fix this.

**Comment by Mila432** [comment]
https://github.com/kpwn/yalu102/issues/64

**Comment by NickGP** [comment]
If you are on a iPad Air 2, it is a known issue and @kpwn is working on it. Otherwise it is not code related. #162

**Comment by NickGP** [comment]
If you would like, #391 and #363 have very similar issues to what you are describing.

**Comment by kpwn** [comment]
use ssh over usb to connect to your iphone and run:
<pre>rm /.installed_yaluX</pre>

to reinstall cydia
