### ISSUE TITLE
iPad Air 2 beta7 keeps getting random resprings 

### ISSUE THREAD

**Issue by haze4** [kpwn/yalu102#398]
This is not a support forum or generic mailing list.

This form is exclusively for reporting issues caused directly by the inner workings of yalu.

Direct your jailbreaking questions to one of these fine communities:

* https://reddit.com/r/jailbreak
* http://www.jailbreakqa.com/

Issues, which are not related to yalu's code, may be closed without comment. Do NOT post about: Cydia, tweak, respring/bootloop or app issues UNLESS you have evidence that they are caused by an error in the jailbreaking software itself.

(Delete this bit after reading, and replace it by "I read the issue posting guidelines.")

**Comment by haze4** [comment]
No tweaks installed At all nothing -and random resprings

**Comment by ghost** [comment]
need update Cydia installer 1.1.28~beta14

**Comment by NickGP** [comment]
The iPad Air is very glitchy and is known to not be completely working with Yalu. @kpwn is working on fixing issues with the iPad Air 2 and will hopefully be able to better support your device.

**Comment by Mila432** [comment]
https://github.com/kpwn/yalu102/issues/360
https://github.com/kpwn/yalu102/issues/64
