### ISSUE TITLE
Cydia not showing up

### ISSUE THREAD

**Issue by Dcjacko** [kpwn/yalu102#404]
I Jailbreaked my Iphone 5S 10.2 i installed Yalu and pressed go and cydia didnt pop up. I tried a couple more times and its still not working

**Comment by ghost** [comment]
This is not code related issue.
#162 #64

**Comment by mmhobi7** [comment]
@eXhumer1149 ?

Just keep restarting and trying, happened to a friend and it worked after clicking "watch log" in cydia impactor and trying again

**Comment by mmhobi7** [comment]
Probably coincidence but try it

**Comment by ghost** [comment]
https://www.reddit.com/r/jailbreak/comments/5sgbyp/tutorial_readding_cydia_in_case_of_loss_ios_102/

Possible fix listed in section 1. Replacing cydia.

**Comment by cydiasnotthere** [comment]
First reset your iPhone so you have the option to press go on Yalu but don't do it yet, now go to your computer and download ifunbox open it then go to quicktoolbox, plug in your iPhone and open USB tunnel. A code should appear if you did it right. Now go to Yalu and click go until you get Cydia. Hope it works for you because it worked for me.

**Comment by ghost** [comment]
Ask this on /r/jailbreak.

**Comment by ghost** [comment]
#162 #64

**Comment by nullpixel** [comment]
LUKE STOP COMMNETING ON EVERY ISSUE

**Comment by ghost** [comment]
And what are you going to do to stop me?

**Comment by nullpixel** [comment]
You're 12. Chill out; I get email notifications for these comments. Scroll to the top of this issue: someone already referred them. There's no need for you to spam every fucking issue

**Comment by ghost** [comment]
I love how you say "chill out," yet you were using all caps telling me to stop.

**Comment by nullpixel** [comment]
Because it's annoying having 26 emails because you spammed on issues that already have been commented on

**Comment by ghost** [comment]
Well then turn off email notifications.

**Comment by mmhobi7** [comment]
Fr shut up luke

**Comment by nullpixel** [comment]
@TheLukeGuy: how about you shut up and do everyone a favour?

I need email notifications on because of my PRs. sush

**Comment by ghost** [comment]
:zipper_mouth_face:
