### ISSUE TITLE
iPhone 6s iOS 10.2 nonce setting fails

### ISSUE THREAD

**Issue by ghost** [kpwn/yalu102#407]
So since nonce enabler is installed by default with Yalu I thought I could just set my generator in case of failures and I need to restore however when I set the boot nonce in nvram it gets error setting variable iokit/common general error

**Comment by chaustark** [comment]
get root first

**Comment by blobbyblo** [comment]
#162 not code related specifically to this jailbreak.

**Comment by ghost** [comment]
I am root
And it kind of is code related because Yalu is meant to enable this but for some reason it fails

**Comment by chaustark** [comment]
lol, what do u mean root, type "su" and your root pwd then add your nonce, pls google before post here

**Comment by ghost** [comment]
Exactly what I have said I am root i even tried your way of 'su' even though I already am and it still gives the same error

**Comment by chaustark** [comment]
with root
![16523584_762906767206218_333966544_o](https://cloud.githubusercontent.com/assets/17468050/22627290/0c6b9800-ebf3-11e6-820c-1d669872c29b.jpg)
without root
![16523034_762906087206286_408505631_o](https://cloud.githubusercontent.com/assets/17468050/22627289/0c68f230-ebf3-11e6-9fc8-54264e0d86f4.jpg)

**Comment by ghost** [comment]
okay lets show you on my device 
https://gyazo.com/f8a7a47b9c30d3a53aea75377245229a

as you see from the whoami command i am infact root

**Comment by chaustark** [comment]
why not use MTerminal

**Comment by ghost** [comment]
I have tried on mterminal also same result just easier to do it via putty

**Comment by DevX-Cipher** [comment]
dude you put con not com.apple

**Comment by DevX-Cipher** [comment]
in your second photo maybe you need to update to beta 7 yalu102 if you need help you can dm me on twitter @modz2014

**Comment by ghost** [comment]
That was other guy 

And I got it working now I'll close this for some reason the ipa off his site didn't work so I just downloaded and compiled it and tried again and worked just fine
