### ISSUE TITLE
Random restart leads activation screen 

### ISSUE THREAD

**Issue by XPMCoding** [kpwn/yalu102#409]
I read the issue posting guidelines.
Random restart lead to the phone booting to activation screen, after unlocking all apps user apps were deleted but none of the texts/pictures were deleted. The Yalu102 app is gone but cydia and Ifile still there. This was on a Iphone 6 IOS 10.1.1 
------------------------------------------------
about ten minutes later the phone restarted and all apps are back as if nothing ever happened....

**Comment by DevX-Cipher** [comment]
so what are you trying to do

**Comment by mmhobi7** [comment]
Did you try touching your mac address or uuid?
Any tweaks?

**Comment by XPMCoding** [comment]
No tweaks, when it happened I had just used Yalu102 was about 2 minutes after being jailbroken. I'm not trying to do anything I was just posting an issue that I ran into

**Comment by kpwn** [comment]
had this happen before, unsure what may be causing this. has no side effects after rebooting.

**Comment by XPMCoding** [comment]
no side effects at all other then the apps being in different spots, first time it has happened
