### ISSUE TITLE
Add Support for Beta of IOS 10.2 (iPhone 6s, NOT IPHONE 7)

### ISSUE THREAD

**Issue by endercypher** [kpwn/yalu102#416]
how do i add support for a beta of 10.2 a friend of mine has the one of the betas of IOS 10.2 hes on a iPhone 6s thanks for the help in advance

**Comment by KILLCAMPER** [comment]
Beta 7 I would go for

**Comment by endercypher** [comment]
as then beta 7 is what youd edit and add support for the beta of IOS 10.2?

**Comment by coolstar** [comment]
You'll need to find the offsets for allproc and rootvnode and add them to offset.c

See: https://bugs.chromium.org/p/project-zero/issues/detail?id=965#c2 for details on finding offsets
