### ISSUE TITLE
What Can I do with my i7

### ISSUE THREAD

**Issue by ahmedgadirov** [kpwn/yalu102#418]
without jailbreak iPhone is not a phone. what i have to do with my i7. please support for i7.

**Comment by XAVERRenogadeAngle** [comment]
If you put it in the microwave after closing this post it will come out with cydia on it. 30 seconds on high should do the trick

**Comment by neildufva** [comment]
it depends on the model of the microwave... older models "high" settings are really the equivalent of modern microwaves "medium" setting. 45 seconds just to be safe to make sure the solder in the flux capacitor gets to the right temperature

**Comment by OGKevin** [comment]
LMAO

**Comment by wtpisaac** [comment]
#64 #162 #360
