### ISSUE TITLE
iPhone 6,2 Non Jailbroken Boot Loop

### ISSUE THREAD

**Issue by LordYusei** [kpwn/yalu102#425]
Fresh iOS 10.2 Install, Jailbreaking with Yalu102 Beta 7, Constant reboot loop on phone. Cannot even get into the Springboard. Restored back to 10.2 with Saved SHSH2 Blobs and jailbroke with Beta 6 instead and working perfectly. Not sure what caused the issues as CrashReporter wasn't installed, but as no tweaks were installed i'm guessing it's code related.

**Comment by kpwn** [comment]
Crashes are always saved, no need for CrashReporter. Closed to clean up issues, but I'm interested in any kernel panic. Also b7 has no significant changes that would break devices that work on b6.

**Comment by LordYusei** [comment]
Forgot to reply to this it seems. I upgraded the iPhone 5S to abets 7 again on a fresh restore of 10.2 (so glad I can write BootNonce lol), and same thing happened again. The issues seem to be a Kernel panic 3/4 of the way through the Jailbreak Process. Sometimes it succeeds, other times it's failing with a Kernel panic caused by an overflow I think. I'll reply back in morning with everything it says. Hope I can at least make it a bit more stable for people

**Comment by LordYusei** [comment]
Oh god I can't type. Meant to say Beta 7.
