### ISSUE TITLE
Loosing Appdata when activating Jailbreak

### ISSUE THREAD

**Issue by Scunkaneli** [kpwn/yalu102#427]
Issue: When activating the yalu Jailbreak via the yalu102b7 app on an iPhoneSE (10.2), it may be possible for Apps (eg Health & Whatsapp, probably every other app too) to loose some of the newest app data. For example the Health app looses the latest (manually added) data about my weight; WhatsApp can loose new messages. I think it is an issue with yalu102 itself and NOT with any tweak.

Description:
There are many ways this issue occurred to me. That's the reason why I want to post it here.

1. WhatsApp: I write a message, then reboot my via reboot command in terminal -> This new message is gone in both non-jailbroken and jailbroken mode. This also occurs when writing a message and then hard-rebooting the phone.

2. WhatsApp: Booting the phone (it got an message while it was shut down). It displays the notification from iOS. Without opening Whatsapp, I go to yalu and activate the jailbreak. In jb-mode, the notification is still there, but if I open Whatsapp, the message is not displayed (neither will it show up later on). If I open Whatsapp first in nonjb-mode, the message will be recived, then when I go to yalu, it stays visible.

3. Health: I add an entry in non-jailbroken mode, then go to yalu and activate the jailbreak. The data may be gone in both non-jb and jb-mode. Sometimes, after activating the jailbreak, the Health app does not display ANY data (just Substrate installed in this case). Respringing fixes this.

All these issues do not occur every time, but just sometimes. This is the reason why it's hard for me to find out the actual reason for this behavior. My guess is that it has something to do how yalu mounts and unmounts the user-data partition (could be wrong tho).
I hope someone is able to reproduce my issue, which is why I tried to discribe it as accurate as possible. Sadly I was not able to find any crashlogs using CrashReporter.

I read the issue posting guidelines & I hope I did not made any mistake. Thank you :)

**Comment by kpwn** [comment]
This seems to be because these apps do not save data as they go but only when exiting them, I believe. I suggest to not do anything in non-jailbroken mode except run Yalu. If you really wanna use non-jb mode, before jailbreaking do a clean reboot. I do not remount the user partition, however I believe Coolstar's stasher does. Do you have that installed by any chance?

**Comment by Scunkaneli** [comment]
Alright, I will try this. If I get this issue another time while following your advice, I'll report back! Maybe it won't be fixed just by not opening any other app than yalu in no-jb mode, as sometimes, WhatsApp messages I get when turning on the phone and then instantly jailbreaking (without opening any other app than yalu) can disappear. I haven't noticed this behaviour again since I wrote this post btw, so it seems to be a rare issue.
Thank you! :)

Edit: Nope, I have not got installed any stashing tweak.

**Comment by Scunkaneli** [comment]
Issue never repeated for me since the last report. Just instantly jailbreak when the device booted and you are good to go, like kpwn suggested. Thanks again for you work.
