### ISSUE TITLE
iTunes Backup Broken.

### ISSUE THREAD

**Issue by poorkid** [kpwn/yalu102#429]
When trying to backup an iPhone 6s (10.2) through the latest iTunes the process doesn't start. I can click it over and over it does nothing. iTunes recognizes the device, but will not back up data. 
I tried a clean non-jb iPod 5 on iOS 9.3.1. It went through the backup process successfully.

I read the issue posting guidelines.

**Comment by kpwn** [comment]
Interesting. Did you try with no-substrate mode?

**Comment by poorkid** [comment]
Yes. Rebooting into no-substrate has the same result.

**Comment by Scunkaneli** [comment]
Weird. Were you able to do a backup before you first executed yalu on your device?

**Comment by poorkid** [comment]
Yes, I have backups from Pangu 933 up to my update with clean 10.2. Updated to newest iTunes just in case but it persists.

**Comment by tangalbert919** [comment]
This is a very strange error. I did a backup after using Yalu, and it worked just fine (until I got an error about authorization, which is vShare's problem).

**Comment by poorkid** [comment]
No cracked app stores or appsync. 
I written a generator to nvram, that's about it with drastic changes.

**Comment by poorkid** [comment]
Is working now with latest iTunes
