### ISSUE TITLE
Can't add offsets for alternate board ids

### ISSUE THREAD

**Issue by Sticktron** [kpwn/yalu102#43]
The current uname.version string comparison is insufficient, it needs the board/model id to be able to create cases for devices with the same kernel but different boards (e.g. Samsung vs TSMC).

**Comment by kpwn** [comment]
not required, allproc and rootvnode are both in the main mach-o

**Comment by Sticktron** [comment]
How do I add this case to the existing if statement?

`} else if (strcmp(u.version, "Darwin Kernel Version 16.3.0: Tue Nov 29 21:40:09 PST 2016; root:xnu-3789.32.1~4/RELEASE_ARM64_S8000") == 0) {
	// 10.2 - iPhone 6s (TSMC)
        allproc_offset = 0x5A8438;
        procoff = 0x360;
        rootvnode_offset = 0x5AE0B8;`

**Comment by kpwn** [comment]
It is already present. The offsets are guaranteed to be identical on two kernels with the same version.

**Comment by Sticktron** [comment]
They weren't in Yalu b3. Am I blind, I don't see my offsets present.

**Comment by kpwn** [comment]
Yalu b3 is completely different. This was a from-scratch rewrite.

**Comment by Sticktron** [comment]
The TSMC issue still exists

**Comment by kpwn** [comment]
your offsets are however identical to those already present.

**Comment by Sticktron** [comment]
OK I am blind, I see them now
