### ISSUE TITLE
None of the betas working on iPhone 6, iOS 10.1

### ISSUE THREAD

**Issue by KashubaK** [kpwn/yalu102#430]
I read the issue posting guidelines.

I know this isn't the spot for support, but I have exhausted support options. Have stumped just about every genius in the /r/jailbreak discord.

I can't seem to get any of the betas to work on my iPhone 6 on iOS 10.1, no matter if I'm using my Windows desktop, my MacBook, any of the betas, or with any workaround (do not disturb, turning find my iPhone off, etc.) I'm able to get the Yalu102 app on my home screen, trust it, and hit "Go". After a few seconds, my phone crashes (the screen gets glitchy then turns off, followed by the apple logo) instead of re-springing.

Was told to post an issue here, since this seems like a bigger issue than something that could be solved through troubleshooting. If anyone needs more data from me, please ask. Also, if someone wants to use me to test just in case nobody has an iPhone 6 on iOS 10.1, that's totally okay. Just hit me up on the /r/jailbreak discord, @kashuba

**Comment by mwoolweaver** [comment]
can you build and run from source with Xcode and provide the output from the device console?

**Comment by KashubaK** [comment]
I'll sure try. Would you mind explaining the "Include the IOKit headers, and add them to your search path." step of the setup process? I'm not an Obj-C/Xcode dev, so I'm not quite sure how to go about that let alone what it means.

**Comment by MEXX1811** [comment]
#435 I made that post about the iPad mini 4 / iPad Air 2 because those devices have similar issues, please try that method on Beta 7 and let me know how it goes, thanks.

**Comment by mwoolweaver** [comment]
@KashubaK try [this](https://github.com/mwoolweaver/yalu102) it should find IOKit for you

**Comment by KashubaK** [comment]
@mwoolweaver I'm getting tons of "Header 'libkern/arm/OSByteOrder.h' not found" errors.
@MEXX1811 Trying that now.

**Comment by KashubaK** [comment]
I'm dumb, had the 10.1 beta. Sorry for wasting all of your guys' time.
