### ISSUE TITLE
Clipboard not working in yalu102 b7 JB

### ISSUE THREAD

**Issue by Crusher7** [kpwn/yalu102#434]
I was using yalu b3 on iPhone 6S+ and it was working good , but after installing yalu102 b7 the "Copy" not working at all even in safemode and the paste works only if something copied before jailbreaking only,then 
I tried jailbraking using yalu b3 , and everything works great again, so I think some problem in yalu102 b7 that causes this problem

**Comment by Crusher7** [comment]
I forgot to mention that My ios is 10.1.1👍🏻

**Comment by kpwn** [comment]
works fine for me, can anyone else repro? did you try no substrate mode (it's different than safe mode)?

**Comment by Crusher7** [comment]
Problem Solved by removing QuickDo3.9.4 !
