### ISSUE TITLE
/sbin/reboot breaks libimobiledevice reboot requests

### ISSUE THREAD

**Issue by colossus689** [kpwn/yalu102#436]
I read the issue posting guidelines.

Not sure as to the purpose of the `/sbin/reboot` introduced in the bootstrap.tar to the file system but it creates an issue for the `/usr/libexec/mobile_diagnostics_relay` service used by libimobiledevice for reboots.

It seems mobile_diagnostics_relay checks for the `access()` to the `/sbin/reboot` path and since it exists it attempts to reboot using it but since it doesn't have a valid codesignature it fails. 

If you've used the yalu102 jailbreak and can't seem to get your device to reboot using MobileDevice.framework (libimobiledevice) only until you successfully run the tethered jailbreak again, this is why.

**Comment by kpwn** [comment]
I am aware of this, and note that this should also apply with all other semi-tethered jailbreaks (i was in fact using this as a way to debug yalu841 before). There is no easy way to solve this I believe, apart from removing the binary.
