### ISSUE TITLE
Click on Go, and said Fail, retry

### ISSUE THREAD

**Issue by juliencousineau** [kpwn/yalu102#438]
Hi, I tried so much jailbreak methods,

And no ones I've succeed so far. I want Cydia in order to lock my LTE signal.

I've succeeded to install Yalu .ipa into my phone, but when I tried to click Go. It's alway's said Fail, Retry..

I want to mention that I was not able to go on General – Device Management and find Yalu.

.. I don't know what I'm missing .. but if someone can help me I will really appreciate it.
![img_2304](https://cloud.githubusercontent.com/assets/8728015/22994127/5938d252-f38b-11e6-8dbc-fc0ee46c362c.PNG)
![img_2305](https://cloud.githubusercontent.com/assets/8728015/22994132/5bd540fe-f38b-11e6-963d-1c43720957b1.PNG)

Thanks.

**Comment by akachronix** [comment]
The offsets are not provided for beta versions of iOS. Also, this is for issues _**WITH**_ the code and _**NOT**_ for issues regarding the actual jailbreak.

**Comment by juliencousineau** [comment]
My version is 10.2.1 not any beta of IOS

![img_2306](https://cloud.githubusercontent.com/assets/8728015/22998882/7afb2238-f39e-11e6-9e78-08416bb15ae6.PNG)

**Comment by ItzLevvie** [comment]
It will not work on 10.2.1

Why couldn't you read the README file?

**Comment by HoraceTang** [comment]
╭(╯^╰)╮

**Comment by kpwn** [comment]
special level of idiocy right here

**Comment by juliencousineau** [comment]
Guys thank you, but I'm not an expert as you, and this kind of comments just put you so low.. anyway thanks for noticing me

**Comment by timonline** [comment]
@juliencousineau you don't have to be an expert or even a genius to go through a GOD DAMN readme. The name even suggests, you know......to read it.

If you don't put in the effort to do your research and then waste people's time by posting an issue on an unsupported version, what do you expect people to do? Pat you on the back?

**Comment by juliencousineau** [comment]
Guys, why such hanger, really? I'm sure that this issue will not just help me, but other idiots like you think they are. So not a waste of time at all, please start having a certain respect when you talk to peoples even hidden behind your keyboard.

**Comment by timonline** [comment]
1) Respect is earned not demanded or owed to anyone
2) Not hiding behind my keyboard when I have an actual photo of myself as the profile pic and full name in my bio.

Feel free to respond but I am not wasting any more time with "smth" like you.

**Comment by juliencousineau** [comment]
I will respond, even if I dont waste any of my time too, but I think it deserve it.

So, take the example of your mom that want to jailbreak her phone, chance are high that she will not know what is the correlation between the iOS version in the front page, even she, like me, red the whole thing back & forth for 2 days. She's stupid? not, she's just not as good as you in a certain topic. So whatever your ego's say right now, you have no right to judge. You are as stupid as me in plenty of other things, and probably make a shit loads of mistake every day, as simple as hey buddy you've forget your keys home, don't you look at the table where you left it before getting out? So the little 3 min that @ItzLevvie  he've take to just mention me that the version is not supported, is not suppose to generate any hanger to him or either of all of you that are affected by that. And yes now I will go continue my day with people, that myself gonna help, and think that I'm smart enough to deserve such respect as your n1 point said.

**Comment by KILLCAMPER** [comment]
@timonline and @juliencousineau  not one fuck was given ;)

**Comment by ann0see** [comment]
@kpwn you should include a popup which opens right after you have touched go. It could look like this: 

**Your iOS version is not supported!** Yalu102 only supports iOS 10.0.1 to 10.2. _OK_
 
But don't let the App close: there are people who fake their iOS version to a higher one...
