### ISSUE TITLE
Substrate error

### ISSUE THREAD

**Issue by MarcoS3935** [kpwn/yalu102#44]
Cydia substrate seems to make apps crash when jailbroken

**Comment by poqqq999** [comment]
Camera error

**Comment by MarcoS3935** [comment]
Camera error?

**Comment by kpwn** [comment]
I have no clue what either of you are trying to say.
Apps work fine on my iPad, can you provide syslog?

**Comment by r4m1live** [comment]
kpwn how is work with u ? its all time failed

**Comment by drake90001** [comment]
@kpwn gathering...

**Comment by drake90001** [comment]
[Untitled.txt](https://github.com/kpwn/yalu102/files/731745/Untitled.txt)

**Comment by Sticktron** [comment]
I have the same issue. After installing Substrate, apps crash instantly when trying to open them. It seems to be limited to App Store apps.

**Comment by Derewith** [comment]
Me too , what to do next?

**Comment by Sticktron** [comment]
Relevant Log:

Jan 26 02:52:41 MG6S kernel(Sandbox)[0] <Notice>: SandboxViolation: AlienBlue(1118) deny(1) file-read-metadata /Library/Frameworks/CydiaSubstrate.framework/Libraries/SubstrateBootstrap.dylib

Jan 26 02:52:41 MG6S assertiond[273] <Notice>: Unable to obtain a task name port right for pid 1118: (os/kern) failure (5)

**Comment by kasiimh1** [comment]
It happens on both 3rd party and system apps, some work some don't. using non substrate version of Yalu works, they all launch.

**Comment by kpwn** [comment]
installed AB, still can't repro. will have a 6s later this week.

**Comment by eni9889** [comment]
Can confirm this is happening for me as well:
```
release: 16.3.0
version: Darwin Kernel Version 16.3.0: Tue Nov 29 21:40:09 PST 2016; root:xnu-3789.32.1~4/RELEASE_ARM64_S8000
machine: iPhone8,2
```

**Comment by kpwn** [comment]
Could be something introduced in 10.2. I am currently testing on 10.1.1.

**Comment by eni9889** [comment]
Can confirm this is happening for me as well:
```
release: 16.3.0
version: Darwin Kernel Version 16.3.0: Tue Nov 29 21:40:09 PST 2016; root:xnu-3789.32.1~4/RELEASE_ARM64_S8000
machine: iPhone8,2
```

**Comment by kasiimh1** [comment]
Safari:

Jan 26 08:09:31 Kasiims-iPhone kernel(Sandbox)[0] <Notice>: SandboxViolation: MobileSafari(971) deny(1) file-read-metadata /Library/Frameworks/CydiaSubstrate.framework/Libraries/SubstrateBootstrap.dylib
Jan 26 08:09:31 Kasiims-iPhone assertiond[332] <Notice>: Unable to obtain a task name port right for pid 971: (os/kern) failure (5)
Jan 26 08:09:31 Kasiims-iPhone SpringBoard(FrontBoard)[314] <Error>: Unable to register for exec notifications: No such process
Jan 26 08:09:31 Kasiims-iPhone SpringBoard(BaseBoard)[314] <Error>: Unable to get short BSD proc info for 971: No such process
Jan 26 08:09:31 Kasiims-iPhone SpringBoard(BaseBoard)[314] <Error>: Unable to get proc info for 971: No such process
Jan 26 08:09:31 Kasiims-iPhone SpringBoard(BaseBoard)[314] <Error>: Unable to obtain a task name port right for pid 971: (os/kern) failure (0x5)
Jan 26 08:09:31 Kasiims-iPhone SpringBoard(BaseBoard)[314] <Error>: Unable to get short BSD proc info for 971: No such process
Jan 26 08:09:31 Kasiims-iPhone SpringBoard(FrontBoard)[314] <Error>: Unable to obtain a process handle for <FBApplicationProcess: 0x10df770a0;

**Comment by Sticktron** [comment]
You're working on a 10.2 jailbreak while on 10.1.1? lol

**Comment by Derewith** [comment]
The problem is with Cydia Substrate <- (also if you install from cydia)

**Comment by osxusr** [comment]
for instance twitter crashes upon launch when jailbroken on 10.2 on 6s

**Comment by hacx** [comment]
Doing "chmod 644 SubstrateBootstrap.dylib"   will "fix" the problem.
note the quotes on "fix" -- it does allow the crashed applications to launch, but not sure about the side effects it will cause.  **_it's just a temp life saver._**

**Comment by kpwn** [comment]
Can repro on 10.2.

**Comment by kpwn** [comment]
Last commit should have fixed it. Need someone to test on 10.1.

**Comment by MarcoS3935** [comment]
@kpwn I can confirm that all apps work on ios 10.2 iPhone 6s, Thanks!
