### ISSUE TITLE
ipad air 2 error

### ISSUE THREAD

**Issue by gurnay1973** [kpwn/yalu102#443]
I need your help, since I jailbreak yalu on an ipad air 2 and it worked correctly, but then make an erase all content and when trying to jailbreak the ipad reboots and does not install anything, sometimes the process works and says already jailbreak , But cydia is not installed.

**Comment by KILLCAMPER** [comment]
Sorry lost me on erase all content ?

**Comment by gurnay1973** [comment]
Through find my iphone and as it does not work I also did an erase all data from ipad configuration

**Comment by justinoboyle** [comment]
Can you post more information? Logs? Anything?

Keep in mind, this is for code issues, not support, so unless it's an actual problem with yalu then we will need to close.

**Comment by KILLCAMPER** [comment]
Why did you erase all data config for that will be a big problem need error report as @justinoboyle says

**Comment by gurnay1973** [comment]
Dear, I do not know how to extract this information. I came to you because I tried to consult on many websites and nobody could help me and it is very strange that I worked the first time and after doing this restoration could not work again.
I'm sorry if I'm not in the right place, but no one has been able to help me.

**Comment by KILLCAMPER** [comment]
I wouldn't of wiped any thing I would of removed your app then reinpacted it then run it again job dun where did you get del all config from you 100% can't do that . Delete the profile for the IPA plug in pc / mac 🖥 re inpact it will take few tries if you deleted config if after 3 times don't work hold power and home till re bouts and try again

**Comment by gurnay1973** [comment]
Dear slash error "Storage almost full" and the ipad is empty

**Comment by KILLCAMPER** [comment]
If say storage almost full its jail broken as soon as says that it's in a jb state palm face

**Comment by gurnay1973** [comment]
I did not understand the last comment I am sorry

**Comment by KILLCAMPER** [comment]
When you jail brake you will get a pop up saying storage full that means you jail broke not that you need to delete every thing . it's saying your jb bye saying storage full but it's not. say you hit go on the app it says storage full yes .then no apple 🍎 logo it spins i.e. Re sprigs device then you are jail broke but your  storage is not full it's a sighn  to say your jail broke it's not full god help me is this the 1st time you have jail broke a device ?

**Comment by gurnay1973** [comment]
Dear, if I have done jailbreak several times with pangu, but I did not notice that message. I have already tried deleting the profile several times and also the power and home button. Still not working

**Comment by KILLCAMPER** [comment]
Are you getting storage full but no cydia when it re boots are you getting Apple logo ? Not resorting 

Open loads of apps in background leave for few mins then got to jb app hold go for 5 seconds try this 4 to 5 times it will go if not inbetweeen try normal power off as you will get glitchy screen pixels then try again if no success hard re boot powe home hold till reboots and leave  for few mins open loads of apps in background again and  try jb app I have I pad Air 2 on 10.2 cellular and mine workers every time like this you using latest beta ?

**Comment by KILLCAMPER** [comment]
If you hpget the storage full you are in a jb state but mite not have cydia

**Comment by KILLCAMPER** [comment]
Ones it says storage full you will need to get termanel to get cydia on device as lots of bugs with mini 4 and Air 2 you using a mac

**Comment by neildufva** [comment]
UNSUBSCRIBE

**Comment by KILLCAMPER** [comment]
Yep @neildufva  i have said all I can to help

**Comment by KILLCAMPER** [comment]
Close this pleases

**Comment by KILLCAMPER** [comment]
# #442 #439
