### ISSUE TITLE
Cannot connect to App Store etc.

### ISSUE THREAD

**Issue by PhangThao1997** [kpwn/yalu102#446]
So I'm on iPhone 7 Plus 10.1.1 Jailbreak. I was running Kodi for a while, just watching some movie, and then it just rebooted my device. I open my device and check Cydia, obv Cydia doesn't work, I ran the Mach_portal. Takes like 10-20 secs before it closed the app. Then I try to open Cydia again and it start working. But how do I get my tweaks back up and working? I try to install a tweak in Cydia to make it respring but then it just get stuck in a dark screen where it wont reboot nor respring. So I got it back working using Substrate Fix (iOS 10). Now my App Store and YouTube won't work. My Gmail says No Connections. Any help? Everything runs fine. all my tweaks all working. just not like the Online Servers apps are not working if thats what you called it i guess...

I read the issue posting guidelines.

**Comment by justinoboyle** [comment]
This repo is for Yalu 10.2. #162

**Comment by PhangThao1997** [comment]
Sorry about that... Where can I post this issues to 10.1.1 iPhone 7 + Jailbreak  mach_portal?

**Comment by justinoboyle** [comment]
@PhangThao1997 All good. https://reddit.com/r/jailbreak is your best bet. Please close this issue.
