### ISSUE TITLE
iPhone 6+ offsets

### ISSUE THREAD

**Issue by ninjaprawn** [kpwn/yalu102#46]
For iOS 10.1.1:
- uname version: `Darwin Kernel Version 16.1.0: Thu Sep 29 21:56:11 PDT 2016; root:xnu-3789.22.3~1/RELEASE_ARM64_T7000`
- allproc: `0x5B4168`
- rootvnode: `0x5ba0b8`

(planning for the future)

**Comment by mrwulff** [comment]
tsmc?
