### ISSUE TITLE
No developer :(

### ISSUE THREAD

**Issue by xymwx** [kpwn/yalu102#469]
I read the issue posting guidelines.

Since I'm not a developer and willing to jailbreak my iPhone 6, the error message disrupted me tonight:
```
provision.cpp:81
ios/addDevice =5405
Unable to add device 'xyDevice' because the team has already reached the maximum number of iPhone devices.
```

What could / should be done?

**Comment by ghost** [comment]
you have too many idevices with that apple id, click on cydia impactor xcode tab and revoke certificates or use a new apple id!
