### ISSUE TITLE
syscall perf degradation

### ISSUE THREAD

**Issue by kpwn** [kpwn/yalu102#48]
a known bug is syscall perf degradation. this is due to a difference from yalub3 which will be sorted out at some point

**Comment by kpwn** [comment]
this is basically a 50% slowdown in fast syscalls such as getuid()

**Comment by kpwn** [comment]
reduced slowdown to <10%. a better job could be done.

**Comment by sunitathanommit** [comment]
https://github.com/kpwn/yalu102/issues/48#issuecomment-275347411

**Comment by sunitathanommit** [comment]
#48

**Comment by kpwn** [comment]
i think this is good enough.
if anyone has remarkably bad benchmarks, please do tell
