### ISSUE TITLE
'system' is not available on iOS

### ISSUE THREAD

**Issue by Sam1370** [kpwn/yalu102#488]
I read the issue posting guidelines.

So I'm trying to compile yalu and it's not working. It says that system is not available on iOS. Can anyone help me?
![image](https://user-images.githubusercontent.com/29418315/31590097-9ca1f8aa-b1bf-11e7-9356-a7bd3bc25463.png)

**EDIT:** Is there any way to bypass this error and continue compiling?

**Comment by Packetfahrer** [comment]
if you use Xcode 9 try Xcode 8.3.3

**Comment by Sam1370** [comment]
@Packetfahrer Thanks, I tried 8.3.3 but I get this.
![image](https://user-images.githubusercontent.com/29418315/31593827-e76ec4be-b1e5-11e7-8d05-9313ed78efe5.png)
The other error is done there so I guess that's good...

**Comment by Packetfahrer** [comment]
build it with an real Device not the Simulator!

**Comment by Sam1370** [comment]
@Packetfahrer When I try to **Product > Build** the project I get the same linker error. Any ideas?

**Comment by Sam1370** [comment]
Nevermind, thanks everyone. I redid this by reinstalling yalu on xcode 8. Thanks

**Comment by vgmoose** [comment]
If there's any future visitors, [this fix](https://github.com/libpd/pd-for-ios/issues/19#issuecomment-334133540) also works with xcode 9.2 to change all `system` calls into `run_cmd` ones.
