### ISSUE TITLE
Possible incorrect offsets for iPad Air 2 Wi-Fi

### ISSUE THREAD

**Issue by igootin** [kpwn/yalu102#49]
Whenever I try on iPad Air 2 Wi-Fi it either reboots or says "failed, retry."

**Comment by Steve-luo** [comment]
Offsets for iPad Air 2 are not included. You'll need to get them and add in yourself. If you don't know how to do that, I highly recommend you do not try to jailbreak, since it's not a stable release yet.

**Comment by igootin** [comment]
No, inside offsets.c you can clearly see that offsets for ipad air 2 are included.

**Comment by Steve-luo** [comment]
@igootin There was a commit I missed. My bad.

**Comment by igootin** [comment]
@Steve-luo
Do you have any idea why it might not be working?

**Comment by nicogibbons** [comment]
The offsets are correct. 4K devices including the iPad Air 2 aren't supported yet. Close this
