### ISSUE TITLE
IOKit/IOKitLib.h file not found

### ISSUE THREAD

**Issue by arinc900** [kpwn/yalu102#5]
/Users/arinc/Documents/yalu102/yalu102/jailbreak.m:14:9: 'IOKit/IOKitLib.h' file not found

**Comment by rpalmieri99** [comment]
That is something to do with the downloaded files. That is on your PC. It does say incomplete so maybe it is not meant to be there?

**Comment by arinc900** [comment]
I'm newbie I don't know how to download and inject it in xcode can you help me?

**Comment by mastermark1983** [comment]
same problem here on Sierra beta 4

**Comment by rpalmieri99** [comment]
Is that when trying to open the .xproj file?

**Comment by mastermark1983** [comment]
its missing on my system

**Comment by rpalmieri99** [comment]
I know, I don't believe it was ever included. Hence the name, incomplete.

**Comment by rpalmieri99** [comment]
I don't have it on my system either, it was not in the repository to download to begin with.

**Comment by arinc900** [comment]
So how did you work it

**Comment by rpalmieri99** [comment]
I mean, @kpwn correct me if I am wrong, but this is incomplete meaning that it isn't meant to work like the rest of the betas that were posted on yalu.qwertyoruiop.com

**Comment by arinc900** [comment]
OK I give up. When a COMPLETE jailbreak is out i will try it.

**Comment by rpalmieri99** [comment]
That's the right idea... wait until full release unless you know what you are doing. Hate to make it sound so negative but its just the way it is. Be patient like everyone else.

**Comment by rpalmieri99** [comment]
I am stupid, found the problem. Sorry for the false information before.

**Comment by mastermark1983** [comment]
Thx Fixed ;)

**Comment by EPiCxRIOTZZ** [comment]
how you fix it?

**Comment by MyNameIsJog** [comment]
How do you fix it?

**Comment by rpalmieri99** [comment]
If you don't know how to fix it, don't worry about using this prebeta. Wait for the full release, prebeta is only meant for users who know.

**Comment by mastermark1983** [comment]
unzip headers in Yalu dir and replace #import "IOKitLib.h"

**Comment by EPiCxRIOTZZ** [comment]
all i wanted to know is why is it saying its not found when i have it

**Comment by mastermark1983** [comment]
its not in the Yalu folder

**Comment by EPiCxRIOTZZ** [comment]
![screen shot 2017-01-25 at 23 02 41](https://cloud.githubusercontent.com/assets/24723906/22313014/6e3f345a-e352-11e6-8f73-d81ea0a415ae.png)

**Comment by mastermark1983** [comment]
https://github.com/kpwn/yalu102/files/730770/headers.zip

**Comment by natezoom** [comment]
hey can you please send me the ipa i dont have a mac email is natezoom@gmail.com @mastermark1983 @arinc900 @EPiCxRIOTZZ

**Comment by mastermark1983** [comment]
https://www.dropbox.com/s/buw9xegysgfmzd4/Yalu10.2.ipa?dl=0

**Comment by natezoom** [comment]
thanks sooooo much @mastermark1983

**Comment by Flayor** [comment]
@mastermark1983 You can send the project xcode fixed ?

**Comment by drake90001** [comment]
This isn't an issue guys, please don't spam it here.

**Comment by johndpope** [comment]
this may help some https://garynil.tw/2017/01/298

**Comment by arinc9** [comment]
Thanks. I learned so much in past 8 months. Now I know so much things in Xcode.

**Comment by arinc9** [comment]
many*
