### ISSUE TITLE
offsets for iPad Air 2 Wi-Fi?

### ISSUE THREAD

**Issue by igootin** [kpwn/yalu102#50]

**Comment by liudayu** [comment]
Yeah what about it?

**Comment by igootin** [comment]
@liudayu Uhhh... the ones included are probably wrong because whenever i press go it reboots without installing cydia, or just says "failed, retry"

**Comment by nicogibbons** [comment]
That's because 4K devices aren't supported.

**Comment by nicogibbons** [comment]
@kpwn Please close his two "issues"
