### ISSUE TITLE
Adding Support for iPhone 5S and iPhone 6 ?

### ISSUE THREAD

**Issue by i0s1q** [kpwn/yalu102#54]
Adding Support for iOS 10.1.1 for the iPhone 5S and 6 ?

Thanks for your hard work

**Comment by liudayu** [comment]
"this is for 16k devices (6s, ipad pro) only at this moment. i won't have the ability to test on a 4k device until the weekend."
#28

**Comment by Dibbyo456** [comment]
**I would love see my iPhone 6 jailbroken iOS 10.**

**Comment by liudayu** [comment]
It is jailbreakable... Can you just be a little bit patient, please.

**Comment by i0s1q** [comment]
Okay :-/
I hopefully add more Devices (iPhone 5S and higher)

Thanks for the help!

**Comment by liudayu** [comment]
All 64 bit devices from iOS10.x - 10.2 will be supported
/close

**Comment by Dibbyo456** [comment]
@liudayu I am currently on iPhone 6 iOS 9.3.3 JB. So, should I update to iOS 10.2 now? Or wait for the JB to drop by? I have saved SHSH Blobs though.

**Comment by i0s1q** [comment]
The question is when will the devices be added, right?
Thanks for your help

**Comment by Dibbyo456** [comment]
@i0s1q We both know, in jb community "will be" means forever.

**Comment by liudayu** [comment]
@Dibbyo456 If you don't need iOS10's features then stay at 9.3.3 is completely fine. 
Also, will be means will be, keep your sarcasm to yourself, please.

**Comment by i0s1q** [comment]
@liudayu I can test it if I had access, I test many Betas officially but as Jailbreak tester I probably do not question
