### ISSUE TITLE
Add Support for iPhone 6S | N71AP

### ISSUE THREAD

**Issue by Derewith** [kpwn/yalu102#55]
else if (strcmp(u.version, "Darwin Kernel Version 16.3.0: Tue Nov 29 21:40:09 PST 2016; root:xnu-3789.32.1~4/RELEASE_ARM64_S8000") == 0) {
        allproc_offset = 0x5a8438;
        procoff = 0x360; // iphone 6s N71AP , credit to @jonderewith
        rootvnode_offset = 0x5b20b8;
     }

**Comment by Sticktron** [comment]
Your rootvnode offset is wrong, you forgot to subtract the base address.
The 6s is already supported, offsets are the same for all models.

**Comment by Derewith** [comment]
Is not wrong trust me is working for me in this way

**Comment by DevX-Cipher** [comment]
how did you find procoff offset
