### ISSUE TITLE
where to download ipa file

### ISSUE THREAD

**Issue by ahlawatashu** [kpwn/yalu102#62]
i am not able to found ipa file can someone please tell me where to download yalu 102 .ipa and when are u gonna add support for iphone 5s.
pls help. :<

**Comment by chris-etheridge** [comment]
If you're looking for the IPA, this isn't for you.

**Comment by chris-etheridge** [comment]
But, if you want, you can compile it using XCode.

**Comment by ahlawatashu** [comment]
https://github.com/zhengmin1989/yalu102/blob/master/yalu102.ipa
then whats this dude

**Comment by nicogibbons** [comment]
That's a guy who compiled and probably shouldn't have

**Comment by ahlawatashu** [comment]
but why

**Comment by chris-etheridge** [comment]
That is a fork of a project, so he is welcome to do what he wants – that doesn't mean its necessarily right.

Wait for the owners of this repo to create an IPA, that is ready for general users to use.

**Comment by ahlawatashu** [comment]
ok thanks i got it 
but can u pls tell me how much time its gonna take

**Comment by duthli** [comment]
U need compile before use :)

**Comment by chris-etheridge** [comment]
It will be ready when its ready.

**Comment by ashraf008** [comment]
can you tell me why i'm gettin ioKitLib.h not found error

**Comment by ahlawatashu** [comment]
ok thanks all of u specially chris

**Comment by chris-etheridge** [comment]
You need to add IOKit to the project.

**Comment by chris-etheridge** [comment]
No problem. I'm sure the owners of this repo will make an announcement when it is ready, for the general public.
