### ISSUE TITLE
iPad Air 2 

### ISSUE THREAD

**Issue by KILLCAMPER** [kpwn/yalu102#66]
Hi is there iPad Air 2 cellular support  and is any one compiled it yet as a ipa any one help thanks

**Comment by neerajvohra** [comment]
Compile yourself and test it. It's not stable yet. Wait for the owner to confirm if it's stable.

**Comment by cawk** [comment]
No it is not supported 4K devices are not supported

**Comment by neerajvohra** [comment]
@cawk https://github.com/kpwn/yalu102/issues/40

**Comment by cawk** [comment]
Yes we have the offsets but it still doesn't work I have already tried that then reading through other issues and responses from luca he says he only has access to 16k device until the weekend so we have to wait till then until 4K devices are supported then the offsets we have will work 

What I got from reading the other issues correct me if I'm wrong luca
