### ISSUE TITLE
iPhone 6s N71m failed retry (Jailbreak)

### ISSUE THREAD

**Issue by mastermark1983** [kpwn/yalu102#7]
iPhone 6s N71m failed try again ;)

it doesn,t work

**Comment by Sn0wFr1tz** [comment]
lol im having the same issue with the same exact phone. im working on a fix on my end rn.

**Comment by mastermark1983** [comment]
I think its not supposed for n71m

**Comment by matthewsamuel2002** [comment]
Is this basically equivalent to Ian Beer's  mach_portal? It doesnt have cydia??

**Comment by mastermark1983** [comment]
Cydia is inside

**Comment by rpalmieri99** [comment]
Hm I might have told a lot of people wrong then @mastermark1983 

Is it not supposed to be complete yet as in barely working?

**Comment by matthewsamuel2002** [comment]
I have a question. Is this legit straight from Luca? Because he never said anything about this on twitter.

**Comment by mastermark1983** [comment]
my xcode is failed and the version I have from mohadu failed on my iPhone 6s I can't test it

**Comment by rpalmieri99** [comment]
Sweet jesus we are on that level... yes. For a reason, to keep morons away from it. Stop the "when" and "its not working" tweets.

**Comment by drake90001** [comment]
Guys, look at closed issue #1 , its already been discussed and luca said what you needed to do. I got the rootvnode for the 6s, headed to school now, once i get there ill get the other.

**Comment by natezoom** [comment]
hey @mastermark1983 can you compile the new one?
