### ISSUE TITLE
No scp/sftp with Dropbear. Safe to use OpenSSH instead?

### ISSUE THREAD

**Issue by Sticktron** [kpwn/yalu102#74]
Or is there a way to get scp/sftp with Dropbear?

**Comment by onchehuh** [comment]
```
cat iosbinpack64/usr/bin/scp | ssh root@iphone "cat > remote"
ssh root@iphone
mv remove /usr/bin/scp
```
Then you have scp

**Comment by Sticktron** [comment]
Thanks.
Still wondering if there's anything inherently wrong with using OpenSSH with this jailbreak though.

**Comment by mc07040654** [comment]
10.2 Comple Guide Video
https://www.youtube.com/watch?v=OyG18xtcRUI

**Comment by Sticktron** [comment]
Thanks but I have scp now.

A lot of (most?) developers are going to want scp/sftp, it would be preferable to be able to install OpenSSH via Cydia for one-step ssh+scp+sftp. Is there an incompatibility with yalu that's forcing Luca to install dropbear?

**Comment by onchehuh** [comment]
Maybe something that would try to launch at startup, causing problems as it's not jailbroken at startup until Yalu is launched

**Comment by Sticktron** [comment]
Yalu reloads launch daemons after jailbreaking, so I don't fink that's the issue.

**Comment by onchehuh** [comment]
But what if a daemon containing unsigned code tries to launch at startup before Yalu is launched ?

**Comment by Sticktron** [comment]
It fails to load until Yalu tries reloading it after jailbreaking (via the reload script in the source files)

**Comment by kpwn** [comment]
openssh is not compatible with iOS 10

**Comment by Sticktron** [comment]
That's the problem then :) thank you for the clarification.

**Comment by dweinstein** [comment]
this `sftp-server` will work if copied to `/usr/libexec/sftp-server` https://github.com/dweinstein/openssh-ios/releases

**Comment by Perry-G** [comment]
Your sftp-server code works like a charm dweinstein !! I had to create a fee github account just to say a big thanks! Much appreciated! God Bless!!
Perry

**Comment by dweinstein** [comment]
You're welcome! :-)

**Comment by jkryanchou** [comment]
Using iFunbox to drag you file into the directory which you want to store.
