### ISSUE TITLE
iPhone 7 10.1.1

### ISSUE THREAD

**Issue by Shmadul** [kpwn/yalu102#78]
My iPhone 7 is on iOS 10.1.1, is it supported, I know 10.2 isn't but heard 10.1.1 is , but I keep getting failed, retry

**Comment by castiel652** [comment]
iPhone 7 is not supported.

**Comment by 4taras4** [comment]
Issue is here: #64

**Comment by liudayu** [comment]
iPhone 7 on iOS10.1.1 is not supported at this stage, currently, yalu102 only supports 6s/SE and iPad Pro 10.0/10.1/10.2.
