### ISSUE TITLE
iPhone 5s Support

### ISSUE THREAD

**Issue by JuG2001** [kpwn/yalu102#79]
When does Yalu support iPhone 5s?

**Comment by olirehacek** [comment]
Please, this is not a place to ask question. Discuss only Code related problems and issues here.

**Comment by liudayu** [comment]
Please search existing issues before you post anything.

[qwertyoruiop's original reply](https://github.com/kpwn/yalu102/issues/28#issuecomment-275305581)

**Comment by JuG2001** [comment]
sorry

**Comment by liudayu** [comment]
Please close this issue, thank you
