### ISSUE TITLE
Build issues...

### ISSUE THREAD

**Issue by anayw2001** [kpwn/yalu102#8]
When I try to build yalu102.app in Xcode 8.2, I get a lot of kernel linking errors

**Comment by opendata26** [comment]
Add the headers

**Comment by anayw2001** [comment]
I did

**Comment by danielwang404** [comment]
We need more info, what did you do?

**Comment by anayw2001** [comment]
I added these: https://github.com/obaby/IOKit, anything else i should add

**Comment by matthewsamuel2002** [comment]
Is this supported for iphone 6

**Comment by anayw2001** [comment]
64-bit = iPhone 5S and above. So yes, it is supported
