### ISSUE TITLE
After Jailbreaking Nothing happens

### ISSUE THREAD

**Issue by CrypticGit** [kpwn/yalu102#80]
After jailbreaking i get the normal backlit blackscreen but after about a minute it restarts

**Comment by JuG2001** [comment]
Which iPhone do you have?

**Comment by liudayu** [comment]
What device do you have and what iOS are you running?

**Comment by Skiddi3** [comment]
Can you leave us a log?

**Comment by CrypticGit** [comment]
Its just the normal log @Skiddi3

**Comment by dallasgroot** [comment]
I have this same problem.... (installed via ipa) iPhone 6s (Samsung chip)

**Comment by CrypticGit** [comment]
IOS 10.2 Iphone 6s samsung @liudayu @JuG2001 I edited the offsets and deleted the other ones.

**Comment by liudayu** [comment]
You don't need to delete the other codes. 
Can you show me what your offset.c looks like now please?
And please paste your log here as well, it will help.

**Comment by CrypticGit** [comment]
It's just the one with iPhone 6s/iPad Pro. I just changed the rootvnode to the correct one.

**Comment by 0x0luke** [comment]
@CrypticGit Would you mind posting your log and as liudayu requested your offsets.c? There isn't a need to remove the other offsets :)

**Comment by CrypticGit** [comment]
@0x0luke  I can't I'm on my way to school

**Comment by liudayu** [comment]
From your description, I couldn't determine what caused your problem, you need to show us what's your code looks like and what is your output. Otherwise, we will not be able to help you.

**Comment by CrypticGit** [comment]
@liudayu i can't till I get home later

**Comment by tangalbert919** [comment]
Ok. We will wait 8 hours, and hope @kpwn doesn't close this thread because this does not sound like a code issue.

**Comment by CrypticGit** [comment]
@tangalbert919 the old code worked fine

**Comment by tangalbert919** [comment]
At the very least, show us what offsets you used. You said you changed the offsets, so we need to know what you used.

**Comment by skimaskngun** [comment]
so should I wait a few days to jb my 6s on 10.2 then?

**Comment by skimaskngun** [comment]
probably shouldnt jump on the first beta train anyway.

**Comment by CrypticGit** [comment]
Somehow it works now after many attempts of jailbreaking without hard resetting it jailbroke and now works every time
