### ISSUE TITLE
Iphone 6 Support 

### ISSUE THREAD

**Issue by mazmol1** [kpwn/yalu102#83]
Iphone 6 on 10.2 ( 14c92)
Offset required adding please also

**Comment by liudayu** [comment]
Please search existing issues before you post any new issue.

Currently, the jailbreak only support 6s/SE and iPad Pro 10.0/10.1/10.2, so you iPhone 5s **IS NOT SUPPORTED**, wait until qwertyoruiop adds more devices support.

Please close this issue
