### ISSUE TITLE
[Question] IPhone 5 Global 32 bit 

### ISSUE THREAD

**Issue by mazmol1** [kpwn/yalu102#84]
I am currently on 10.1.1 and i window has closed is there any way that support for it be there in the future or will it be a long wait.. thanks if this is not relevant and don't want to answer just reply with close thread thanks

**Comment by liudayu** [comment]
Bruh, 64 bit only, **NO SUPPORT** for 32 bit

**Comment by liudayu** [comment]
Close this issue please.
