### ISSUE TITLE
iPhone 6 Plus and 5s adding support on iOS 10.2

### ISSUE THREAD

**Issue by patrickawsomeness1** [kpwn/yalu102#86]
Because some people need to work on the Cydia tweak but only have iPhone 6 or 5s

**Comment by ONSOHO** [comment]
Hey, The weekend will clear that up.

**Comment by liudayu** [comment]
He doesn't have devices to test until weekends.
[Source](https://github.com/kpwn/yalu102/issues/28#issuecomment-275305581)

**Comment by RalphGuevara** [comment]
Please stop asking for older device support.

**Comment by KILLCAMPER** [comment]
64 bit devices will be added he is waiting on them for weekend just wait it will all fall in to place it takes time and a lot of hrs for the guys putting in the codes and the offsets and testing . @RalphGuevara  chill man attitude is what killed the dev teams politeness cost Notting .

**Comment by FNCxPro** [comment]
#64

**Comment by RalphGuevara** [comment]
@KILLCAMPER I wasn't trying to give attitude :b buuut he needs to look at closed posts, as well as #64. just trying to be a little honest.

**Comment by KILLCAMPER** [comment]
I no buuuut he is probably new and thinks this is like Reddit as it's been posted hear and he a new so give the benefit of the doubt bud keep it all 2 thumbs friend ;) 👍👍

**Comment by jordaonet** [comment]
Hi. 

Just wanted to thank you guys and specially Luca and Marco for all the hard work.

I managed to compile and install yesterday's version on my 6+ with 10.2, although I know nothing of C despite having a iMac, which allowed me to do that. 

If any help is needed to speed up the tests, and has long as apple signs 10.2, count me in !!!

Been a jbreaker since 3.0.1 !!! 

Can't just use the iPhone without it, due to tweaks like activator or springtomize just to name a few. 

Like me, there are a lot of jb users who don't give a damn to cracked apps or games...

Thx once again. 

Muita força desde Portugal Luca e Marco. 

Grazzie tante

**Comment by mwoolweaver** [comment]
This issue should be closed...

**Comment by Fr0stExe** [comment]
I like how @Ralphguevara got dislikes because he just pretty much told people the rule that they should already know to stop asking for support it's literally right when you load the github page

Then that other dude just copy's him saying "buuuut" talk about attitude "bud" 😂😂😂

**Comment by RalphGuevara** [comment]
It was mainly my fault anyway, i guess i sounded too mean.

**Comment by KILLCAMPER** [comment]
@Fr0stExe  just was saying polite the way we can all help each other I do apologies if I put buuut .all ways think it's good to be polite sorry just the way I was I was raised. @RalphGuevara if you didn't mean it with attitude I do apologise and I do mean that just trying to help same as you guys

**Comment by RalphGuevara** [comment]
Nah your fine @KILLCAMPER, were all fellow jailbreakers here c:

**Comment by KILLCAMPER** [comment]
@RalphGuevara top guy I get what your saying tho same emails same question again and again wish you all the best bud

**Comment by ntassani** [comment]
@jordaonet Hi! How you get iokit for compile for i6+ ?

**Comment by jordaonet** [comment]
@ntassani hi I've downloaded it from a link in one of the threads here. 
Currently of to work and can't send it to you. If you need it I can send them to you later tonight.

**Comment by jordaonet** [comment]
@ntassani here is the link:
[https://github.com/kennytm/iphone-private-frameworks/tree/master/IOKit]

1) Download as .zip
2) unzip it to your "yalu102" folder.
3) rename the extracted folder to "IOKit"
4) edit jailbreak.m file line 14 replacing `#import <IOKit/IOKitLib.h>` for `#import "IOKit/IOKitLib.h"`.

This is how I managed to build it and run it from xCode into my iPhone 6+ with iOS 10.2. Hope it helps !!!

**Comment by kpwn** [comment]
Stop posting links to copyrighted IOKit headers.

**Comment by jordaonet** [comment]
@kpwn 
Sorry for that. Already edited my post.

**Comment by adi2k17** [comment]
Bro, can you add a JB support for iphone6,1 @REQUSTED

**Comment by AbouImran** [comment]
JB for iPhone 6 iOS 10.1.1 done
