### ISSUE TITLE
on cydia app homepage . when clicking anything greys out . doesnt work 

### ISSUE THREAD

**Issue by subhamshaw** [kpwn/yalu102#88]
when i click on anything on cydia apps's homepage . the button turns grey . nothing happens

other than that all are working- add sources and can install tweaks 

cannot login to cydia account

**Comment by Elronnd** [comment]
This is a cydia problem, not a jailbreak problem.  Please see #64.

**Comment by Amcio** [comment]
but i will still answer your question. Update to cydia beta or swipe to the left or something.

**Comment by moridaffy** [comment]
There's a beta version of Cydia on saurik's repo, which fixes that.
Here's the repo: http://apt.saurik.com/beta/cydia-arm64/
