### ISSUE TITLE
Add Support

### ISSUE THREAD

**Issue by AdibSadman** [kpwn/yalu102#89]
There is no support for any iPad Air 2 wifi or other iPads other than the iPad Pro

Please add support to air 2 because nothing happens when you run the yalu102 app on air 2

Thanks

**Comment by KILLCAMPER** [comment]
@AdibSadman sorry to say this is true and this site is for coding and issues it will be added in time buy the active coders on this site pleases wait and read the read file on the mane page as it sates what it is only compatible with at moment .

**Comment by RajPatel0929** [comment]
wait dude, let them get this all working 1st, even I'm waiting for support for my iPhone... just wait it out like everyone ... and post that in r/jailbreak not here as this is for reporting error/code and shit.

**Comment by AdibSadman** [comment]
My bad sorry guys
