### ISSUE TITLE
Read-only filesystem

### ISSUE THREAD

**Issue by CrypticGit** [kpwn/yalu102#91]
For some reason jailbreak doesn't grant me right access

**Comment by KILLCAMPER** [comment]
Have you got a log for error codes

**Comment by CrypticGit** [comment]
@KILLCAMPER I'm at school

**Comment by drake90001** [comment]
rootvnode offset, what device? newest commit?

**Comment by CrypticGit** [comment]
I'll have to get newest when I get home and see if it still happens@drake90001 iPhone 6s 10.2 rootvnode

**Comment by CrypticGit** [comment]
@kpwn does Yalu have to use app groups or will it eventually be installed through safari

**Comment by kpwn** [comment]
you started with a question and you ended by saying you can't try solutions and started asking unrelated question. And this is like your 10th issue. 

Try properly explaining what happened; giving output from Yalu; giving a syslog, etc.

I am closing this for derailing. Feel free to open a new issue about this, but please do it properly.
