### ISSUE TITLE
I need a .ipa to test this, mac is broken

### ISSUE THREAD

**Issue by jakeHq** [kpwn/yalu102#92]
Can someone leave me an ipa freshly compiled with the all offsets commit (latest)

**Comment by ryanb93** [comment]
Fix and build from source or wait for the next version to be compiled by Luca or Kpwn. Don't trust other people's IPA files, as stated [here](https://yalu.qwertyoruiop.com/)

**Comment by jakeHq** [comment]
orlly?

**Comment by jakeHq** [comment]
wow, ok.. that's cool...

**Comment by jakeHq** [comment]
keep downvoting kiddos!!! Let's go!

**Comment by jakeHq** [comment]
Oh, If someone says "mac is broken" I'm pretty sure they don't have a fucking working mac to build an xcode project on.

**Comment by ryanb93** [comment]
Then you need to wait until there is another release.

**Comment by RalphGuevara** [comment]
Hey man ,why are you starting drama on here. it doesn't hurt to wait till there is an actual iPA for the jailbreak. 

If anything you are lucky you get a jailbreak right now because my iPhone 6 isn't compatible right now but i'm just waiting,

**Comment by jakeHq** [comment]
kek

**Comment by jakeHq** [comment]
faggots at the finest.

**Comment by jakeHq** [comment]
Downvote ASAP!!! WE NEED MORE SKIDS!!!!

**Comment by nicogibbons** [comment]
Please close. If you can't compile use the IPA found on: yalu.qwertyoruiop.com

**Comment by xMilesManx** [comment]
You are the literal definition of scum. Please close this issue.

**Comment by jakeHq** [comment]
kek

**Comment by Skiddi3** [comment]
"WE NEED MORE SKIDS!!!!"

> Opens issue called: "I need a .ipa to test this, mac is broken"

**Comment by jakeHq** [comment]
kek

**Comment by jakeHq** [comment]
K K K

**Comment by liudayu** [comment]
Maybe should get your IQ checked asap.
Close this issue please.

**Comment by jakeHq** [comment]
k dad

**Comment by jakeHq** [comment]
close issue

**Comment by jakeHq** [comment]
MACHINE DO YOUR WORK!11!1!!11 CLOSE THE ISSUE1!1!11

**Comment by jakeHq** [comment]
oh found the button.

**Comment by vmunich** [comment]
There's an IPA already on Luca's site https://yalu.qwertyoruiop.com/

**Comment by jakeHq** [comment]
stfu bitch

**Comment by liudayu** [comment]
@vmunich is right. You don't need a Mac to jailbreak your iOS devices. Download ipa from https://yalu.qwertyoruiop.com and then use cydia impactor to install on your device.

**Comment by jakeHq** [comment]
So you're assuming my device? iPod touch 6

**Comment by jakeHq** [comment]
@xMilesManx ikr

**Comment by jakeHq** [comment]
soo scummy!11111111!!1!!11

**Comment by liudayu** [comment]
iPod touch 6 is currently not supported, qwertyoruiop will add support during this weekend.

**Comment by jakeHq** [comment]
The offsets are the src in already, not the IPA tho. dumbass

**Comment by vmunich** [comment]
@jakeHq no device older than the 6S will work, even with the right offsets, wait until it gets fixed this weekend.

**Comment by jakeHq** [comment]
Nigload.exe
