### ISSUE TITLE
IPad Air 2 support please

### ISSUE THREAD

**Issue by AdibSadman** [kpwn/yalu102#96]

**Comment by meyer9** [comment]
He will not be able to test 4k processors until the weekend.

**Comment by AdibSadman** [comment]
Thanks I have been waiting for so long for a jb for iPad Air 2 wifi

**Comment by xMilesManx** [comment]
I have read at least 9 times, that you should not use the issues tab to ask for device support. It's only for code issues only. Please do some research.

**Comment by AdibSadman** [comment]
Alright. I'm no expert here but all I am saying is that I hope support for iPad Air 2 will be added. I have been very patient.

Thanks to all for the hard work!
