### ISSUE TITLE
There is no "no substrate" mode

### ISSUE THREAD

**Issue by haza1608** [kpwn/yalu102#97]
I'm referring to when you hold the volume up to jailbreak without activating substrate.

**Comment by tangalbert919** [comment]
The issue tab is for code-related issues only, because @kpwn already gets fed up to every issue that has everything to do with device support, and nothing about code. Also, why do you need to enter "no substrate" mode?

**Comment by haza1608** [comment]
I have a tweak that's preventing me getting past the lock screen whilst jailbroken.

**Comment by ipadkid358** [comment]
Please confirm that you're attempting this in the correct manner. Official Reddit tutorial is below

##How to enter No Substrate mode on iOS 10.2 (Yalu102)

1. Open Yalu102

2. **Hold the volume up button from this point on**

3. Tap Go

4. You'll know if you're in No Substrate mode after the respring because Cydia will be able to open. No tweaks will work

**Comment by haza1608** [comment]
No luck. I'll have to SSH into my phone to fix it.

**Comment by tangalbert919** [comment]
I'm going to try to add 4k device support myself, but that will be dangerous because I don't have any knowledge on Objecive-C. I only know Java, and a little bit of Python.

**Comment by meyer9** [comment]
Checkout https://github.com/kpwn/yalu102/issues/40

**Comment by ipadkid358** [comment]
This is extremely unrelated to the issue

**Comment by tangalbert919** [comment]
This isn't a code issue either, but nobody bothers to say "close this issue"?

**Comment by haza1608** [comment]
You're not supposed to create support threads. This is not a support thread, it's more of a suggestion/improvement

**Comment by meyer9** [comment]
It is, but I was just trying to help him.

**Comment by kpwn** [comment]
I think I am aware of why this is happening. I will try to fix it. Thanks for this bug report.

**Comment by kpwn** [comment]
Fixed in last commit. Closing issue, but please comment if it works for you now.
