### ISSUE TITLE
add it to i7 please

### ISSUE THREAD

**Issue by hazemustafa** [kpwn/yalu102#98]

**Comment by tangalbert919** [comment]
This is not a code-related issue, nor does it sound like an issue at all.
If your iPhone 7 is on iOS 10.2, you're f***ed. If you're on iOS 10.1.1 or below, it already exists.

**Comment by DarknesGaming** [comment]
Honestly, if you're really trying to join the millions of dummies who constantly ask for device support, guess what, @hazemustafa? You just joined the ranks.
Sit back and let the developers do their thing.

**Comment by meyer9** [comment]
#64

**Comment by RalphGuevara** [comment]
I feel bad for the Devs, They have to keep deleting/closing threads because people aren't taking the time to look at the questions asked and reading rules.

**Comment by DarknesGaming** [comment]
Same here. The problem: That README file doesn't have any rules. They don't even know what the guidelines are to make an issue that won't be closed.
